package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle98DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 469 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertEquals(true, if ((obj.entry[211].resource!! as Patient).active != null) (obj.entry[211].resource!! as Patient).active else false, "Field: (obj.entry[211].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[211].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Butler", (obj.entry[211].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Jane", (obj.entry[211].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[211].resource!! as Patient).gender))
        assertEquals("1944-09-19", (obj.entry[211].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[211].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[212].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[212].resource!! as Patient).resourceType))
        assertTrue(stringMatch("283", (obj.entry[212].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[212].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[212].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[212].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[212].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[212].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[212].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577602", (obj.entry[212].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[212].resource!! as Patient).active != null) (obj.entry[212].resource!! as Patient).active else false, "Field: (obj.entry[212].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[212].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Spencer", (obj.entry[212].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Herbert", (obj.entry[212].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[212].resource!! as Patient).gender))
        assertEquals("1955-09-19", (obj.entry[212].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[212].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[213].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[213].resource!! as Patient).resourceType))
        assertTrue(stringMatch("284", (obj.entry[213].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[213].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[213].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[213].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[213].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[213].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[213].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577603", (obj.entry[213].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[213].resource!! as Patient).active != null) (obj.entry[213].resource!! as Patient).active else false, "Field: (obj.entry[213].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[213].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("White", (obj.entry[213].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Heidi", (obj.entry[213].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[213].resource!! as Patient).gender))
        assertEquals("1947-11-25", (obj.entry[213].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[213].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[214].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[214].resource!! as Patient).resourceType))
        assertTrue(stringMatch("285", (obj.entry[214].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[214].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[214].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[214].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[214].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[214].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[214].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577604", (obj.entry[214].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[214].resource!! as Patient).active != null) (obj.entry[214].resource!! as Patient).active else false, "Field: (obj.entry[214].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[214].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Colon", (obj.entry[214].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Joyce", (obj.entry[214].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[214].resource!! as Patient).gender))
        assertEquals("1984-09-19", (obj.entry[214].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[214].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[215].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[215].resource!! as Patient).resourceType))
        assertTrue(stringMatch("286", (obj.entry[215].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[215].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[215].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[215].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[215].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[215].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[215].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577605", (obj.entry[215].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[215].resource!! as Patient).active != null) (obj.entry[215].resource!! as Patient).active else false, "Field: (obj.entry[215].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[215].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Cunningham", (obj.entry[215].resource!! as Patient).name[0].family))
    }
}
