package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle23DataTest : DataTests() {
    @Test
    fun `diagnosticreport-hla-genetics-results-example 388 Test`() {
        val json = File("./src/test/resources/model/sample_data/diagnosticreport-hla-genetics-results-example.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("urn:uuid:c233ad3d-1572-48d6-9", (obj.entry[16].resource!! as Observation).related[1].target.reference))
        assertTrue(stringMatch("HLA-B*15:01:01:01, exon 3", (obj.entry[16].resource!! as Observation).related[1].target.display))
        assertTrue(stringMatch("POST", obj.entry[16].request!!.method))
        assertTrue(stringMatch("Observation", obj.entry[16].request!!.url))
        assertTrue(stringMatch("urn:uuid:792be53e-d4fb-4887-a", obj.entry[17].fullUrl))
        assertTrue(stringMatch("Observation", (obj.entry[17].resource!! as Observation).resourceType))
        assertTrue(stringMatch("generated", (obj.entry[17].resource!! as Observation).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[17].resource!! as Observation).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/Structure", (obj.entry[17].resource!! as Observation).extension[0].url))
        assertTrue(stringMatch("http://www.genenames.org", (obj.entry[17].resource!! as Observation).extension[0].valueCodeableConcept!!.coding[0].system))
        assertTrue(stringMatch("HGNC:4932", (obj.entry[17].resource!! as Observation).extension[0].valueCodeableConcept!!.coding[0].code))
        assertTrue(stringMatch("HLA-B", (obj.entry[17].resource!! as Observation).extension[0].valueCodeableConcept!!.coding[0].display))
        assertTrue(stringMatch("http://hl7.org/fhir/Structure", (obj.entry[17].resource!! as Observation).extension[1].url))
        assertTrue(stringMatch("http://www.ebi.ac.uk/cgi-bin/", (obj.entry[17].resource!! as Observation).extension[1].valueCodeableConcept!!.coding[0].system))
        assertTrue(stringMatch("B*57:01:01", (obj.entry[17].resource!! as Observation).extension[1].valueCodeableConcept!!.coding[0].code))
        assertTrue(stringMatch("HLA-B*57:01:01G", (obj.entry[17].resource!! as Observation).extension[1].valueCodeableConcept!!.coding[0].display))
        assertTrue(stringMatch("http://hl7.org/fhir/Structure", (obj.entry[17].resource!! as Observation).extension[2].url))
        assertTrue(stringMatch("http://loinc.org", (obj.entry[17].resource!! as Observation).extension[2].valueCodeableConcept!!.coding[0].system))
        assertTrue(stringMatch("LA6683-2", (obj.entry[17].resource!! as Observation).extension[2].valueCodeableConcept!!.coding[0].code))
        assertTrue(stringMatch("germline", (obj.entry[17].resource!! as Observation).extension[2].valueCodeableConcept!!.coding[0].display))
        assertTrue(stringMatch("http://hl7.org/fhir/Structure", (obj.entry[17].resource!! as Observation).extension[3].url))
        assertTrue(stringMatch("urn:uuid:a19a3557-b36c-4b35-a", (obj.entry[17].resource!! as Observation).extension[3].valueUri))
        assertTrue(stringMatch("final", (obj.entry[17].resource!! as Observation).status))
        assertTrue(stringMatch("http://loinc.org", (obj.entry[17].resource!! as Observation).code.coding[0].system))
        assertTrue(stringMatch("57291-7", (obj.entry[17].resource!! as Observation).code.coding[0].code))
        assertTrue(stringMatch("HLA-B [Type] by High resoluti", (obj.entry[17].resource!! as Observation).code.coding[0].display))
        assertTrue(stringMatch("Patient/119", (obj.entry[17].resource!! as Observation).subject!!.reference))
        assertTrue(stringMatch("Mary Chalmers", (obj.entry[17].resource!! as Observation).subject!!.display))
        assertEquals("2016-12-15", (obj.entry[17].resource!! as Observation).effectiveDateTime.toString())
        assertTrue(stringMatch("Specimen/120", (obj.entry[17].resource!! as Observation).specimen!!.reference))
        assertTrue(stringMatch("buccal swab from Mary Chalmer", (obj.entry[17].resource!! as Observation).specimen!!.display))
        assertTrue(stringMatch("derived-from", (obj.entry[17].resource!! as Observation).related[0].type))
        assertTrue(stringMatch("urn:uuid:05fa52d7-5c67-460a-8", (obj.entry[17].resource!! as Observation).related[0].target.reference))
        assertTrue(stringMatch("HLA-B*57:01:01, exon 2", (obj.entry[17].resource!! as Observation).related[0].target.display))
        assertTrue(stringMatch("derived-from", (obj.entry[17].resource!! as Observation).related[1].type))
        assertTrue(stringMatch("urn:uuid:db69e549-6267-4777-b", (obj.entry[17].resource!! as Observation).related[1].target.reference))
        assertTrue(stringMatch("HLA-B*57:01:01, exon 3", (obj.entry[17].resource!! as Observation).related[1].target.display))
        assertTrue(stringMatch("POST", obj.entry[17].request!!.method))
        assertTrue(stringMatch("Observation", obj.entry[17].request!!.url))
        assertTrue(stringMatch("urn:uuid:60613a43-c4cb-4502-b", obj.entry[18].fullUrl))
        assertTrue(stringMatch("Observation", (obj.entry[18].resource!! as Observation).resourceType))
        assertTrue(stringMatch("generated", (obj.entry[18].resource!! as Observation).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[18].resource!! as Observation).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/Structure", (obj.entry[18].resource!! as Observation).extension[0].url))
        assertTrue(stringMatch("http://www.genenames.org", (obj.entry[18].resource!! as Observation).extension[0].valueCodeableConcept!!.coding[0].system))
        assertTrue(stringMatch("HGNC:4932", (obj.entry[18].resource!! as Observation).extension[0].valueCodeableConcept!!.coding[0].code))
        assertTrue(stringMatch("HLA-B", (obj.entry[18].resource!! as Observation).extension[0].valueCodeableConcept!!.coding[0].display))
        assertTrue(stringMatch("http://hl7.org/fhir/Structure", (obj.entry[18].resource!! as Observation).extension[1].url))
        assertTrue(stringMatch("http://loinc.org", (obj.entry[18].resource!! as Observation).extension[1].valueCodeableConcept!!.coding[0].system))
        assertTrue(stringMatch("LA6683-2", (obj.entry[18].resource!! as Observation).extension[1].valueCodeableConcept!!.coding[0].code))
        assertTrue(stringMatch("germline", (obj.entry[18].resource!! as Observation).extension[1].valueCodeableConcept!!.coding[0].display))
        assertTrue(stringMatch("final", (obj.entry[18].resource!! as Observation).status))
        assertTrue(stringMatch("http://loinc.org", (obj.entry[18].resource!! as Observation).code.coding[0].system))
        assertTrue(stringMatch("57291-7", (obj.entry[18].resource!! as Observation).code.coding[0].code))
        assertTrue(stringMatch("HLA-B [Type] by High resoluti", (obj.entry[18].resource!! as Observation).code.coding[0].display))
        assertTrue(stringMatch("Patient/119", (obj.entry[18].resource!! as Observation).subject!!.reference))
        assertTrue(stringMatch("Mary Chalmers", (obj.entry[18].resource!! as Observation).subject!!.display))
        assertEquals("2016-12-15", (obj.entry[18].resource!! as Observation).effectiveDateTime.toString())
        assertTrue(stringMatch("Specimen/120", (obj.entry[18].resource!! as Observation).specimen!!.reference))
        assertTrue(stringMatch("buccal swab from Mary Chalmer", (obj.entry[18].resource!! as Observation).specimen!!.display))
        assertTrue(stringMatch("derived-from", (obj.entry[18].resource!! as Observation).related[0].type))
        assertTrue(stringMatch("urn:uuid:e2092243-2970-49d2-a", (obj.entry[18].resource!! as Observation).related[0].target.reference))
        assertTrue(stringMatch("HLA-B*15:01:01G, exons 2 and ", (obj.entry[18].resource!! as Observation).related[0].target.display))
        assertTrue(stringMatch("derived-from", (obj.entry[18].resource!! as Observation).related[1].type))
        assertTrue(stringMatch("urn:uuid:792be53e-d4fb-4887-a", (obj.entry[18].resource!! as Observation).related[1].target.reference))
        assertTrue(stringMatch("HLA-B*57:01:01G, exons 2 and ", (obj.entry[18].resource!! as Observation).related[1].target.display))
        assertTrue(stringMatch("POST", obj.entry[18].request!!.method))
        assertTrue(stringMatch("Observation", obj.entry[18].request!!.url))
        assertTrue(stringMatch("urn:uuid:709c5315-9403-4867-9", obj.entry[19].fullUrl))
        assertTrue(stringMatch("Observation", (obj.entry[19].resource!! as Observation).resourceType))
        assertTrue(stringMatch("generated", (obj.entry[19].resource!! as Observation).text!!.status))
    }
}
