package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle78DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 449 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("Patient", (obj.entry[128].resource!! as Patient).resourceType))
        assertTrue(stringMatch("199", (obj.entry[128].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[128].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[128].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[128].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[128].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[128].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[128].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577518", (obj.entry[128].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[128].resource!! as Patient).active != null) (obj.entry[128].resource!! as Patient).active else false, "Field: (obj.entry[128].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[128].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Schneider", (obj.entry[128].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Tammy", (obj.entry[128].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[128].resource!! as Patient).gender))
        assertEquals("1950-04-22", (obj.entry[128].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[128].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[129].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[129].resource!! as Patient).resourceType))
        assertTrue(stringMatch("200", (obj.entry[129].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[129].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[129].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[129].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[129].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[129].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[129].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577519", (obj.entry[129].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[129].resource!! as Patient).active != null) (obj.entry[129].resource!! as Patient).active else false, "Field: (obj.entry[129].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[129].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Guerrero", (obj.entry[129].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Kimberly", (obj.entry[129].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[129].resource!! as Patient).gender))
        assertEquals("1958-08-22", (obj.entry[129].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[129].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[130].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[130].resource!! as Patient).resourceType))
        assertTrue(stringMatch("201", (obj.entry[130].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[130].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[130].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[130].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[130].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[130].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[130].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577520", (obj.entry[130].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[130].resource!! as Patient).active != null) (obj.entry[130].resource!! as Patient).active else false, "Field: (obj.entry[130].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[130].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Wright", (obj.entry[130].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Joy", (obj.entry[130].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[130].resource!! as Patient).gender))
        assertEquals("1951-06-06", (obj.entry[130].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[130].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[131].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[131].resource!! as Patient).resourceType))
        assertTrue(stringMatch("202", (obj.entry[131].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[131].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[131].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[131].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[131].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[131].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[131].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577521", (obj.entry[131].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[131].resource!! as Patient).active != null) (obj.entry[131].resource!! as Patient).active else false, "Field: (obj.entry[131].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[131].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Carpenter", (obj.entry[131].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Amy", (obj.entry[131].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[131].resource!! as Patient).gender))
        assertEquals("1940-07-07", (obj.entry[131].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[131].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[132].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[132].resource!! as Patient).resourceType))
        assertTrue(stringMatch("203", (obj.entry[132].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[132].resource!! as Patient).meta!!.lastUpdated.toString())
    }
}
