package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle86DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 457 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[161].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577551", (obj.entry[161].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[161].resource!! as Patient).active != null) (obj.entry[161].resource!! as Patient).active else false, "Field: (obj.entry[161].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[161].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("James", (obj.entry[161].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Brandon", (obj.entry[161].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[161].resource!! as Patient).gender))
        assertEquals("1961-04-14", (obj.entry[161].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[161].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[162].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[162].resource!! as Patient).resourceType))
        assertTrue(stringMatch("233", (obj.entry[162].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[162].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[162].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[162].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[162].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[162].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[162].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577552", (obj.entry[162].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[162].resource!! as Patient).active != null) (obj.entry[162].resource!! as Patient).active else false, "Field: (obj.entry[162].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[162].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Manning", (obj.entry[162].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Jimmy", (obj.entry[162].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[162].resource!! as Patient).gender))
        assertEquals("1975-06-07", (obj.entry[162].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[162].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[163].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[163].resource!! as Patient).resourceType))
        assertTrue(stringMatch("234", (obj.entry[163].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[163].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[163].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[163].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[163].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[163].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[163].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577553", (obj.entry[163].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[163].resource!! as Patient).active != null) (obj.entry[163].resource!! as Patient).active else false, "Field: (obj.entry[163].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[163].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Vaughn", (obj.entry[163].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Clyde", (obj.entry[163].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[163].resource!! as Patient).gender))
        assertEquals("1940-11-07", (obj.entry[163].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[163].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[164].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[164].resource!! as Patient).resourceType))
        assertTrue(stringMatch("235", (obj.entry[164].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[164].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[164].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[164].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[164].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[164].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[164].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577554", (obj.entry[164].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[164].resource!! as Patient).active != null) (obj.entry[164].resource!! as Patient).active else false, "Field: (obj.entry[164].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[164].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Bryan", (obj.entry[164].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Eugene", (obj.entry[164].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[164].resource!! as Patient).gender))
        assertEquals("1997-10-22", (obj.entry[164].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[164].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[165].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[165].resource!! as Patient).resourceType))
        assertTrue(stringMatch("236", (obj.entry[165].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[165].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[165].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[165].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[165].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[165].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[165].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577555", (obj.entry[165].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[165].resource!! as Patient).active != null) (obj.entry[165].resource!! as Patient).active else false, "Field: (obj.entry[165].resource!! as Patient).active")
    }
}
