package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle56DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 427 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[36].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[36].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[36].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[36].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[36].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[36].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577426", (obj.entry[36].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[36].resource!! as Patient).active != null) (obj.entry[36].resource!! as Patient).active else false, "Field: (obj.entry[36].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[36].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Nguyen", (obj.entry[36].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Glenda", (obj.entry[36].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[36].resource!! as Patient).gender))
        assertEquals("1945-02-16", (obj.entry[36].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[36].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[37].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[37].resource!! as Patient).resourceType))
        assertTrue(stringMatch("108", (obj.entry[37].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[37].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[37].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[37].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[37].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[37].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[37].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577427", (obj.entry[37].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[37].resource!! as Patient).active != null) (obj.entry[37].resource!! as Patient).active else false, "Field: (obj.entry[37].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[37].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Swanson", (obj.entry[37].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Nathaniel", (obj.entry[37].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[37].resource!! as Patient).gender))
        assertEquals("1940-01-08", (obj.entry[37].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[37].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[38].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[38].resource!! as Patient).resourceType))
        assertTrue(stringMatch("109", (obj.entry[38].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[38].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[38].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[38].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[38].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[38].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[38].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577428", (obj.entry[38].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[38].resource!! as Patient).active != null) (obj.entry[38].resource!! as Patient).active else false, "Field: (obj.entry[38].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[38].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Powers", (obj.entry[38].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Vera", (obj.entry[38].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[38].resource!! as Patient).gender))
        assertEquals("1945-06-12", (obj.entry[38].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[38].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[39].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[39].resource!! as Patient).resourceType))
        assertTrue(stringMatch("110", (obj.entry[39].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[39].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[39].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[39].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[39].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[39].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[39].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577429", (obj.entry[39].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[39].resource!! as Patient).active != null) (obj.entry[39].resource!! as Patient).active else false, "Field: (obj.entry[39].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[39].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Chandler", (obj.entry[39].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Perry", (obj.entry[39].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[39].resource!! as Patient).gender))
        assertEquals("1960-01-12", (obj.entry[39].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[39].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[40].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[40].resource!! as Patient).resourceType))
        assertTrue(stringMatch("111", (obj.entry[40].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[40].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[40].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[40].resource!! as Patient).text!!.div))
    }
}
