package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle20DataTest : DataTests() {
    @Test
    fun `diagnosticreport-hla-genetics-results-example 385 Test`() {
        val json = File("./src/test/resources/model/sample_data/diagnosticreport-hla-genetics-results-example.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("HLA00381", (obj.entry[8].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].code))
        assertTrue(stringMatch("HLA-B*57:01:01", (obj.entry[8].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.text))
        assertEquals(1001, (obj.entry[8].resource!! as Sequence).referenceSeq!!.windowStart)
        assertEquals(1277, (obj.entry[8].resource!! as Sequence).referenceSeq!!.windowEnd)
        assertTrue(stringMatch("GGTCTCACATCATCCAGGTGATGTATGGC", (obj.entry[8].resource!! as Sequence).observedSeq))
        assertTrue(stringMatch("POST", obj.entry[8].request!!.method))
        assertTrue(stringMatch("Sequence", obj.entry[8].request!!.url))
        assertTrue(stringMatch("urn:uuid:bb55c2bc-5ad2-4bc1-8", obj.entry[9].fullUrl))
        assertTrue(stringMatch("Sequence", (obj.entry[9].resource!! as Sequence).resourceType))
        assertTrue(stringMatch("generated", (obj.entry[9].resource!! as Sequence).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[9].resource!! as Sequence).text!!.div))
        assertTrue(stringMatch("dna", (obj.entry[9].resource!! as Sequence).type))
        assertEquals(0, (obj.entry[9].resource!! as Sequence).coordinateSystem)
        assertTrue(stringMatch("Patient/119", (obj.entry[9].resource!! as Sequence).patient!!.reference))
        assertTrue(stringMatch("Mary Chalmers", (obj.entry[9].resource!! as Sequence).patient!!.display))
        assertTrue(stringMatch("Specimen/120", (obj.entry[9].resource!! as Sequence).specimen!!.reference))
        assertTrue(stringMatch("buccal swab from Mary Chalmer", (obj.entry[9].resource!! as Sequence).specimen!!.display))
        assertTrue(stringMatch("http://www.ebi.ac.uk/ipd/imgt", (obj.entry[9].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].system))
        assertTrue(stringMatch("3.23", (obj.entry[9].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].version))
        assertTrue(stringMatch("HLA00401", (obj.entry[9].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].code))
        assertTrue(stringMatch("HLA-C*01:02:01", (obj.entry[9].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.text))
        assertEquals(486, (obj.entry[9].resource!! as Sequence).referenceSeq!!.windowStart)
        assertEquals(756, (obj.entry[9].resource!! as Sequence).referenceSeq!!.windowEnd)
        assertTrue(stringMatch("GCTCCCACTCCATGAAGTATTTCTTCACA", (obj.entry[9].resource!! as Sequence).observedSeq))
        assertTrue(stringMatch("POST", obj.entry[9].request!!.method))
        assertTrue(stringMatch("Sequence", obj.entry[9].request!!.url))
        assertTrue(stringMatch("urn:uuid:46938bb2-0486-4e87-b", obj.entry[10].fullUrl))
        assertTrue(stringMatch("Sequence", (obj.entry[10].resource!! as Sequence).resourceType))
        assertTrue(stringMatch("generated", (obj.entry[10].resource!! as Sequence).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[10].resource!! as Sequence).text!!.div))
        assertTrue(stringMatch("dna", (obj.entry[10].resource!! as Sequence).type))
        assertEquals(0, (obj.entry[10].resource!! as Sequence).coordinateSystem)
        assertTrue(stringMatch("Patient/119", (obj.entry[10].resource!! as Sequence).patient!!.reference))
        assertTrue(stringMatch("Mary Chalmers", (obj.entry[10].resource!! as Sequence).patient!!.display))
        assertTrue(stringMatch("Specimen/120", (obj.entry[10].resource!! as Sequence).specimen!!.reference))
        assertTrue(stringMatch("buccal swab from Mary Chalmer", (obj.entry[10].resource!! as Sequence).specimen!!.display))
        assertTrue(stringMatch("http://www.ebi.ac.uk/ipd/imgt", (obj.entry[10].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].system))
        assertTrue(stringMatch("3.23", (obj.entry[10].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].version))
        assertTrue(stringMatch("HLA00401", (obj.entry[10].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].code))
        assertTrue(stringMatch("HLA-C*01:02:01", (obj.entry[10].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.text))
        assertEquals(1002, (obj.entry[10].resource!! as Sequence).referenceSeq!!.windowStart)
        assertEquals(1278, (obj.entry[10].resource!! as Sequence).referenceSeq!!.windowEnd)
        assertTrue(stringMatch("GGTCTCACACCCTCCAGTGGATGTGTGGC", (obj.entry[10].resource!! as Sequence).observedSeq))
        assertTrue(stringMatch("POST", obj.entry[10].request!!.method))
        assertTrue(stringMatch("Sequence", obj.entry[10].request!!.url))
        assertTrue(stringMatch("urn:uuid:2ae2ff34-279e-43c2-9", obj.entry[11].fullUrl))
        assertTrue(stringMatch("Sequence", (obj.entry[11].resource!! as Sequence).resourceType))
        assertTrue(stringMatch("generated", (obj.entry[11].resource!! as Sequence).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[11].resource!! as Sequence).text!!.div))
        assertTrue(stringMatch("dna", (obj.entry[11].resource!! as Sequence).type))
        assertEquals(0, (obj.entry[11].resource!! as Sequence).coordinateSystem)
        assertTrue(stringMatch("Patient/119", (obj.entry[11].resource!! as Sequence).patient!!.reference))
        assertTrue(stringMatch("Mary Chalmers", (obj.entry[11].resource!! as Sequence).patient!!.display))
        assertTrue(stringMatch("Specimen/120", (obj.entry[11].resource!! as Sequence).specimen!!.reference))
        assertTrue(stringMatch("buccal swab from Mary Chalmer", (obj.entry[11].resource!! as Sequence).specimen!!.display))
        assertTrue(stringMatch("http://www.ebi.ac.uk/ipd/imgt", (obj.entry[11].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].system))
        assertTrue(stringMatch("3.23", (obj.entry[11].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].version))
        assertTrue(stringMatch("HLA00413", (obj.entry[11].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].code))
        assertTrue(stringMatch("HLA-C*03:04:01:01", (obj.entry[11].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.text))
        assertEquals(486, (obj.entry[11].resource!! as Sequence).referenceSeq!!.windowStart)
        assertEquals(756, (obj.entry[11].resource!! as Sequence).referenceSeq!!.windowEnd)
        assertTrue(stringMatch("GCTCCCACTCCATGAGGTATTTCTACACC", (obj.entry[11].resource!! as Sequence).observedSeq))
        assertTrue(stringMatch("POST", obj.entry[11].request!!.method))
        assertTrue(stringMatch("Sequence", obj.entry[11].request!!.url))
        assertTrue(stringMatch("urn:uuid:19153ef1-68c6-47a2-9", obj.entry[12].fullUrl))
        assertTrue(stringMatch("Sequence", (obj.entry[12].resource!! as Sequence).resourceType))
        assertTrue(stringMatch("generated", (obj.entry[12].resource!! as Sequence).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[12].resource!! as Sequence).text!!.div))
        assertTrue(stringMatch("dna", (obj.entry[12].resource!! as Sequence).type))
        assertEquals(0, (obj.entry[12].resource!! as Sequence).coordinateSystem)
        assertTrue(stringMatch("Patient/119", (obj.entry[12].resource!! as Sequence).patient!!.reference))
    }
}
