package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle75DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 446 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("577505", (obj.entry[115].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[115].resource!! as Patient).active != null) (obj.entry[115].resource!! as Patient).active else false, "Field: (obj.entry[115].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[115].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Cruz", (obj.entry[115].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Melissa", (obj.entry[115].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[115].resource!! as Patient).gender))
        assertEquals("1989-05-02", (obj.entry[115].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[115].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[116].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[116].resource!! as Patient).resourceType))
        assertTrue(stringMatch("187", (obj.entry[116].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[116].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[116].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[116].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[116].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[116].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[116].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577506", (obj.entry[116].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[116].resource!! as Patient).active != null) (obj.entry[116].resource!! as Patient).active else false, "Field: (obj.entry[116].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[116].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Hubbard", (obj.entry[116].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Maureen", (obj.entry[116].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[116].resource!! as Patient).gender))
        assertEquals("1972-03-12", (obj.entry[116].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[116].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[117].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[117].resource!! as Patient).resourceType))
        assertTrue(stringMatch("188", (obj.entry[117].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[117].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[117].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[117].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[117].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[117].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[117].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577507", (obj.entry[117].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[117].resource!! as Patient).active != null) (obj.entry[117].resource!! as Patient).active else false, "Field: (obj.entry[117].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[117].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Lawrence", (obj.entry[117].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Kim", (obj.entry[117].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[117].resource!! as Patient).gender))
        assertEquals("1972-12-02", (obj.entry[117].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[117].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[118].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[118].resource!! as Patient).resourceType))
        assertTrue(stringMatch("189", (obj.entry[118].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[118].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[118].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[118].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[118].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[118].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[118].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577508", (obj.entry[118].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[118].resource!! as Patient).active != null) (obj.entry[118].resource!! as Patient).active else false, "Field: (obj.entry[118].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[118].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Torres", (obj.entry[118].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Dwight", (obj.entry[118].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[118].resource!! as Patient).gender))
        assertEquals("1938-05-08", (obj.entry[118].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[118].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[119].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[119].resource!! as Patient).resourceType))
        assertTrue(stringMatch("190", (obj.entry[119].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[119].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[119].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[119].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[119].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[119].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[119].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577509", (obj.entry[119].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[119].resource!! as Patient).active != null) (obj.entry[119].resource!! as Patient).active else false, "Field: (obj.entry[119].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[119].resource!! as Patient).name[0].use))
    }
}
