package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle63DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 434 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("SS", (obj.entry[65].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[65].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577455", (obj.entry[65].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[65].resource!! as Patient).active != null) (obj.entry[65].resource!! as Patient).active else false, "Field: (obj.entry[65].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[65].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Reynolds", (obj.entry[65].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Julio", (obj.entry[65].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[65].resource!! as Patient).gender))
        assertEquals("1970-04-13", (obj.entry[65].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[65].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[66].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[66].resource!! as Patient).resourceType))
        assertTrue(stringMatch("137", (obj.entry[66].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[66].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[66].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[66].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[66].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[66].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[66].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577456", (obj.entry[66].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[66].resource!! as Patient).active != null) (obj.entry[66].resource!! as Patient).active else false, "Field: (obj.entry[66].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[66].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Roberson", (obj.entry[66].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Jonathan", (obj.entry[66].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[66].resource!! as Patient).gender))
        assertEquals("1945-10-01", (obj.entry[66].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[66].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[67].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[67].resource!! as Patient).resourceType))
        assertTrue(stringMatch("138", (obj.entry[67].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[67].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[67].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[67].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[67].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[67].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[67].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577457", (obj.entry[67].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[67].resource!! as Patient).active != null) (obj.entry[67].resource!! as Patient).active else false, "Field: (obj.entry[67].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[67].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Crawford", (obj.entry[67].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Carla", (obj.entry[67].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[67].resource!! as Patient).gender))
        assertEquals("1969-02-03", (obj.entry[67].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[67].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[68].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[68].resource!! as Patient).resourceType))
        assertTrue(stringMatch("139", (obj.entry[68].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[68].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[68].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[68].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[68].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[68].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[68].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577458", (obj.entry[68].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[68].resource!! as Patient).active != null) (obj.entry[68].resource!! as Patient).active else false, "Field: (obj.entry[68].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[68].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Hicks", (obj.entry[68].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Ronald", (obj.entry[68].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[68].resource!! as Patient).gender))
        assertEquals("1942-09-28", (obj.entry[68].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[68].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[69].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[69].resource!! as Patient).resourceType))
        assertTrue(stringMatch("140", (obj.entry[69].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[69].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[69].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[69].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[69].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[69].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[69].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577459", (obj.entry[69].resource!! as Patient).identifier[0].value))
    }
}
