package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle2DataTest : DataTests() {
    @Test
    fun `practitioner-examples-general 366 Test`() {
        val json = File("./src/test/resources/model/sample_data/practitioner-examples-general.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("phone", (obj.entry[1].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1002", (obj.entry[1].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[1].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[1].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1002 Healthcare Drive", (obj.entry[1].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("male", (obj.entry[1].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[2].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[2].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("14", (obj.entry[2].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[2].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[2].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[2].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[2].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[2].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[2].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("33344444", (obj.entry[2].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[2].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Assigned", (obj.entry[2].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Amanda", (obj.entry[2].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[2].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1021", (obj.entry[2].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[2].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[2].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1020 Healthcare Drive", (obj.entry[2].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("female", (obj.entry[2].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[3].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[3].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("15", (obj.entry[3].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[3].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[3].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[3].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[3].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[3].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[3].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("444444444", (obj.entry[3].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[3].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Hippocrates", (obj.entry[3].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Harold", (obj.entry[3].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[3].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1003", (obj.entry[3].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[3].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[3].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1003 Healthcare Drive", (obj.entry[3].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("male", (obj.entry[3].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[4].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[4].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("16", (obj.entry[4].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[4].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[4].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[4].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[4].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[4].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[4].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("555555555", (obj.entry[4].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[4].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Primary", (obj.entry[4].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Patricia", (obj.entry[4].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[4].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1004", (obj.entry[4].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[4].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[4].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1004 Healthcare Drive", (obj.entry[4].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("female", (obj.entry[4].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[5].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[5].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("17", (obj.entry[5].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[5].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[5].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[5].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[5].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[5].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
    }
}
