package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle57DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 428 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[40].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[40].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[40].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577430", (obj.entry[40].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[40].resource!! as Patient).active != null) (obj.entry[40].resource!! as Patient).active else false, "Field: (obj.entry[40].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[40].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Carroll", (obj.entry[40].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Alvin", (obj.entry[40].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[40].resource!! as Patient).gender))
        assertEquals("1945-06-04", (obj.entry[40].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[40].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[41].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[41].resource!! as Patient).resourceType))
        assertTrue(stringMatch("112", (obj.entry[41].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[41].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[41].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[41].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[41].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[41].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[41].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577431", (obj.entry[41].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[41].resource!! as Patient).active != null) (obj.entry[41].resource!! as Patient).active else false, "Field: (obj.entry[41].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[41].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Matthews", (obj.entry[41].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Florence", (obj.entry[41].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[41].resource!! as Patient).gender))
        assertEquals("1995-01-05", (obj.entry[41].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[41].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[42].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[42].resource!! as Patient).resourceType))
        assertTrue(stringMatch("113", (obj.entry[42].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[42].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[42].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[42].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[42].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[42].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[42].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577432", (obj.entry[42].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[42].resource!! as Patient).active != null) (obj.entry[42].resource!! as Patient).active else false, "Field: (obj.entry[42].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[42].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Frazier", (obj.entry[42].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Jordan", (obj.entry[42].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[42].resource!! as Patient).gender))
        assertEquals("1943-02-08", (obj.entry[42].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[42].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[43].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[43].resource!! as Patient).resourceType))
        assertTrue(stringMatch("114", (obj.entry[43].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[43].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[43].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[43].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[43].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[43].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[43].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577433", (obj.entry[43].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[43].resource!! as Patient).active != null) (obj.entry[43].resource!! as Patient).active else false, "Field: (obj.entry[43].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[43].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Patrick", (obj.entry[43].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Beth", (obj.entry[43].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[43].resource!! as Patient).gender))
        assertEquals("1990-08-10", (obj.entry[43].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[43].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[44].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[44].resource!! as Patient).resourceType))
        assertTrue(stringMatch("115", (obj.entry[44].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[44].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[44].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[44].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[44].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[44].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[44].resource!! as Patient).identifier[0].system))
    }
}
