package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle8DataTest : DataTests() {
    @Test
    fun `practitioner-examples-general 372 Test`() {
        val json = File("./src/test/resources/model/sample_data/practitioner-examples-general.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("36", (obj.entry[24].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[24].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[24].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[24].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[24].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[24].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[24].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222445555", (obj.entry[24].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[24].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Pasteur", (obj.entry[24].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Paula", (obj.entry[24].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[24].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1036", (obj.entry[24].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[24].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[24].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1034 Healthcare Drive", (obj.entry[24].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("female", (obj.entry[24].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[25].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[25].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("37", (obj.entry[25].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[25].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[25].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[25].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[25].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[25].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[25].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222446666", (obj.entry[25].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[25].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Osler", (obj.entry[25].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Otto", (obj.entry[25].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[25].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1037", (obj.entry[25].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[25].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[25].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1035 Healthcare Drive", (obj.entry[25].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("male", (obj.entry[25].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[26].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[26].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("38", (obj.entry[26].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[26].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[26].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[26].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[26].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[26].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[26].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222447777", (obj.entry[26].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[26].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Renal", (obj.entry[26].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Rory", (obj.entry[26].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[26].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1038", (obj.entry[26].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[26].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[26].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1036 Healthcare Drive", (obj.entry[26].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("male", (obj.entry[26].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[27].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[27].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("39", (obj.entry[27].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[27].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[27].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[27].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[27].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[27].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[27].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222448888", (obj.entry[27].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[27].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Brain", (obj.entry[27].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Barry", (obj.entry[27].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[27].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1039", (obj.entry[27].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[27].resource!! as Practitioner).telecom[0].use))
    }
}
