package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle196DataTest : DataTests() {
    @Test
    fun `diagnosticreport-examples-general 569 Test`() {
        val json = File("./src/test/resources/model/sample_data/diagnosticreport-examples-general.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("http://example.org/local", ((obj.entry[14].resource!! as DiagnosticReport).contained[8] as Observation).code.coding[0].system))
        assertTrue(stringMatch("TAZ", ((obj.entry[14].resource!! as DiagnosticReport).contained[8] as Observation).code.coding[0].code))
        assertTrue(stringMatch("CEFTAZIDIME", ((obj.entry[14].resource!! as DiagnosticReport).contained[8] as Observation).code.coding[0].display))
        assertTrue(stringMatch("Patient/5", ((obj.entry[14].resource!! as DiagnosticReport).contained[8] as Observation).subject!!.reference))
        assertTrue(stringMatch("Organization/1832473e-2fe0-45", ((obj.entry[14].resource!! as DiagnosticReport).contained[8] as Observation).performer[0].reference))
        assertTrue(stringMatch("Acme Laboratory, Inc", ((obj.entry[14].resource!! as DiagnosticReport).contained[8] as Observation).performer[0].display))
        assertTrue(stringMatch("%.2f".format(1f), "%.2f".format(((obj.entry[14].resource!! as DiagnosticReport).contained[8] as Observation).valueQuantity!!.value)))
        assertTrue(stringMatch("<=", ((obj.entry[14].resource!! as DiagnosticReport).contained[8] as Observation).valueQuantity!!.comparator))
        assertTrue(stringMatch("U", ((obj.entry[14].resource!! as DiagnosticReport).contained[8] as Observation).valueQuantity!!.unit))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0078", ((obj.entry[14].resource!! as DiagnosticReport).contained[8] as Observation).interpretation!!.coding[0].system))
        assertTrue(stringMatch("S", ((obj.entry[14].resource!! as DiagnosticReport).contained[8] as Observation).interpretation!!.coding[0].code))
        assertTrue(stringMatch("Observation", ((obj.entry[14].resource!! as DiagnosticReport).contained[9] as Observation).resourceType))
        assertTrue(stringMatch("o10", ((obj.entry[14].resource!! as DiagnosticReport).contained[9] as Observation).id))
        assertTrue(stringMatch("final", ((obj.entry[14].resource!! as DiagnosticReport).contained[9] as Observation).status))
        assertTrue(stringMatch("http://example.org/local", ((obj.entry[14].resource!! as DiagnosticReport).contained[9] as Observation).code.coding[0].system))
        assertTrue(stringMatch("CRO", ((obj.entry[14].resource!! as DiagnosticReport).contained[9] as Observation).code.coding[0].code))
        assertTrue(stringMatch("CEFTRIAXONE", ((obj.entry[14].resource!! as DiagnosticReport).contained[9] as Observation).code.coding[0].display))
        assertTrue(stringMatch("Patient/5", ((obj.entry[14].resource!! as DiagnosticReport).contained[9] as Observation).subject!!.reference))
        assertTrue(stringMatch("Organization/1832473e-2fe0-45", ((obj.entry[14].resource!! as DiagnosticReport).contained[9] as Observation).performer[0].reference))
        assertTrue(stringMatch("Acme Laboratory, Inc", ((obj.entry[14].resource!! as DiagnosticReport).contained[9] as Observation).performer[0].display))
        assertTrue(stringMatch("%.2f".format(1f), "%.2f".format(((obj.entry[14].resource!! as DiagnosticReport).contained[9] as Observation).valueQuantity!!.value)))
        assertTrue(stringMatch("<=", ((obj.entry[14].resource!! as DiagnosticReport).contained[9] as Observation).valueQuantity!!.comparator))
        assertTrue(stringMatch("U", ((obj.entry[14].resource!! as DiagnosticReport).contained[9] as Observation).valueQuantity!!.unit))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0078", ((obj.entry[14].resource!! as DiagnosticReport).contained[9] as Observation).interpretation!!.coding[0].system))
        assertTrue(stringMatch("S", ((obj.entry[14].resource!! as DiagnosticReport).contained[9] as Observation).interpretation!!.coding[0].code))
        assertTrue(stringMatch("Observation", ((obj.entry[14].resource!! as DiagnosticReport).contained[10] as Observation).resourceType))
        assertTrue(stringMatch("o11", ((obj.entry[14].resource!! as DiagnosticReport).contained[10] as Observation).id))
        assertTrue(stringMatch("final", ((obj.entry[14].resource!! as DiagnosticReport).contained[10] as Observation).status))
        assertTrue(stringMatch("http://example.org/local", ((obj.entry[14].resource!! as DiagnosticReport).contained[10] as Observation).code.coding[0].system))
        assertTrue(stringMatch("CIPRO", ((obj.entry[14].resource!! as DiagnosticReport).contained[10] as Observation).code.coding[0].code))
        assertTrue(stringMatch("CIPROFLOXACIN", ((obj.entry[14].resource!! as DiagnosticReport).contained[10] as Observation).code.coding[0].display))
        assertTrue(stringMatch("Patient/5", ((obj.entry[14].resource!! as DiagnosticReport).contained[10] as Observation).subject!!.reference))
        assertTrue(stringMatch("Organization/1832473e-2fe0-45", ((obj.entry[14].resource!! as DiagnosticReport).contained[10] as Observation).performer[0].reference))
        assertTrue(stringMatch("Acme Laboratory, Inc", ((obj.entry[14].resource!! as DiagnosticReport).contained[10] as Observation).performer[0].display))
        assertTrue(stringMatch("%.2f".format(0.25f), "%.2f".format(((obj.entry[14].resource!! as DiagnosticReport).contained[10] as Observation).valueQuantity!!.value)))
        assertTrue(stringMatch("<=", ((obj.entry[14].resource!! as DiagnosticReport).contained[10] as Observation).valueQuantity!!.comparator))
        assertTrue(stringMatch("U", ((obj.entry[14].resource!! as DiagnosticReport).contained[10] as Observation).valueQuantity!!.unit))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0078", ((obj.entry[14].resource!! as DiagnosticReport).contained[10] as Observation).interpretation!!.coding[0].system))
        assertTrue(stringMatch("S", ((obj.entry[14].resource!! as DiagnosticReport).contained[10] as Observation).interpretation!!.coding[0].code))
        assertTrue(stringMatch("Observation", ((obj.entry[14].resource!! as DiagnosticReport).contained[11] as Observation).resourceType))
        assertTrue(stringMatch("o12", ((obj.entry[14].resource!! as DiagnosticReport).contained[11] as Observation).id))
        assertTrue(stringMatch("final", ((obj.entry[14].resource!! as DiagnosticReport).contained[11] as Observation).status))
        assertTrue(stringMatch("http://example.org/local", ((obj.entry[14].resource!! as DiagnosticReport).contained[11] as Observation).code.coding[0].system))
        assertTrue(stringMatch("GM", ((obj.entry[14].resource!! as DiagnosticReport).contained[11] as Observation).code.coding[0].code))
        assertTrue(stringMatch("GENTAMICIN", ((obj.entry[14].resource!! as DiagnosticReport).contained[11] as Observation).code.coding[0].display))
        assertTrue(stringMatch("Patient/5", ((obj.entry[14].resource!! as DiagnosticReport).contained[11] as Observation).subject!!.reference))
        assertTrue(stringMatch("Organization/1832473e-2fe0-45", ((obj.entry[14].resource!! as DiagnosticReport).contained[11] as Observation).performer[0].reference))
        assertTrue(stringMatch("Acme Laboratory, Inc", ((obj.entry[14].resource!! as DiagnosticReport).contained[11] as Observation).performer[0].display))
        assertTrue(stringMatch("%.2f".format(1f), "%.2f".format(((obj.entry[14].resource!! as DiagnosticReport).contained[11] as Observation).valueQuantity!!.value)))
        assertTrue(stringMatch("<=", ((obj.entry[14].resource!! as DiagnosticReport).contained[11] as Observation).valueQuantity!!.comparator))
        assertTrue(stringMatch("U", ((obj.entry[14].resource!! as DiagnosticReport).contained[11] as Observation).valueQuantity!!.unit))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0078", ((obj.entry[14].resource!! as DiagnosticReport).contained[11] as Observation).interpretation!!.coding[0].system))
        assertTrue(stringMatch("S", ((obj.entry[14].resource!! as DiagnosticReport).contained[11] as Observation).interpretation!!.coding[0].code))
        assertTrue(stringMatch("Observation", ((obj.entry[14].resource!! as DiagnosticReport).contained[12] as Observation).resourceType))
        assertTrue(stringMatch("o13", ((obj.entry[14].resource!! as DiagnosticReport).contained[12] as Observation).id))
        assertTrue(stringMatch("final", ((obj.entry[14].resource!! as DiagnosticReport).contained[12] as Observation).status))
        assertTrue(stringMatch("http://example.org/local", ((obj.entry[14].resource!! as DiagnosticReport).contained[12] as Observation).code.coding[0].system))
        assertTrue(stringMatch("IPM", ((obj.entry[14].resource!! as DiagnosticReport).contained[12] as Observation).code.coding[0].code))
        assertTrue(stringMatch("IMIPENEM", ((obj.entry[14].resource!! as DiagnosticReport).contained[12] as Observation).code.coding[0].display))
        assertTrue(stringMatch("Patient/5", ((obj.entry[14].resource!! as DiagnosticReport).contained[12] as Observation).subject!!.reference))
        assertTrue(stringMatch("Organization/1832473e-2fe0-45", ((obj.entry[14].resource!! as DiagnosticReport).contained[12] as Observation).performer[0].reference))
        assertTrue(stringMatch("Acme Laboratory, Inc", ((obj.entry[14].resource!! as DiagnosticReport).contained[12] as Observation).performer[0].display))
        assertTrue(stringMatch("%.2f".format(1f), "%.2f".format(((obj.entry[14].resource!! as DiagnosticReport).contained[12] as Observation).valueQuantity!!.value)))
        assertTrue(stringMatch("<=", ((obj.entry[14].resource!! as DiagnosticReport).contained[12] as Observation).valueQuantity!!.comparator))
        assertTrue(stringMatch("U", ((obj.entry[14].resource!! as DiagnosticReport).contained[12] as Observation).valueQuantity!!.unit))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0078", ((obj.entry[14].resource!! as DiagnosticReport).contained[12] as Observation).interpretation!!.coding[0].system))
        assertTrue(stringMatch("S", ((obj.entry[14].resource!! as DiagnosticReport).contained[12] as Observation).interpretation!!.coding[0].code))
        assertTrue(stringMatch("Observation", ((obj.entry[14].resource!! as DiagnosticReport).contained[13] as Observation).resourceType))
        assertTrue(stringMatch("o14", ((obj.entry[14].resource!! as DiagnosticReport).contained[13] as Observation).id))
        assertTrue(stringMatch("final", ((obj.entry[14].resource!! as DiagnosticReport).contained[13] as Observation).status))
        assertTrue(stringMatch("http://example.org/local", ((obj.entry[14].resource!! as DiagnosticReport).contained[13] as Observation).code.coding[0].system))
    }
}
