package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle96DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 467 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("generated", (obj.entry[203].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[203].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[203].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[203].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[203].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577593", (obj.entry[203].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[203].resource!! as Patient).active != null) (obj.entry[203].resource!! as Patient).active else false, "Field: (obj.entry[203].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[203].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Griffith", (obj.entry[203].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Darrell", (obj.entry[203].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[203].resource!! as Patient).gender))
        assertEquals("1995-07-07", (obj.entry[203].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[203].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[204].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[204].resource!! as Patient).resourceType))
        assertTrue(stringMatch("275", (obj.entry[204].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[204].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[204].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[204].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[204].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[204].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[204].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577594", (obj.entry[204].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[204].resource!! as Patient).active != null) (obj.entry[204].resource!! as Patient).active else false, "Field: (obj.entry[204].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[204].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Payne", (obj.entry[204].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Jackie", (obj.entry[204].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[204].resource!! as Patient).gender))
        assertEquals("1994-06-16", (obj.entry[204].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[204].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[205].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[205].resource!! as Patient).resourceType))
        assertTrue(stringMatch("276", (obj.entry[205].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[205].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[205].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[205].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[205].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[205].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[205].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577595", (obj.entry[205].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[205].resource!! as Patient).active != null) (obj.entry[205].resource!! as Patient).active else false, "Field: (obj.entry[205].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[205].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Morrison", (obj.entry[205].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Jo", (obj.entry[205].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[205].resource!! as Patient).gender))
        assertEquals("1953-02-01", (obj.entry[205].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[205].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[206].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[206].resource!! as Patient).resourceType))
        assertTrue(stringMatch("277", (obj.entry[206].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[206].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[206].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[206].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[206].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[206].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[206].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577596", (obj.entry[206].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[206].resource!! as Patient).active != null) (obj.entry[206].resource!! as Patient).active else false, "Field: (obj.entry[206].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[206].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Parker", (obj.entry[206].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Francisco", (obj.entry[206].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[206].resource!! as Patient).gender))
        assertEquals("1973-12-04", (obj.entry[206].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[206].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[207].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[207].resource!! as Patient).resourceType))
        assertTrue(stringMatch("278", (obj.entry[207].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[207].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[207].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[207].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[207].resource!! as Patient).identifier[0].type!!.coding[0].system))
    }
}
