package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle53DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 424 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("official", (obj.entry[23].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Holt", (obj.entry[23].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Willard", (obj.entry[23].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[23].resource!! as Patient).gender))
        assertEquals("1933-08-07", (obj.entry[23].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[23].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/9", obj.entry[24].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[24].resource!! as Patient).resourceType))
        assertTrue(stringMatch("95", (obj.entry[24].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[24].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[24].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[24].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[24].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[24].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[24].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577414", (obj.entry[24].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[24].resource!! as Patient).active != null) (obj.entry[24].resource!! as Patient).active else false, "Field: (obj.entry[24].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[24].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("May", (obj.entry[24].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Christian", (obj.entry[24].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[24].resource!! as Patient).gender))
        assertEquals("1960-05-08", (obj.entry[24].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[24].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/9", obj.entry[25].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[25].resource!! as Patient).resourceType))
        assertTrue(stringMatch("96", (obj.entry[25].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[25].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[25].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[25].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[25].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[25].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[25].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577415", (obj.entry[25].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[25].resource!! as Patient).active != null) (obj.entry[25].resource!! as Patient).active else false, "Field: (obj.entry[25].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[25].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Hawkins", (obj.entry[25].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Bryan", (obj.entry[25].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[25].resource!! as Patient).gender))
        assertEquals("1970-07-09", (obj.entry[25].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[25].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/9", obj.entry[26].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[26].resource!! as Patient).resourceType))
        assertTrue(stringMatch("97", (obj.entry[26].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[26].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[26].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[26].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[26].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[26].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[26].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577416", (obj.entry[26].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[26].resource!! as Patient).active != null) (obj.entry[26].resource!! as Patient).active else false, "Field: (obj.entry[26].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[26].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("George", (obj.entry[26].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Jay", (obj.entry[26].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[26].resource!! as Patient).gender))
        assertEquals("1954-10-08", (obj.entry[26].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[26].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/9", obj.entry[27].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[27].resource!! as Patient).resourceType))
        assertTrue(stringMatch("98", (obj.entry[27].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[27].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[27].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[27].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[27].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[27].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[27].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577417", (obj.entry[27].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[27].resource!! as Patient).active != null) (obj.entry[27].resource!! as Patient).active else false, "Field: (obj.entry[27].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[27].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Jordan", (obj.entry[27].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Roberto", (obj.entry[27].resource!! as Patient).name[0].given[0]))
    }
}
