package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle97DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 468 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("SS", (obj.entry[207].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[207].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577597", (obj.entry[207].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[207].resource!! as Patient).active != null) (obj.entry[207].resource!! as Patient).active else false, "Field: (obj.entry[207].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[207].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Bennett", (obj.entry[207].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Marion", (obj.entry[207].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[207].resource!! as Patient).gender))
        assertEquals("1958-03-03", (obj.entry[207].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[207].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[208].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[208].resource!! as Patient).resourceType))
        assertTrue(stringMatch("279", (obj.entry[208].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[208].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[208].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[208].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[208].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[208].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[208].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577598", (obj.entry[208].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[208].resource!! as Patient).active != null) (obj.entry[208].resource!! as Patient).active else false, "Field: (obj.entry[208].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[208].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Hammond", (obj.entry[208].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Albert", (obj.entry[208].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[208].resource!! as Patient).gender))
        assertEquals("1962-05-28", (obj.entry[208].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[208].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[209].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[209].resource!! as Patient).resourceType))
        assertTrue(stringMatch("280", (obj.entry[209].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[209].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[209].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[209].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[209].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[209].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[209].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577599", (obj.entry[209].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[209].resource!! as Patient).active != null) (obj.entry[209].resource!! as Patient).active else false, "Field: (obj.entry[209].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[209].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Hunt", (obj.entry[209].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Brittany", (obj.entry[209].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[209].resource!! as Patient).gender))
        assertEquals("1962-04-23", (obj.entry[209].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[209].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[210].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[210].resource!! as Patient).resourceType))
        assertTrue(stringMatch("281", (obj.entry[210].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[210].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[210].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[210].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[210].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[210].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[210].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577600", (obj.entry[210].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[210].resource!! as Patient).active != null) (obj.entry[210].resource!! as Patient).active else false, "Field: (obj.entry[210].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[210].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Gray", (obj.entry[210].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Agnes", (obj.entry[210].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[210].resource!! as Patient).gender))
        assertEquals("1992-08-02", (obj.entry[210].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[210].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[211].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[211].resource!! as Patient).resourceType))
        assertTrue(stringMatch("282", (obj.entry[211].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[211].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[211].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[211].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[211].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[211].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[211].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577601", (obj.entry[211].resource!! as Patient).identifier[0].value))
    }
}
