package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle66DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 437 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("Organization/1", (obj.entry[77].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[78].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[78].resource!! as Patient).resourceType))
        assertTrue(stringMatch("149", (obj.entry[78].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[78].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[78].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[78].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[78].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[78].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[78].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577468", (obj.entry[78].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[78].resource!! as Patient).active != null) (obj.entry[78].resource!! as Patient).active else false, "Field: (obj.entry[78].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[78].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Glover", (obj.entry[78].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Henry", (obj.entry[78].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[78].resource!! as Patient).gender))
        assertEquals("1971-06-30", (obj.entry[78].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[78].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[79].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[79].resource!! as Patient).resourceType))
        assertTrue(stringMatch("150", (obj.entry[79].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[79].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[79].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[79].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[79].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[79].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[79].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577469", (obj.entry[79].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[79].resource!! as Patient).active != null) (obj.entry[79].resource!! as Patient).active else false, "Field: (obj.entry[79].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[79].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Austin", (obj.entry[79].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Brenda", (obj.entry[79].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[79].resource!! as Patient).gender))
        assertEquals("1972-09-28", (obj.entry[79].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[79].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[80].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[80].resource!! as Patient).resourceType))
        assertTrue(stringMatch("151", (obj.entry[80].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[80].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[80].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[80].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[80].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[80].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[80].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577470", (obj.entry[80].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[80].resource!! as Patient).active != null) (obj.entry[80].resource!! as Patient).active else false, "Field: (obj.entry[80].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[80].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Phelps", (obj.entry[80].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Tara", (obj.entry[80].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[80].resource!! as Patient).gender))
        assertEquals("1952-03-14", (obj.entry[80].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[80].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[81].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[81].resource!! as Patient).resourceType))
        assertTrue(stringMatch("152", (obj.entry[81].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[81].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[81].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[81].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[81].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[81].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[81].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577471", (obj.entry[81].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[81].resource!! as Patient).active != null) (obj.entry[81].resource!! as Patient).active else false, "Field: (obj.entry[81].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[81].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Floyd", (obj.entry[81].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Phillip", (obj.entry[81].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[81].resource!! as Patient).gender))
        assertEquals("1963-06-17", (obj.entry[81].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[81].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[82].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[82].resource!! as Patient).resourceType))
    }
}
