package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle73DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 444 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[107].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[107].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[107].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[107].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[107].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[107].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577497", (obj.entry[107].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[107].resource!! as Patient).active != null) (obj.entry[107].resource!! as Patient).active else false, "Field: (obj.entry[107].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[107].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Stewart", (obj.entry[107].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Michelle", (obj.entry[107].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[107].resource!! as Patient).gender))
        assertEquals("1973-05-23", (obj.entry[107].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[107].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[108].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[108].resource!! as Patient).resourceType))
        assertTrue(stringMatch("179", (obj.entry[108].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[108].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[108].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[108].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[108].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[108].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[108].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577498", (obj.entry[108].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[108].resource!! as Patient).active != null) (obj.entry[108].resource!! as Patient).active else false, "Field: (obj.entry[108].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[108].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Gilbert", (obj.entry[108].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Rachel", (obj.entry[108].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[108].resource!! as Patient).gender))
        assertEquals("1947-09-03", (obj.entry[108].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[108].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[109].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[109].resource!! as Patient).resourceType))
        assertTrue(stringMatch("180", (obj.entry[109].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[109].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[109].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[109].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[109].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[109].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[109].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577499", (obj.entry[109].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[109].resource!! as Patient).active != null) (obj.entry[109].resource!! as Patient).active else false, "Field: (obj.entry[109].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[109].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Schwartz", (obj.entry[109].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Valerie", (obj.entry[109].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[109].resource!! as Patient).gender))
        assertEquals("1965-06-15", (obj.entry[109].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[109].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[110].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[110].resource!! as Patient).resourceType))
        assertTrue(stringMatch("181", (obj.entry[110].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[110].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[110].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[110].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[110].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[110].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[110].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577500", (obj.entry[110].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[110].resource!! as Patient).active != null) (obj.entry[110].resource!! as Patient).active else false, "Field: (obj.entry[110].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[110].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Doyle", (obj.entry[110].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Darlene", (obj.entry[110].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[110].resource!! as Patient).gender))
        assertEquals("1939-07-14", (obj.entry[110].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[110].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[111].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[111].resource!! as Patient).resourceType))
        assertTrue(stringMatch("182", (obj.entry[111].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[111].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[111].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[111].resource!! as Patient).text!!.div))
    }
}
