package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle59DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 430 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("Strickland", (obj.entry[48].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Veronica", (obj.entry[48].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[48].resource!! as Patient).gender))
        assertEquals("1963-02-08", (obj.entry[48].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[48].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[49].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[49].resource!! as Patient).resourceType))
        assertTrue(stringMatch("120", (obj.entry[49].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[49].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[49].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[49].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[49].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[49].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[49].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577439", (obj.entry[49].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[49].resource!! as Patient).active != null) (obj.entry[49].resource!! as Patient).active else false, "Field: (obj.entry[49].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[49].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Mckinney", (obj.entry[49].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Valerie", (obj.entry[49].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[49].resource!! as Patient).gender))
        assertEquals("1960-06-08", (obj.entry[49].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[49].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[50].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[50].resource!! as Patient).resourceType))
        assertTrue(stringMatch("121", (obj.entry[50].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[50].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[50].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[50].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[50].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[50].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[50].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577440", (obj.entry[50].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[50].resource!! as Patient).active != null) (obj.entry[50].resource!! as Patient).active else false, "Field: (obj.entry[50].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[50].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Ortiz", (obj.entry[50].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Lucille", (obj.entry[50].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[50].resource!! as Patient).gender))
        assertEquals("1930-04-02", (obj.entry[50].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[50].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[51].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[51].resource!! as Patient).resourceType))
        assertTrue(stringMatch("122", (obj.entry[51].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[51].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[51].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[51].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[51].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[51].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[51].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577441", (obj.entry[51].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[51].resource!! as Patient).active != null) (obj.entry[51].resource!! as Patient).active else false, "Field: (obj.entry[51].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[51].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Alvarez", (obj.entry[51].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Mitchell", (obj.entry[51].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[51].resource!! as Patient).gender))
        assertEquals("1980-04-08", (obj.entry[51].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[51].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[52].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[52].resource!! as Patient).resourceType))
        assertTrue(stringMatch("123", (obj.entry[52].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[52].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[52].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[52].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[52].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[52].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[52].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577442", (obj.entry[52].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[52].resource!! as Patient).active != null) (obj.entry[52].resource!! as Patient).active else false, "Field: (obj.entry[52].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[52].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Dennis", (obj.entry[52].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Charles", (obj.entry[52].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[52].resource!! as Patient).gender))
    }
}
