package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle19DataTest : DataTests() {
    @Test
    fun `diagnosticreport-hla-genetics-results-example 384 Test`() {
        val json = File("./src/test/resources/model/sample_data/diagnosticreport-hla-genetics-results-example.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("POST", obj.entry[4].request!!.method))
        assertTrue(stringMatch("Sequence", obj.entry[4].request!!.url))
        assertTrue(stringMatch("urn:uuid:cbabf93e-1b4b-46f2-b", obj.entry[5].fullUrl))
        assertTrue(stringMatch("Sequence", (obj.entry[5].resource!! as Sequence).resourceType))
        assertTrue(stringMatch("generated", (obj.entry[5].resource!! as Sequence).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[5].resource!! as Sequence).text!!.div))
        assertTrue(stringMatch("dna", (obj.entry[5].resource!! as Sequence).type))
        assertEquals(0, (obj.entry[5].resource!! as Sequence).coordinateSystem)
        assertTrue(stringMatch("Patient/119", (obj.entry[5].resource!! as Sequence).patient!!.reference))
        assertTrue(stringMatch("Mary Chalmers", (obj.entry[5].resource!! as Sequence).patient!!.display))
        assertTrue(stringMatch("Specimen/120", (obj.entry[5].resource!! as Sequence).specimen!!.reference))
        assertTrue(stringMatch("buccal swab from Mary Chalmer", (obj.entry[5].resource!! as Sequence).specimen!!.display))
        assertTrue(stringMatch("http://www.ebi.ac.uk/ipd/imgt", (obj.entry[5].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].system))
        assertTrue(stringMatch("3.23", (obj.entry[5].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].version))
        assertTrue(stringMatch("HLA00162", (obj.entry[5].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].code))
        assertTrue(stringMatch("HLA-B*15:01:01:01", (obj.entry[5].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.text))
        assertEquals(486, (obj.entry[5].resource!! as Sequence).referenceSeq!!.windowStart)
        assertEquals(756, (obj.entry[5].resource!! as Sequence).referenceSeq!!.windowEnd)
        assertTrue(stringMatch("GCTCCCACTCCATGAGGTATTTCTACACC", (obj.entry[5].resource!! as Sequence).observedSeq))
        assertTrue(stringMatch("POST", obj.entry[5].request!!.method))
        assertTrue(stringMatch("Sequence", obj.entry[5].request!!.url))
        assertTrue(stringMatch("urn:uuid:c233ad3d-1572-48d6-9", obj.entry[6].fullUrl))
        assertTrue(stringMatch("Sequence", (obj.entry[6].resource!! as Sequence).resourceType))
        assertTrue(stringMatch("generated", (obj.entry[6].resource!! as Sequence).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[6].resource!! as Sequence).text!!.div))
        assertTrue(stringMatch("dna", (obj.entry[6].resource!! as Sequence).type))
        assertEquals(0, (obj.entry[6].resource!! as Sequence).coordinateSystem)
        assertTrue(stringMatch("Patient/119", (obj.entry[6].resource!! as Sequence).patient!!.reference))
        assertTrue(stringMatch("Mary Chalmers", (obj.entry[6].resource!! as Sequence).patient!!.display))
        assertTrue(stringMatch("Specimen/120", (obj.entry[6].resource!! as Sequence).specimen!!.reference))
        assertTrue(stringMatch("buccal swab from Mary Chalmer", (obj.entry[6].resource!! as Sequence).specimen!!.display))
        assertTrue(stringMatch("http://www.ebi.ac.uk/ipd/imgt", (obj.entry[6].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].system))
        assertTrue(stringMatch("3.23", (obj.entry[6].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].version))
        assertTrue(stringMatch("HLA00162", (obj.entry[6].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].code))
        assertTrue(stringMatch("HLA-B*15:01:01:01", (obj.entry[6].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.text))
        assertEquals(1001, (obj.entry[6].resource!! as Sequence).referenceSeq!!.windowStart)
        assertEquals(1277, (obj.entry[6].resource!! as Sequence).referenceSeq!!.windowEnd)
        assertTrue(stringMatch("GGTCTCACACCCTCCAGAGGATGTACGGC", (obj.entry[6].resource!! as Sequence).observedSeq))
        assertTrue(stringMatch("POST", obj.entry[6].request!!.method))
        assertTrue(stringMatch("Sequence", obj.entry[6].request!!.url))
        assertTrue(stringMatch("urn:uuid:05fa52d7-5c67-460a-8", obj.entry[7].fullUrl))
        assertTrue(stringMatch("Sequence", (obj.entry[7].resource!! as Sequence).resourceType))
        assertTrue(stringMatch("generated", (obj.entry[7].resource!! as Sequence).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[7].resource!! as Sequence).text!!.div))
        assertTrue(stringMatch("dna", (obj.entry[7].resource!! as Sequence).type))
        assertEquals(0, (obj.entry[7].resource!! as Sequence).coordinateSystem)
        assertTrue(stringMatch("Patient/119", (obj.entry[7].resource!! as Sequence).patient!!.reference))
        assertTrue(stringMatch("Mary Chalmers", (obj.entry[7].resource!! as Sequence).patient!!.display))
        assertTrue(stringMatch("Specimen/120", (obj.entry[7].resource!! as Sequence).specimen!!.reference))
        assertTrue(stringMatch("buccal swab from Mary Chalmer", (obj.entry[7].resource!! as Sequence).specimen!!.display))
        assertTrue(stringMatch("http://www.ebi.ac.uk/ipd/imgt", (obj.entry[7].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].system))
        assertTrue(stringMatch("3.23", (obj.entry[7].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].version))
        assertTrue(stringMatch("HLA00381", (obj.entry[7].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].code))
        assertTrue(stringMatch("HLA-B*57:01:01", (obj.entry[7].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.text))
        assertEquals(485, (obj.entry[7].resource!! as Sequence).referenceSeq!!.windowStart)
        assertEquals(755, (obj.entry[7].resource!! as Sequence).referenceSeq!!.windowEnd)
        assertTrue(stringMatch("GCTCCCACTCCATGAGGTATTTCTACACC", (obj.entry[7].resource!! as Sequence).observedSeq))
        assertTrue(stringMatch("POST", obj.entry[7].request!!.method))
        assertTrue(stringMatch("Sequence", obj.entry[7].request!!.url))
        assertTrue(stringMatch("urn:uuid:db69e549-6267-4777-b", obj.entry[8].fullUrl))
        assertTrue(stringMatch("Sequence", (obj.entry[8].resource!! as Sequence).resourceType))
        assertTrue(stringMatch("generated", (obj.entry[8].resource!! as Sequence).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[8].resource!! as Sequence).text!!.div))
        assertTrue(stringMatch("dna", (obj.entry[8].resource!! as Sequence).type))
        assertEquals(0, (obj.entry[8].resource!! as Sequence).coordinateSystem)
        assertTrue(stringMatch("Patient/119", (obj.entry[8].resource!! as Sequence).patient!!.reference))
        assertTrue(stringMatch("Mary Chalmers", (obj.entry[8].resource!! as Sequence).patient!!.display))
        assertTrue(stringMatch("Specimen/120", (obj.entry[8].resource!! as Sequence).specimen!!.reference))
        assertTrue(stringMatch("buccal swab from Mary Chalmer", (obj.entry[8].resource!! as Sequence).specimen!!.display))
        assertTrue(stringMatch("http://www.ebi.ac.uk/ipd/imgt", (obj.entry[8].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].system))
        assertTrue(stringMatch("3.23", (obj.entry[8].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].version))
    }
}
