package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle51DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 422 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[15].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[15].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[15].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[15].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577405", (obj.entry[15].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[15].resource!! as Patient).active != null) (obj.entry[15].resource!! as Patient).active else false, "Field: (obj.entry[15].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[15].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Perry", (obj.entry[15].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Eric", (obj.entry[15].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[15].resource!! as Patient).gender))
        assertEquals("1955-05-30", (obj.entry[15].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[15].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/8", obj.entry[16].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[16].resource!! as Patient).resourceType))
        assertTrue(stringMatch("87", (obj.entry[16].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[16].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[16].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[16].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[16].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[16].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[16].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577406", (obj.entry[16].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[16].resource!! as Patient).active != null) (obj.entry[16].resource!! as Patient).active else false, "Field: (obj.entry[16].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[16].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("May", (obj.entry[16].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Laurie", (obj.entry[16].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[16].resource!! as Patient).gender))
        assertEquals("1944-05-08", (obj.entry[16].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[16].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/8", obj.entry[17].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[17].resource!! as Patient).resourceType))
        assertTrue(stringMatch("88", (obj.entry[17].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[17].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[17].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[17].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[17].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[17].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[17].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577407", (obj.entry[17].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[17].resource!! as Patient).active != null) (obj.entry[17].resource!! as Patient).active else false, "Field: (obj.entry[17].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[17].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Becker", (obj.entry[17].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Tara", (obj.entry[17].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[17].resource!! as Patient).gender))
        assertEquals("1940-08-05", (obj.entry[17].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[17].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/8", obj.entry[18].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[18].resource!! as Patient).resourceType))
        assertTrue(stringMatch("89", (obj.entry[18].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[18].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[18].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[18].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[18].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[18].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[18].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577408", (obj.entry[18].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[18].resource!! as Patient).active != null) (obj.entry[18].resource!! as Patient).active else false, "Field: (obj.entry[18].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[18].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Rodgers", (obj.entry[18].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Clara", (obj.entry[18].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[18].resource!! as Patient).gender))
        assertEquals("1981-06-08", (obj.entry[18].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[18].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/9", obj.entry[19].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[19].resource!! as Patient).resourceType))
        assertTrue(stringMatch("90", (obj.entry[19].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[19].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[19].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[19].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[19].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[19].resource!! as Patient).identifier[0].type!!.coding[0].code))
    }
}
