package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle76DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 447 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("Malone", (obj.entry[119].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Ian", (obj.entry[119].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[119].resource!! as Patient).gender))
        assertEquals("1942-04-12", (obj.entry[119].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[119].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[120].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[120].resource!! as Patient).resourceType))
        assertTrue(stringMatch("191", (obj.entry[120].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[120].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[120].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[120].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[120].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[120].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[120].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577510", (obj.entry[120].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[120].resource!! as Patient).active != null) (obj.entry[120].resource!! as Patient).active else false, "Field: (obj.entry[120].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[120].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Boone", (obj.entry[120].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Albert", (obj.entry[120].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[120].resource!! as Patient).gender))
        assertEquals("1942-08-29", (obj.entry[120].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[120].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[121].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[121].resource!! as Patient).resourceType))
        assertTrue(stringMatch("192", (obj.entry[121].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[121].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[121].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[121].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[121].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[121].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[121].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577511", (obj.entry[121].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[121].resource!! as Patient).active != null) (obj.entry[121].resource!! as Patient).active else false, "Field: (obj.entry[121].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[121].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Valdez", (obj.entry[121].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Tracy", (obj.entry[121].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[121].resource!! as Patient).gender))
        assertEquals("1943-02-13", (obj.entry[121].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[121].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[122].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[122].resource!! as Patient).resourceType))
        assertTrue(stringMatch("193", (obj.entry[122].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[122].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[122].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[122].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[122].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[122].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[122].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577512", (obj.entry[122].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[122].resource!! as Patient).active != null) (obj.entry[122].resource!! as Patient).active else false, "Field: (obj.entry[122].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[122].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Drake", (obj.entry[122].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Francis", (obj.entry[122].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[122].resource!! as Patient).gender))
        assertEquals("1943-03-22", (obj.entry[122].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[122].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[123].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[123].resource!! as Patient).resourceType))
        assertTrue(stringMatch("194", (obj.entry[123].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[123].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[123].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[123].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[123].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[123].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[123].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577513", (obj.entry[123].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[123].resource!! as Patient).active != null) (obj.entry[123].resource!! as Patient).active else false, "Field: (obj.entry[123].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[123].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Perkins", (obj.entry[123].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Clifton", (obj.entry[123].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[123].resource!! as Patient).gender))
    }
}
