package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle88DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 459 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("female", (obj.entry[169].resource!! as Patient).gender))
        assertEquals("1996-05-06", (obj.entry[169].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[169].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[170].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[170].resource!! as Patient).resourceType))
        assertTrue(stringMatch("241", (obj.entry[170].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[170].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[170].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[170].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[170].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[170].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[170].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577560", (obj.entry[170].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[170].resource!! as Patient).active != null) (obj.entry[170].resource!! as Patient).active else false, "Field: (obj.entry[170].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[170].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Gonzalez", (obj.entry[170].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Jose", (obj.entry[170].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[170].resource!! as Patient).gender))
        assertEquals("1962-11-05", (obj.entry[170].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[170].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[171].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[171].resource!! as Patient).resourceType))
        assertTrue(stringMatch("242", (obj.entry[171].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[171].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[171].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[171].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[171].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[171].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[171].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577561", (obj.entry[171].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[171].resource!! as Patient).active != null) (obj.entry[171].resource!! as Patient).active else false, "Field: (obj.entry[171].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[171].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Hamilton", (obj.entry[171].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Wendy", (obj.entry[171].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[171].resource!! as Patient).gender))
        assertEquals("1980-07-13", (obj.entry[171].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[171].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[172].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[172].resource!! as Patient).resourceType))
        assertTrue(stringMatch("243", (obj.entry[172].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[172].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[172].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[172].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[172].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[172].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[172].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577562", (obj.entry[172].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[172].resource!! as Patient).active != null) (obj.entry[172].resource!! as Patient).active else false, "Field: (obj.entry[172].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[172].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Sanders", (obj.entry[172].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Dwight", (obj.entry[172].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[172].resource!! as Patient).gender))
        assertEquals("1945-10-25", (obj.entry[172].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[172].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[173].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[173].resource!! as Patient).resourceType))
        assertTrue(stringMatch("244", (obj.entry[173].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[173].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[173].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[173].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[173].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[173].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[173].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577563", (obj.entry[173].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[173].resource!! as Patient).active != null) (obj.entry[173].resource!! as Patient).active else false, "Field: (obj.entry[173].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[173].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Blair", (obj.entry[173].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Diane", (obj.entry[173].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[173].resource!! as Patient).gender))
        assertEquals("1950-06-15", (obj.entry[173].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[173].resource!! as Patient).managingOrganization!!.reference))
    }
}
