package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle18DataTest : DataTests() {
    @Test
    fun `diagnosticreport-hla-genetics-results-example 383 Test`() {
        val json = File("./src/test/resources/model/sample_data/diagnosticreport-hla-genetics-results-example.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[1].resource!! as Sequence).text!!.div))
        assertTrue(stringMatch("dna", (obj.entry[1].resource!! as Sequence).type))
        assertEquals(0, (obj.entry[1].resource!! as Sequence).coordinateSystem)
        assertTrue(stringMatch("Patient/119", (obj.entry[1].resource!! as Sequence).patient!!.reference))
        assertTrue(stringMatch("Mary Chalmers", (obj.entry[1].resource!! as Sequence).patient!!.display))
        assertTrue(stringMatch("Specimen/120", (obj.entry[1].resource!! as Sequence).specimen!!.reference))
        assertTrue(stringMatch("buccal swab from Mary Chalmer", (obj.entry[1].resource!! as Sequence).specimen!!.display))
        assertTrue(stringMatch("http://www.ebi.ac.uk/ipd/imgt", (obj.entry[1].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].system))
        assertTrue(stringMatch("3.23", (obj.entry[1].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].version))
        assertTrue(stringMatch("HLA00001", (obj.entry[1].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].code))
        assertTrue(stringMatch("HLA-A*01:01:01:01", (obj.entry[1].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.text))
        assertEquals(503, (obj.entry[1].resource!! as Sequence).referenceSeq!!.windowStart)
        assertEquals(773, (obj.entry[1].resource!! as Sequence).referenceSeq!!.windowEnd)
        assertTrue(stringMatch("GCTCCCACTCCATGAGGTATTTCTTCACA", (obj.entry[1].resource!! as Sequence).observedSeq))
        assertTrue(stringMatch("POST", obj.entry[1].request!!.method))
        assertTrue(stringMatch("Sequence", obj.entry[1].request!!.url))
        assertTrue(stringMatch("urn:uuid:7c393185-f15c-45bc-a", obj.entry[2].fullUrl))
        assertTrue(stringMatch("Sequence", (obj.entry[2].resource!! as Sequence).resourceType))
        assertTrue(stringMatch("generated", (obj.entry[2].resource!! as Sequence).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[2].resource!! as Sequence).text!!.div))
        assertTrue(stringMatch("dna", (obj.entry[2].resource!! as Sequence).type))
        assertEquals(0, (obj.entry[2].resource!! as Sequence).coordinateSystem)
        assertTrue(stringMatch("Patient/119", (obj.entry[2].resource!! as Sequence).patient!!.reference))
        assertTrue(stringMatch("Mary Chalmers", (obj.entry[2].resource!! as Sequence).patient!!.display))
        assertTrue(stringMatch("Specimen/120", (obj.entry[2].resource!! as Sequence).specimen!!.reference))
        assertTrue(stringMatch("buccal swab from Mary Chalmer", (obj.entry[2].resource!! as Sequence).specimen!!.display))
        assertTrue(stringMatch("http://www.ebi.ac.uk/ipd/imgt", (obj.entry[2].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].system))
        assertTrue(stringMatch("3.23", (obj.entry[2].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].version))
        assertTrue(stringMatch("HLA00001", (obj.entry[2].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].code))
        assertTrue(stringMatch("HLA-A*01:01:01:01", (obj.entry[2].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.text))
        assertEquals(1014, (obj.entry[2].resource!! as Sequence).referenceSeq!!.windowStart)
        assertEquals(1290, (obj.entry[2].resource!! as Sequence).referenceSeq!!.windowEnd)
        assertTrue(stringMatch("GTTCTCACACCATCCAGATAATGTATGGC", (obj.entry[2].resource!! as Sequence).observedSeq))
        assertTrue(stringMatch("POST", obj.entry[2].request!!.method))
        assertTrue(stringMatch("Sequence", obj.entry[2].request!!.url))
        assertTrue(stringMatch("urn:uuid:65c85f14-c3a0-4b72-8", obj.entry[3].fullUrl))
        assertTrue(stringMatch("Sequence", (obj.entry[3].resource!! as Sequence).resourceType))
        assertTrue(stringMatch("generated", (obj.entry[3].resource!! as Sequence).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[3].resource!! as Sequence).text!!.div))
        assertTrue(stringMatch("dna", (obj.entry[3].resource!! as Sequence).type))
        assertEquals(0, (obj.entry[3].resource!! as Sequence).coordinateSystem)
        assertTrue(stringMatch("Patient/119", (obj.entry[3].resource!! as Sequence).patient!!.reference))
        assertTrue(stringMatch("Mary Chalmers", (obj.entry[3].resource!! as Sequence).patient!!.display))
        assertTrue(stringMatch("Specimen/120", (obj.entry[3].resource!! as Sequence).specimen!!.reference))
        assertTrue(stringMatch("buccal swab from Mary Chalmer", (obj.entry[3].resource!! as Sequence).specimen!!.display))
        assertTrue(stringMatch("http://www.ebi.ac.uk/ipd/imgt", (obj.entry[3].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].system))
        assertTrue(stringMatch("3.23", (obj.entry[3].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].version))
        assertTrue(stringMatch("HLA00002", (obj.entry[3].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].code))
        assertTrue(stringMatch("HLA-A*01:02", (obj.entry[3].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.text))
        assertEquals(503, (obj.entry[3].resource!! as Sequence).referenceSeq!!.windowStart)
        assertEquals(773, (obj.entry[3].resource!! as Sequence).referenceSeq!!.windowEnd)
        assertTrue(stringMatch("GCTCCCACTCCATGAGGTATTTCTCCACA", (obj.entry[3].resource!! as Sequence).observedSeq))
        assertTrue(stringMatch("POST", obj.entry[3].request!!.method))
        assertTrue(stringMatch("Sequence", obj.entry[3].request!!.url))
        assertTrue(stringMatch("urn:uuid:fbba9fe7-0ece-4ec1-9", obj.entry[4].fullUrl))
        assertTrue(stringMatch("Sequence", (obj.entry[4].resource!! as Sequence).resourceType))
        assertTrue(stringMatch("generated", (obj.entry[4].resource!! as Sequence).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[4].resource!! as Sequence).text!!.div))
        assertTrue(stringMatch("dna", (obj.entry[4].resource!! as Sequence).type))
        assertEquals(0, (obj.entry[4].resource!! as Sequence).coordinateSystem)
        assertTrue(stringMatch("Patient/119", (obj.entry[4].resource!! as Sequence).patient!!.reference))
        assertTrue(stringMatch("Mary Chalmers", (obj.entry[4].resource!! as Sequence).patient!!.display))
        assertTrue(stringMatch("Specimen/120", (obj.entry[4].resource!! as Sequence).specimen!!.reference))
        assertTrue(stringMatch("buccal swab from Mary Chalmer", (obj.entry[4].resource!! as Sequence).specimen!!.display))
        assertTrue(stringMatch("http://www.ebi.ac.uk/ipd/imgt", (obj.entry[4].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].system))
        assertTrue(stringMatch("3.23", (obj.entry[4].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].version))
        assertTrue(stringMatch("HLA00002", (obj.entry[4].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.coding[0].code))
        assertTrue(stringMatch("HLA-A*01:02", (obj.entry[4].resource!! as Sequence).referenceSeq!!.referenceSeqId!!.text))
        assertEquals(1014, (obj.entry[4].resource!! as Sequence).referenceSeq!!.windowStart)
        assertEquals(1290, (obj.entry[4].resource!! as Sequence).referenceSeq!!.windowEnd)
        assertTrue(stringMatch("GTTCTCACACCATCCAGATAATGTATGGC", (obj.entry[4].resource!! as Sequence).observedSeq))
    }
}
