package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle85DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 456 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[157].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[157].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[157].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[157].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577547", (obj.entry[157].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[157].resource!! as Patient).active != null) (obj.entry[157].resource!! as Patient).active else false, "Field: (obj.entry[157].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[157].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Clarke", (obj.entry[157].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Christopher", (obj.entry[157].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[157].resource!! as Patient).gender))
        assertEquals("1950-11-17", (obj.entry[157].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[157].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[158].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[158].resource!! as Patient).resourceType))
        assertTrue(stringMatch("229", (obj.entry[158].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[158].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[158].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[158].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[158].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[158].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[158].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577548", (obj.entry[158].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[158].resource!! as Patient).active != null) (obj.entry[158].resource!! as Patient).active else false, "Field: (obj.entry[158].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[158].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Kennedy", (obj.entry[158].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Michele", (obj.entry[158].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[158].resource!! as Patient).gender))
        assertEquals("1943-09-03", (obj.entry[158].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[158].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[159].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[159].resource!! as Patient).resourceType))
        assertTrue(stringMatch("230", (obj.entry[159].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[159].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[159].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[159].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[159].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[159].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[159].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577549", (obj.entry[159].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[159].resource!! as Patient).active != null) (obj.entry[159].resource!! as Patient).active else false, "Field: (obj.entry[159].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[159].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Edwards", (obj.entry[159].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Jonathan", (obj.entry[159].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[159].resource!! as Patient).gender))
        assertEquals("1952-07-04", (obj.entry[159].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[159].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[160].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[160].resource!! as Patient).resourceType))
        assertTrue(stringMatch("231", (obj.entry[160].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[160].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[160].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[160].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[160].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[160].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[160].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577550", (obj.entry[160].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[160].resource!! as Patient).active != null) (obj.entry[160].resource!! as Patient).active else false, "Field: (obj.entry[160].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[160].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Dennis", (obj.entry[160].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Norman", (obj.entry[160].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[160].resource!! as Patient).gender))
        assertEquals("1941-09-25", (obj.entry[160].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[160].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[161].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[161].resource!! as Patient).resourceType))
        assertTrue(stringMatch("232", (obj.entry[161].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[161].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[161].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[161].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[161].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[161].resource!! as Patient).identifier[0].type!!.coding[0].code))
    }
}
