package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle27DataTest : DataTests() {
    @Test
    fun `practitionerrole-examples-general 393 Test`() {
        val json = File("./src/test/resources/model/sample_data/practitionerrole-examples-general.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[7].resource!! as PractitionerRole).text!!.div))
        assertTrue(stringMatch("Practitioner/f202", (obj.entry[7].resource!! as PractitionerRole).practitioner!!.reference))
        assertTrue(stringMatch("Luigi Maas", (obj.entry[7].resource!! as PractitionerRole).practitioner!!.display))
        assertTrue(stringMatch("Organization/f201", (obj.entry[7].resource!! as PractitionerRole).organization!!.reference))
        assertTrue(stringMatch("AUMC", (obj.entry[7].resource!! as PractitionerRole).organization!!.display))
        assertTrue(stringMatch("http://snomed.info/sct", (obj.entry[7].resource!! as PractitionerRole).code[0].coding[0].system))
        assertTrue(stringMatch("33526004", (obj.entry[7].resource!! as PractitionerRole).code[0].coding[0].code))
        assertTrue(stringMatch("Electronic laboratory reporti", (obj.entry[7].resource!! as PractitionerRole).code[0].coding[0].display))
        assertTrue(stringMatch("http://snomed.info/sct", (obj.entry[7].resource!! as PractitionerRole).specialty[0].coding[0].system))
        assertTrue(stringMatch("159285000", (obj.entry[7].resource!! as PractitionerRole).specialty[0].coding[0].code))
        assertTrue(stringMatch("Medical laboratory technician", (obj.entry[7].resource!! as PractitionerRole).specialty[0].coding[0].display))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[8].fullUrl))
        assertTrue(stringMatch("PractitionerRole", (obj.entry[8].resource!! as PractitionerRole).resourceType))
        assertTrue(stringMatch("f201-0", (obj.entry[8].resource!! as PractitionerRole).id))
        assertTrue(stringMatch("generated", (obj.entry[8].resource!! as PractitionerRole).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[8].resource!! as PractitionerRole).text!!.div))
        assertTrue(stringMatch("Practitioner/f201", (obj.entry[8].resource!! as PractitionerRole).practitioner!!.reference))
        assertTrue(stringMatch("Dokter Bronsig", (obj.entry[8].resource!! as PractitionerRole).practitioner!!.display))
        assertTrue(stringMatch("Organization/f201", (obj.entry[8].resource!! as PractitionerRole).organization!!.reference))
        assertTrue(stringMatch("AUMC", (obj.entry[8].resource!! as PractitionerRole).organization!!.display))
        assertTrue(stringMatch("http://snomed.info/sct", (obj.entry[8].resource!! as PractitionerRole).code[0].coding[0].system))
        assertTrue(stringMatch("225304007", (obj.entry[8].resource!! as PractitionerRole).code[0].coding[0].code))
        assertTrue(stringMatch("Implementation of planned int", (obj.entry[8].resource!! as PractitionerRole).code[0].coding[0].display))
        assertTrue(stringMatch("http://snomed.info/sct", (obj.entry[8].resource!! as PractitionerRole).specialty[0].coding[0].system))
        assertTrue(stringMatch("310512001", (obj.entry[8].resource!! as PractitionerRole).specialty[0].coding[0].code))
        assertTrue(stringMatch("Medical oncologist", (obj.entry[8].resource!! as PractitionerRole).specialty[0].coding[0].display))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[9].fullUrl))
        assertTrue(stringMatch("PractitionerRole", (obj.entry[9].resource!! as PractitionerRole).resourceType))
        assertTrue(stringMatch("f203-0", (obj.entry[9].resource!! as PractitionerRole).id))
        assertTrue(stringMatch("generated", (obj.entry[9].resource!! as PractitionerRole).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[9].resource!! as PractitionerRole).text!!.div))
        assertTrue(stringMatch("Practitioner/f203", (obj.entry[9].resource!! as PractitionerRole).practitioner!!.reference))
        assertTrue(stringMatch("Juri van Gelder", (obj.entry[9].resource!! as PractitionerRole).practitioner!!.display))
        assertTrue(stringMatch("Organization/f201", (obj.entry[9].resource!! as PractitionerRole).organization!!.reference))
        assertTrue(stringMatch("AUMC", (obj.entry[9].resource!! as PractitionerRole).organization!!.display))
        assertTrue(stringMatch("http://snomed.info/sct", (obj.entry[9].resource!! as PractitionerRole).code[0].coding[0].system))
        assertTrue(stringMatch("36682004", (obj.entry[9].resource!! as PractitionerRole).code[0].coding[0].code))
        assertTrue(stringMatch("Physical therapist", (obj.entry[9].resource!! as PractitionerRole).code[0].coding[0].display))
        assertTrue(stringMatch("http://snomed.info/sct", (obj.entry[9].resource!! as PractitionerRole).specialty[0].coding[0].system))
        assertTrue(stringMatch("410158009", (obj.entry[9].resource!! as PractitionerRole).specialty[0].coding[0].code))
        assertTrue(stringMatch("Assess physical therapist ser", (obj.entry[9].resource!! as PractitionerRole).specialty[0].coding[0].display))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[10].fullUrl))
        assertTrue(stringMatch("PractitionerRole", (obj.entry[10].resource!! as PractitionerRole).resourceType))
        assertTrue(stringMatch("f005-0", (obj.entry[10].resource!! as PractitionerRole).id))
        assertTrue(stringMatch("generated", (obj.entry[10].resource!! as PractitionerRole).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[10].resource!! as PractitionerRole).text!!.div))
        assertTrue(stringMatch("Practitioner/f005", (obj.entry[10].resource!! as PractitionerRole).practitioner!!.reference))
        assertTrue(stringMatch("Langeveld Anne", (obj.entry[10].resource!! as PractitionerRole).practitioner!!.display))
        assertTrue(stringMatch("Organization/f001", (obj.entry[10].resource!! as PractitionerRole).organization!!.reference))
        assertTrue(stringMatch("BMC", (obj.entry[10].resource!! as PractitionerRole).organization!!.display))
        assertTrue(stringMatch("urn:oid:2.16.840.1.113883.2.4", (obj.entry[10].resource!! as PractitionerRole).code[0].coding[0].system))
        assertTrue(stringMatch("01.000", (obj.entry[10].resource!! as PractitionerRole).code[0].coding[0].code))
        assertTrue(stringMatch("Arts", (obj.entry[10].resource!! as PractitionerRole).code[0].coding[0].display))
        assertTrue(stringMatch("Care role", (obj.entry[10].resource!! as PractitionerRole).code[0].text))
        assertTrue(stringMatch("urn:oid:2.16.840.1.113883.2.4", (obj.entry[10].resource!! as PractitionerRole).specialty[0].coding[0].system))
        assertTrue(stringMatch("01.018", (obj.entry[10].resource!! as PractitionerRole).specialty[0].coding[0].code))
        assertTrue(stringMatch("Keel- neus- en oorarts", (obj.entry[10].resource!! as PractitionerRole).specialty[0].coding[0].display))
        assertTrue(stringMatch("specialization", (obj.entry[10].resource!! as PractitionerRole).specialty[0].text))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[11].fullUrl))
        assertTrue(stringMatch("PractitionerRole", (obj.entry[11].resource!! as PractitionerRole).resourceType))
        assertTrue(stringMatch("f006-0", (obj.entry[11].resource!! as PractitionerRole).id))
        assertTrue(stringMatch("generated", (obj.entry[11].resource!! as PractitionerRole).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[11].resource!! as PractitionerRole).text!!.div))
        assertTrue(stringMatch("Practitioner/f006", (obj.entry[11].resource!! as PractitionerRole).practitioner!!.reference))
        assertTrue(stringMatch("Rob van den Berk", (obj.entry[11].resource!! as PractitionerRole).practitioner!!.display))
        assertTrue(stringMatch("Organization/f001", (obj.entry[11].resource!! as PractitionerRole).organization!!.reference))
        assertTrue(stringMatch("BMC", (obj.entry[11].resource!! as PractitionerRole).organization!!.display))
        assertTrue(stringMatch("urn:oid:2.16.840.1.113883.2.4", (obj.entry[11].resource!! as PractitionerRole).code[0].coding[0].system))
        assertTrue(stringMatch("01.000", (obj.entry[11].resource!! as PractitionerRole).code[0].coding[0].code))
        assertTrue(stringMatch("Arts", (obj.entry[11].resource!! as PractitionerRole).code[0].coding[0].display))
        assertTrue(stringMatch("Care role", (obj.entry[11].resource!! as PractitionerRole).code[0].text))
    }
}
