package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle25DataTest : DataTests() {
    @Test
    fun `diagnosticreport-hla-genetics-results-example 390 Test`() {
        val json = File("./src/test/resources/model/sample_data/diagnosticreport-hla-genetics-results-example.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("http://hl7.org/fhir/Structure", (obj.entry[21].resource!! as Observation).extension[0].url))
        assertTrue(stringMatch("http://www.genenames.org", (obj.entry[21].resource!! as Observation).extension[0].valueCodeableConcept!!.coding[0].system))
        assertTrue(stringMatch("HGNC:4933", (obj.entry[21].resource!! as Observation).extension[0].valueCodeableConcept!!.coding[0].code))
        assertTrue(stringMatch("HLA-C", (obj.entry[21].resource!! as Observation).extension[0].valueCodeableConcept!!.coding[0].display))
        assertTrue(stringMatch("http://hl7.org/fhir/Structure", (obj.entry[21].resource!! as Observation).extension[1].url))
        assertTrue(stringMatch("http://loinc.org", (obj.entry[21].resource!! as Observation).extension[1].valueCodeableConcept!!.coding[0].system))
        assertTrue(stringMatch("LA6683-2", (obj.entry[21].resource!! as Observation).extension[1].valueCodeableConcept!!.coding[0].code))
        assertTrue(stringMatch("germline", (obj.entry[21].resource!! as Observation).extension[1].valueCodeableConcept!!.coding[0].display))
        assertTrue(stringMatch("final", (obj.entry[21].resource!! as Observation).status))
        assertTrue(stringMatch("http://loinc.org", (obj.entry[21].resource!! as Observation).code.coding[0].system))
        assertTrue(stringMatch("77636-9", (obj.entry[21].resource!! as Observation).code.coding[0].code))
        assertTrue(stringMatch("HLA-C [Type] by High resoluti", (obj.entry[21].resource!! as Observation).code.coding[0].display))
        assertTrue(stringMatch("Patient/119", (obj.entry[21].resource!! as Observation).subject!!.reference))
        assertTrue(stringMatch("Mary Chalmers", (obj.entry[21].resource!! as Observation).subject!!.display))
        assertEquals("2016-12-15", (obj.entry[21].resource!! as Observation).effectiveDateTime.toString())
        assertTrue(stringMatch("Specimen/120", (obj.entry[21].resource!! as Observation).specimen!!.reference))
        assertTrue(stringMatch("buccal swab from Mary Chalmer", (obj.entry[21].resource!! as Observation).specimen!!.display))
        assertTrue(stringMatch("derived-from", (obj.entry[21].resource!! as Observation).related[0].type))
        assertTrue(stringMatch("urn:uuid:709c5315-9403-4867-9", (obj.entry[21].resource!! as Observation).related[0].target.reference))
        assertTrue(stringMatch("HLA-C*01:02:01G, exons 2 and ", (obj.entry[21].resource!! as Observation).related[0].target.display))
        assertTrue(stringMatch("derived-from", (obj.entry[21].resource!! as Observation).related[1].type))
        assertTrue(stringMatch("urn:uuid:8b2aa21c-1426-4717-8", (obj.entry[21].resource!! as Observation).related[1].target.reference))
        assertTrue(stringMatch("HLA-C*03:04:01G, exons 2 and ", (obj.entry[21].resource!! as Observation).related[1].target.display))
        assertTrue(stringMatch("POST", obj.entry[21].request!!.method))
        assertTrue(stringMatch("Observation", obj.entry[21].request!!.url))
    }

    @Test
    fun `practitionerrole-examples-general 391 Test`() {
        val json = File("./src/test/resources/model/sample_data/practitionerrole-examples-general.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("Bundle", obj.resourceType))
        assertTrue(stringMatch("3ad0687e-f477-468c-afd5-fcc2b", obj.id))
        assertTrue(stringMatch("collection", obj.type))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[0].fullUrl))
        assertTrue(stringMatch("PractitionerRole", (obj.entry[0].resource!! as PractitionerRole).resourceType))
        assertTrue(stringMatch("f003-0", (obj.entry[0].resource!! as PractitionerRole).id))
        assertTrue(stringMatch("generated", (obj.entry[0].resource!! as PractitionerRole).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[0].resource!! as PractitionerRole).text!!.div))
        assertTrue(stringMatch("Practitioner/f003", (obj.entry[0].resource!! as PractitionerRole).practitioner!!.reference))
        assertTrue(stringMatch("Marc Versteegh", (obj.entry[0].resource!! as PractitionerRole).practitioner!!.display))
        assertTrue(stringMatch("Organization/f001", (obj.entry[0].resource!! as PractitionerRole).organization!!.reference))
        assertTrue(stringMatch("BMC", (obj.entry[0].resource!! as PractitionerRole).organization!!.display))
        assertTrue(stringMatch("urn:oid:2.16.840.1.113883.2.4", (obj.entry[0].resource!! as PractitionerRole).code[0].coding[0].system))
        assertTrue(stringMatch("01.000", (obj.entry[0].resource!! as PractitionerRole).code[0].coding[0].code))
        assertTrue(stringMatch("Arts", (obj.entry[0].resource!! as PractitionerRole).code[0].coding[0].display))
        assertTrue(stringMatch("Care role", (obj.entry[0].resource!! as PractitionerRole).code[0].text))
        assertTrue(stringMatch("urn:oid:2.16.840.1.113883.2.4", (obj.entry[0].resource!! as PractitionerRole).specialty[0].coding[0].system))
        assertTrue(stringMatch("01.011", (obj.entry[0].resource!! as PractitionerRole).specialty[0].coding[0].code))
        assertTrue(stringMatch("Cardiothoracal surgery", (obj.entry[0].resource!! as PractitionerRole).specialty[0].coding[0].display))
        assertTrue(stringMatch("specialization", (obj.entry[0].resource!! as PractitionerRole).specialty[0].text))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[1].fullUrl))
        assertTrue(stringMatch("PractitionerRole", (obj.entry[1].resource!! as PractitionerRole).resourceType))
        assertTrue(stringMatch("example-0", (obj.entry[1].resource!! as PractitionerRole).id))
        assertTrue(stringMatch("generated", (obj.entry[1].resource!! as PractitionerRole).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[1].resource!! as PractitionerRole).text!!.div))
        assertTrue(stringMatch("http://example.org/role-ident", (obj.entry[1].resource!! as PractitionerRole).identifier[0].system))
        assertTrue(stringMatch("52", (obj.entry[1].resource!! as PractitionerRole).identifier[0].value))
        assertEquals("2012-01-01", (obj.entry[1].resource!! as PractitionerRole).period!!.start.toString())
        assertEquals("2012-03-31", (obj.entry[1].resource!! as PractitionerRole).period!!.end.toString())
        assertTrue(stringMatch("Practitioner/example", (obj.entry[1].resource!! as PractitionerRole).practitioner!!.reference))
        assertTrue(stringMatch("Adam Careful", (obj.entry[1].resource!! as PractitionerRole).practitioner!!.display))
        assertTrue(stringMatch("Organization/f001", (obj.entry[1].resource!! as PractitionerRole).organization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0286", (obj.entry[1].resource!! as PractitionerRole).code[0].coding[0].system))
        assertTrue(stringMatch("RP", (obj.entry[1].resource!! as PractitionerRole).code[0].coding[0].code))
        assertTrue(stringMatch("Location/1", (obj.entry[1].resource!! as PractitionerRole).location[0].reference))
        assertTrue(stringMatch("South Wing, second floor", (obj.entry[1].resource!! as PractitionerRole).location[0].display))
        assertTrue(stringMatch("HealthcareService/example", (obj.entry[1].resource!! as PractitionerRole).healthcareService[0].reference))
        assertTrue(stringMatch("email", (obj.entry[1].resource!! as PractitionerRole).telecom[0].system))
        assertTrue(stringMatch("dr.adam.careful@example.org", (obj.entry[1].resource!! as PractitionerRole).telecom[0].value))
        assertTrue(stringMatch("Endpoint/example", (obj.entry[1].resource!! as PractitionerRole).endpoint[0].reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[2].fullUrl))
        assertTrue(stringMatch("PractitionerRole", (obj.entry[2].resource!! as PractitionerRole).resourceType))
        assertTrue(stringMatch("example-1", (obj.entry[2].resource!! as PractitionerRole).id))
        assertTrue(stringMatch("generated", (obj.entry[2].resource!! as PractitionerRole).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[2].resource!! as PractitionerRole).text!!.div))
        assertEquals("2012-01-01", (obj.entry[2].resource!! as PractitionerRole).period!!.start.toString())
    }
}
