package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle70DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 441 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("official", (obj.entry[94].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Ortega", (obj.entry[94].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Samuel", (obj.entry[94].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[94].resource!! as Patient).gender))
        assertEquals("1943-06-07", (obj.entry[94].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[94].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[95].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[95].resource!! as Patient).resourceType))
        assertTrue(stringMatch("166", (obj.entry[95].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[95].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[95].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[95].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[95].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[95].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[95].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577485", (obj.entry[95].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[95].resource!! as Patient).active != null) (obj.entry[95].resource!! as Patient).active else false, "Field: (obj.entry[95].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[95].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Harvey", (obj.entry[95].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Andy", (obj.entry[95].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[95].resource!! as Patient).gender))
        assertEquals("2009-03-17", (obj.entry[95].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[95].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[96].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[96].resource!! as Patient).resourceType))
        assertTrue(stringMatch("167", (obj.entry[96].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[96].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[96].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[96].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[96].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[96].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[96].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577486", (obj.entry[96].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[96].resource!! as Patient).active != null) (obj.entry[96].resource!! as Patient).active else false, "Field: (obj.entry[96].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[96].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Bailey", (obj.entry[96].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Ian", (obj.entry[96].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[96].resource!! as Patient).gender))
        assertEquals("2009-06-20", (obj.entry[96].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[96].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[97].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[97].resource!! as Patient).resourceType))
        assertTrue(stringMatch("168", (obj.entry[97].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[97].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[97].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[97].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[97].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[97].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[97].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577487", (obj.entry[97].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[97].resource!! as Patient).active != null) (obj.entry[97].resource!! as Patient).active else false, "Field: (obj.entry[97].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[97].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Walker", (obj.entry[97].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Denise", (obj.entry[97].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[97].resource!! as Patient).gender))
        assertEquals("2009-03-19", (obj.entry[97].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[97].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[98].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[98].resource!! as Patient).resourceType))
        assertTrue(stringMatch("169", (obj.entry[98].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[98].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[98].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[98].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[98].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[98].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[98].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577488", (obj.entry[98].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[98].resource!! as Patient).active != null) (obj.entry[98].resource!! as Patient).active else false, "Field: (obj.entry[98].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[98].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Brock", (obj.entry[98].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Beth", (obj.entry[98].resource!! as Patient).name[0].given[0]))
    }
}
