package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle74DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 445 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[111].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[111].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[111].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577501", (obj.entry[111].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[111].resource!! as Patient).active != null) (obj.entry[111].resource!! as Patient).active else false, "Field: (obj.entry[111].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[111].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Wilson", (obj.entry[111].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Bill", (obj.entry[111].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[111].resource!! as Patient).gender))
        assertEquals("1948-10-08", (obj.entry[111].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[111].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[112].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[112].resource!! as Patient).resourceType))
        assertTrue(stringMatch("183", (obj.entry[112].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[112].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[112].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[112].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[112].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[112].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[112].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577502", (obj.entry[112].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[112].resource!! as Patient).active != null) (obj.entry[112].resource!! as Patient).active else false, "Field: (obj.entry[112].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[112].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Doyle", (obj.entry[112].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Esther", (obj.entry[112].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[112].resource!! as Patient).gender))
        assertEquals("1970-05-21", (obj.entry[112].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[112].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[113].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[113].resource!! as Patient).resourceType))
        assertTrue(stringMatch("184", (obj.entry[113].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[113].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[113].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[113].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[113].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[113].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[113].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577503", (obj.entry[113].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[113].resource!! as Patient).active != null) (obj.entry[113].resource!! as Patient).active else false, "Field: (obj.entry[113].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[113].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Hunter", (obj.entry[113].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Micheal", (obj.entry[113].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[113].resource!! as Patient).gender))
        assertEquals("1942-02-12", (obj.entry[113].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[113].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[114].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[114].resource!! as Patient).resourceType))
        assertTrue(stringMatch("185", (obj.entry[114].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[114].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[114].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[114].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[114].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[114].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[114].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577504", (obj.entry[114].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[114].resource!! as Patient).active != null) (obj.entry[114].resource!! as Patient).active else false, "Field: (obj.entry[114].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[114].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Black", (obj.entry[114].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Salvador", (obj.entry[114].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[114].resource!! as Patient).gender))
        assertEquals("1952-05-21", (obj.entry[114].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[114].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[115].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[115].resource!! as Patient).resourceType))
        assertTrue(stringMatch("186", (obj.entry[115].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[115].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[115].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[115].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[115].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[115].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[115].resource!! as Patient).identifier[0].system))
    }
}
