package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle200DataTest : DataTests() {
    @Test
    fun `patient-examples-general 574 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-general.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[2].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[2].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[2].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("444555555", (obj.entry[2].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[2].resource!! as Patient).active != null) (obj.entry[2].resource!! as Patient).active else false, "Field: (obj.entry[2].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[2].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Kidd", (obj.entry[2].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Kari", (obj.entry[2].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[2].resource!! as Patient).telecom[0].system))
        assertTrue(stringMatch("555-555-2005", (obj.entry[2].resource!! as Patient).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[2].resource!! as Patient).telecom[0].use))
        assertTrue(stringMatch("female", (obj.entry[2].resource!! as Patient).gender))
        assertTrue(stringMatch("home", (obj.entry[2].resource!! as Patient).address[0].use))
        assertTrue(stringMatch("2222 Home Street", (obj.entry[2].resource!! as Patient).address[0].line[0]))
        assertTrue(stringMatch("Organization/hl7", (obj.entry[2].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/4", obj.entry[3].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[3].resource!! as Patient).resourceType))
        assertTrue(stringMatch("4", (obj.entry[3].resource!! as Patient).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[3].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[3].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[3].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[3].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[3].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[3].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("444114567", (obj.entry[3].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[3].resource!! as Patient).active != null) (obj.entry[3].resource!! as Patient).active else false, "Field: (obj.entry[3].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[3].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Nuclear", (obj.entry[3].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Nancy", (obj.entry[3].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[3].resource!! as Patient).telecom[0].system))
        assertTrue(stringMatch("555-555-5001", (obj.entry[3].resource!! as Patient).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[3].resource!! as Patient).telecom[0].use))
        assertTrue(stringMatch("female", (obj.entry[3].resource!! as Patient).gender))
        assertTrue(stringMatch("home", (obj.entry[3].resource!! as Patient).address[0].use))
        assertTrue(stringMatch("6666 Home Street", (obj.entry[3].resource!! as Patient).address[0].line[0]))
        assertTrue(stringMatch("Organization/hl7", (obj.entry[3].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/5", obj.entry[4].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[4].resource!! as Patient).resourceType))
        assertTrue(stringMatch("5", (obj.entry[4].resource!! as Patient).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[4].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[4].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[4].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[4].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[4].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[4].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("444111234", (obj.entry[4].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[4].resource!! as Patient).active != null) (obj.entry[4].resource!! as Patient).active else false, "Field: (obj.entry[4].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[4].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Nuclear", (obj.entry[4].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Neville", (obj.entry[4].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[4].resource!! as Patient).telecom[0].system))
        assertTrue(stringMatch("555-555-5001", (obj.entry[4].resource!! as Patient).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[4].resource!! as Patient).telecom[0].use))
        assertTrue(stringMatch("male", (obj.entry[4].resource!! as Patient).gender))
        assertTrue(stringMatch("home", (obj.entry[4].resource!! as Patient).address[0].use))
        assertTrue(stringMatch("6666 Home Street", (obj.entry[4].resource!! as Patient).address[0].line[0]))
        assertTrue(stringMatch("Organization/hl7", (obj.entry[4].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/6", obj.entry[5].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[5].resource!! as Patient).resourceType))
        assertTrue(stringMatch("6", (obj.entry[5].resource!! as Patient).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[5].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[5].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[5].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[5].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[5].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[5].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("444113456", (obj.entry[5].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[5].resource!! as Patient).active != null) (obj.entry[5].resource!! as Patient).active else false, "Field: (obj.entry[5].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[5].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Nuclear", (obj.entry[5].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Ned", (obj.entry[5].resource!! as Patient).name[0].given[0]))
    }
}
