package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle65DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 436 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("Virgil", (obj.entry[73].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[73].resource!! as Patient).gender))
        assertEquals("1997-06-17", (obj.entry[73].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[73].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[74].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[74].resource!! as Patient).resourceType))
        assertTrue(stringMatch("145", (obj.entry[74].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[74].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[74].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[74].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[74].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[74].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[74].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577464", (obj.entry[74].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[74].resource!! as Patient).active != null) (obj.entry[74].resource!! as Patient).active else false, "Field: (obj.entry[74].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[74].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Lane", (obj.entry[74].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Cory", (obj.entry[74].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[74].resource!! as Patient).gender))
        assertEquals("1973-04-15", (obj.entry[74].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[74].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[75].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[75].resource!! as Patient).resourceType))
        assertTrue(stringMatch("146", (obj.entry[75].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[75].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[75].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[75].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[75].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[75].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[75].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577465", (obj.entry[75].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[75].resource!! as Patient).active != null) (obj.entry[75].resource!! as Patient).active else false, "Field: (obj.entry[75].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[75].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Harrison", (obj.entry[75].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Willie", (obj.entry[75].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[75].resource!! as Patient).gender))
        assertEquals("1972-06-26", (obj.entry[75].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[75].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[76].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[76].resource!! as Patient).resourceType))
        assertTrue(stringMatch("147", (obj.entry[76].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[76].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[76].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[76].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[76].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[76].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[76].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577466", (obj.entry[76].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[76].resource!! as Patient).active != null) (obj.entry[76].resource!! as Patient).active else false, "Field: (obj.entry[76].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[76].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Palmer", (obj.entry[76].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Kim", (obj.entry[76].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[76].resource!! as Patient).gender))
        assertEquals("1968-09-10", (obj.entry[76].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[76].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[77].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[77].resource!! as Patient).resourceType))
        assertTrue(stringMatch("148", (obj.entry[77].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[77].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[77].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[77].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[77].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[77].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[77].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577467", (obj.entry[77].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[77].resource!! as Patient).active != null) (obj.entry[77].resource!! as Patient).active else false, "Field: (obj.entry[77].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[77].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("May", (obj.entry[77].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Hilda", (obj.entry[77].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[77].resource!! as Patient).gender))
        assertEquals("1983-05-23", (obj.entry[77].resource!! as Patient).birthDate.toString())
    }
}
