package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle69DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 440 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[90].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577480", (obj.entry[90].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[90].resource!! as Patient).active != null) (obj.entry[90].resource!! as Patient).active else false, "Field: (obj.entry[90].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[90].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Hunt", (obj.entry[90].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Zachary", (obj.entry[90].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[90].resource!! as Patient).gender))
        assertEquals("1945-06-02", (obj.entry[90].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[90].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[91].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[91].resource!! as Patient).resourceType))
        assertTrue(stringMatch("162", (obj.entry[91].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[91].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[91].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[91].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[91].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[91].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[91].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577481", (obj.entry[91].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[91].resource!! as Patient).active != null) (obj.entry[91].resource!! as Patient).active else false, "Field: (obj.entry[91].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[91].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Palmer", (obj.entry[91].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Tyler", (obj.entry[91].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[91].resource!! as Patient).gender))
        assertEquals("1940-05-08", (obj.entry[91].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[91].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[92].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[92].resource!! as Patient).resourceType))
        assertTrue(stringMatch("163", (obj.entry[92].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[92].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[92].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[92].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[92].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[92].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[92].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577482", (obj.entry[92].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[92].resource!! as Patient).active != null) (obj.entry[92].resource!! as Patient).active else false, "Field: (obj.entry[92].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[92].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Marshall", (obj.entry[92].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Johnny", (obj.entry[92].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[92].resource!! as Patient).gender))
        assertEquals("1943-04-06", (obj.entry[92].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[92].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[93].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[93].resource!! as Patient).resourceType))
        assertTrue(stringMatch("164", (obj.entry[93].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[93].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[93].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[93].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[93].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[93].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[93].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577483", (obj.entry[93].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[93].resource!! as Patient).active != null) (obj.entry[93].resource!! as Patient).active else false, "Field: (obj.entry[93].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[93].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Mccarthy", (obj.entry[93].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Becky", (obj.entry[93].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[93].resource!! as Patient).gender))
        assertEquals("1950-05-30", (obj.entry[93].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[93].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[94].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[94].resource!! as Patient).resourceType))
        assertTrue(stringMatch("165", (obj.entry[94].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[94].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[94].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[94].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[94].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[94].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[94].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577484", (obj.entry[94].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[94].resource!! as Patient).active != null) (obj.entry[94].resource!! as Patient).active else false, "Field: (obj.entry[94].resource!! as Patient).active")
    }
}
