package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle40DataTest : DataTests() {
    @Test
    fun `questionnaire-profile-example-ussg-fht 409 Test`() {
        val json = File("./src/test/resources/model/sample_data/questionnaire-profile-example-ussg-fht.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("-- COPD", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[41].display))
        assertTrue(stringMatch("LA10560-3", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[42].code))
        assertTrue(stringMatch("-- Chronic Bronchitis", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[42].display))
        assertTrue(stringMatch("LA10561-1", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[43].code))
        assertTrue(stringMatch("-- Emphysema", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[43].display))
        assertTrue(stringMatch("LA10562-9", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[44].code))
        assertTrue(stringMatch("-- Chronic Lower Respiratory ", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[44].display))
        assertTrue(stringMatch("LA10563-7", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[45].code))
        assertTrue(stringMatch("-- Influenza/Pneumonia", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[45].display))
        assertTrue(stringMatch("LA10564-5", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[46].code))
        assertTrue(stringMatch("-- Asthma", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[46].display))
        assertTrue(stringMatch("LA10590-0", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[47].code))
        assertTrue(stringMatch("Neurological Disorders", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[47].display))
        assertTrue(stringMatch("LA10527-2", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[48].code))
        assertTrue(stringMatch("Osteoporosis", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[48].display))
        assertTrue(stringMatch("LA10535-5", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[49].code))
        assertTrue(stringMatch("Psychological Disorders", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[49].display))
        assertTrue(stringMatch("LA10574-4", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[50].code))
        assertTrue(stringMatch("-- Anxiety", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[50].display))
        assertTrue(stringMatch("LA10575-1", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[51].code))
        assertTrue(stringMatch("-- Bipolar/Manic Depressive D", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[51].display))
        assertTrue(stringMatch("LA10576-9", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[52].code))
        assertTrue(stringMatch("-- Depression", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[52].display))
        assertTrue(stringMatch("LA10577-7", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[53].code))
        assertTrue(stringMatch("-- Attention Deficit Hyper Ac", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[53].display))
        assertTrue(stringMatch("LA10578-5", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[54].code))
        assertTrue(stringMatch("-- Autism", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[54].display))
        assertTrue(stringMatch("LA10579-3", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[55].code))
        assertTrue(stringMatch("-- Personality Disorder", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[55].display))
        assertTrue(stringMatch("LA10580-1", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[56].code))
        assertTrue(stringMatch("-- Eating Disorder", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[56].display))
        assertTrue(stringMatch("LA10581-9", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[57].code))
        assertTrue(stringMatch("-- Obsessive Compulsive Disor", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[57].display))
        assertTrue(stringMatch("LA10582-7", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[58].code))
        assertTrue(stringMatch("-- Panic Disorder", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[58].display))
        assertTrue(stringMatch("LA10583-5", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[59].code))
        assertTrue(stringMatch("-- Post Traumatic Stress Diso", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[59].display))
        assertTrue(stringMatch("LA10584-3", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[60].code))
        assertTrue(stringMatch("-- Schizophrenia", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[60].display))
        assertTrue(stringMatch("LA10585-0", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[61].code))
        assertTrue(stringMatch("-- Social Phobia", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[61].display))
        assertTrue(stringMatch("LA10586-8", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[62].code))
        assertTrue(stringMatch("-- Dementia", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[62].display))
        assertTrue(stringMatch("LA10591-8", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[63].code))
        assertTrue(stringMatch("Septicemia", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[63].display))
        assertTrue(stringMatch("LA10522-3", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[64].code))
        assertTrue(stringMatch("Stroke/Brain Attack", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[64].display))
        assertTrue(stringMatch("LA10530-6", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[65].code))
        assertTrue(stringMatch("Sudden Infant Death Syndrome", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[65].display))
        assertTrue(stringMatch("PUT", obj.entry[7].request!!.method))
        assertTrue(stringMatch("http://hl7.org/fhir/us/sdc/Va", obj.entry[7].request!!.url))
        assertTrue(stringMatch("http://hl7.org/fhir/us/sdc/Va", obj.entry[8].fullUrl))
        assertTrue(stringMatch("ValueSet", (obj.entry[8].resource!! as ValueSet).resourceType))
        assertTrue(stringMatch("LL619-8", (obj.entry[8].resource!! as ValueSet).id))
        assertTrue(stringMatch("http://hl7.org/fhir/us/sdc/St", (obj.entry[8].resource!! as ValueSet).meta!!.profile[0]))
        assertTrue(stringMatch("generated", (obj.entry[8].resource!! as ValueSet).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[8].resource!! as ValueSet).text!!.div))
        assertTrue(stringMatch("http://details.loinc.org/Answ", (obj.entry[8].resource!! as ValueSet).url))
        assertTrue(stringMatch("USSG-FHT age", (obj.entry[8].resource!! as ValueSet).name))
        assertTrue(stringMatch("active", (obj.entry[8].resource!! as ValueSet).status))
        assertTrue(stringMatch("Regenstrief Institute, Inc an", (obj.entry[8].resource!! as ValueSet).publisher))
        assertTrue(stringMatch("Family history tool age range", (obj.entry[8].resource!! as ValueSet).description))
        assertEquals(true, if ((obj.entry[8].resource!! as ValueSet).immutable != null) (obj.entry[8].resource!! as ValueSet).immutable else false, "Field: (obj.entry[8].resource!! as ValueSet).immutable")
        assertTrue(stringMatch("Refer to https://loinc.org/te", (obj.entry[8].resource!! as ValueSet).copyright))
        assertEquals(false, if ((obj.entry[8].resource!! as ValueSet).extensible != null) (obj.entry[8].resource!! as ValueSet).extensible else false, "Field: (obj.entry[8].resource!! as ValueSet).extensible")
        assertTrue(stringMatch("http://loinc.org", (obj.entry[8].resource!! as ValueSet).compose!!.include[0].system))
        assertTrue(stringMatch("LA10402-8", (obj.entry[8].resource!! as ValueSet).compose!!.include[0].concept[0].code))
        assertTrue(stringMatch("Pre-Birth", (obj.entry[8].resource!! as ValueSet).compose!!.include[0].concept[0].display))
        assertTrue(stringMatch("LA10403-6", (obj.entry[8].resource!! as ValueSet).compose!!.include[0].concept[1].code))
        assertTrue(stringMatch("Newborn", (obj.entry[8].resource!! as ValueSet).compose!!.include[0].concept[1].display))
        assertTrue(stringMatch("LA10394-7", (obj.entry[8].resource!! as ValueSet).compose!!.include[0].concept[2].code))
    }
}
