package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle28DataTest : DataTests() {
    @Test
    fun `practitionerrole-examples-general 394 Test`() {
        val json = File("./src/test/resources/model/sample_data/practitionerrole-examples-general.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("urn:oid:2.16.840.1.113883.2.4", (obj.entry[11].resource!! as PractitionerRole).specialty[0].coding[0].system))
        assertTrue(stringMatch("17.000", (obj.entry[11].resource!! as PractitionerRole).specialty[0].coding[0].code))
        assertTrue(stringMatch("Pharmacist", (obj.entry[11].resource!! as PractitionerRole).specialty[0].coding[0].display))
        assertTrue(stringMatch("specialization", (obj.entry[11].resource!! as PractitionerRole).specialty[0].text))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[12].fullUrl))
        assertTrue(stringMatch("PractitionerRole", (obj.entry[12].resource!! as PractitionerRole).resourceType))
        assertTrue(stringMatch("f001-0", (obj.entry[12].resource!! as PractitionerRole).id))
        assertTrue(stringMatch("generated", (obj.entry[12].resource!! as PractitionerRole).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[12].resource!! as PractitionerRole).text!!.div))
        assertTrue(stringMatch("Practitioner/f001", (obj.entry[12].resource!! as PractitionerRole).practitioner!!.reference))
        assertTrue(stringMatch("Eric van den broek", (obj.entry[12].resource!! as PractitionerRole).practitioner!!.display))
        assertTrue(stringMatch("Organization/f001", (obj.entry[12].resource!! as PractitionerRole).organization!!.reference))
        assertTrue(stringMatch("BMC", (obj.entry[12].resource!! as PractitionerRole).organization!!.display))
        assertTrue(stringMatch("urn:oid:2.16.840.1.113883.2.4", (obj.entry[12].resource!! as PractitionerRole).code[0].coding[0].system))
        assertTrue(stringMatch("01.000", (obj.entry[12].resource!! as PractitionerRole).code[0].coding[0].code))
        assertTrue(stringMatch("Arts", (obj.entry[12].resource!! as PractitionerRole).code[0].coding[0].display))
        assertTrue(stringMatch("Care role", (obj.entry[12].resource!! as PractitionerRole).code[0].text))
        assertTrue(stringMatch("urn:oid:2.16.840.1.113883.2.4", (obj.entry[12].resource!! as PractitionerRole).specialty[0].coding[0].system))
        assertTrue(stringMatch("01.018", (obj.entry[12].resource!! as PractitionerRole).specialty[0].coding[0].code))
        assertTrue(stringMatch("Ear-, Nose and Throat", (obj.entry[12].resource!! as PractitionerRole).specialty[0].coding[0].display))
        assertTrue(stringMatch("specialization", (obj.entry[12].resource!! as PractitionerRole).specialty[0].text))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[13].fullUrl))
        assertTrue(stringMatch("PractitionerRole", (obj.entry[13].resource!! as PractitionerRole).resourceType))
        assertTrue(stringMatch("f002-0", (obj.entry[13].resource!! as PractitionerRole).id))
        assertTrue(stringMatch("generated", (obj.entry[13].resource!! as PractitionerRole).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[13].resource!! as PractitionerRole).text!!.div))
        assertTrue(stringMatch("Practitioner/f002", (obj.entry[13].resource!! as PractitionerRole).practitioner!!.reference))
        assertTrue(stringMatch("Pieter Voigt", (obj.entry[13].resource!! as PractitionerRole).practitioner!!.display))
        assertTrue(stringMatch("Organization/f001", (obj.entry[13].resource!! as PractitionerRole).organization!!.reference))
        assertTrue(stringMatch("BMC", (obj.entry[13].resource!! as PractitionerRole).organization!!.display))
        assertTrue(stringMatch("urn:oid:2.16.840.1.113883.2.4", (obj.entry[13].resource!! as PractitionerRole).code[0].coding[0].system))
        assertTrue(stringMatch("01.000", (obj.entry[13].resource!! as PractitionerRole).code[0].coding[0].code))
        assertTrue(stringMatch("Arts", (obj.entry[13].resource!! as PractitionerRole).code[0].coding[0].display))
        assertTrue(stringMatch("Care role", (obj.entry[13].resource!! as PractitionerRole).code[0].text))
        assertTrue(stringMatch("urn:oid:2.16.840.1.113883.2.4", (obj.entry[13].resource!! as PractitionerRole).specialty[0].coding[0].system))
        assertTrue(stringMatch("01.011", (obj.entry[13].resource!! as PractitionerRole).specialty[0].coding[0].code))
        assertTrue(stringMatch("Cardiothoracal surgery", (obj.entry[13].resource!! as PractitionerRole).specialty[0].coding[0].display))
        assertTrue(stringMatch("specialization", (obj.entry[13].resource!! as PractitionerRole).specialty[0].text))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[14].fullUrl))
        assertTrue(stringMatch("PractitionerRole", (obj.entry[14].resource!! as PractitionerRole).resourceType))
        assertTrue(stringMatch("f204-0", (obj.entry[14].resource!! as PractitionerRole).id))
        assertTrue(stringMatch("generated", (obj.entry[14].resource!! as PractitionerRole).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[14].resource!! as PractitionerRole).text!!.div))
        assertTrue(stringMatch("Practitioner/f204", (obj.entry[14].resource!! as PractitionerRole).practitioner!!.reference))
        assertTrue(stringMatch("Carla Espinosa", (obj.entry[14].resource!! as PractitionerRole).practitioner!!.display))
        assertTrue(stringMatch("Organization/f201", (obj.entry[14].resource!! as PractitionerRole).organization!!.reference))
        assertTrue(stringMatch("AUMC", (obj.entry[14].resource!! as PractitionerRole).organization!!.display))
        assertTrue(stringMatch("http://snomed.info/sct", (obj.entry[14].resource!! as PractitionerRole).code[0].coding[0].system))
        assertTrue(stringMatch("224565004", (obj.entry[14].resource!! as PractitionerRole).code[0].coding[0].code))
        assertTrue(stringMatch("Renal nurse", (obj.entry[14].resource!! as PractitionerRole).code[0].coding[0].display))
        assertTrue(stringMatch("http://snomed.info/sct", (obj.entry[14].resource!! as PractitionerRole).specialty[0].coding[0].system))
        assertTrue(stringMatch("9632001", (obj.entry[14].resource!! as PractitionerRole).specialty[0].coding[0].code))
        assertTrue(stringMatch("Nursing procedure", (obj.entry[14].resource!! as PractitionerRole).specialty[0].coding[0].display))
    }

    @Test
    fun `document-example-dischargesummary 395 Test`() {
        val json = File("./src/test/resources/model/sample_data/document-example-dischargesummary.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("Bundle", obj.resourceType))
        assertTrue(stringMatch("father", obj.id))
        assertEquals("2013-05-28T22:12:21Z", obj.meta!!.lastUpdated.toString())
        assertTrue(stringMatch("urn:ietf:rfc:3986", obj.identifier!!.system))
        assertTrue(stringMatch("urn:uuid:0c3151bd-1cbf-4d64-b", obj.identifier!!.value))
        assertTrue(stringMatch("document", obj.type))
        assertTrue(stringMatch("http://fhir.healthintersectio", obj.entry[0].fullUrl))
        assertTrue(stringMatch("Composition", (obj.entry[0].resource!! as Composition).resourceType))
        assertTrue(stringMatch("180f219f-97a8-486d-99d9-ed631", (obj.entry[0].resource!! as Composition).id))
        assertEquals("2013-05-28T22:12:21Z", (obj.entry[0].resource!! as Composition).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[0].resource!! as Composition).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[0].resource!! as Composition).text!!.div))
        assertTrue(stringMatch("final", (obj.entry[0].resource!! as Composition).status))
        assertTrue(stringMatch("http://loinc.org", (obj.entry[0].resource!! as Composition).type.coding[0].system))
        assertTrue(stringMatch("28655-9", (obj.entry[0].resource!! as Composition).type.coding[0].code))
        assertTrue(stringMatch("Discharge Summary from Respon", (obj.entry[0].resource!! as Composition).type.text))
        assertTrue(stringMatch("http://fhir.healthintersectio", (obj.entry[0].resource!! as Composition).subject.reference))
        assertTrue(stringMatch("Eve Everywoman", (obj.entry[0].resource!! as Composition).subject.display))
    }
}
