package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle13DataTest : DataTests() {
    @Test
    fun `practitioner-examples-general 377 Test`() {
        val json = File("./src/test/resources/model/sample_data/practitioner-examples-general.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("work", (obj.entry[42].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[42].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1049 Healthcare Drive", (obj.entry[42].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("male", (obj.entry[42].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[43].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[43].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("55", (obj.entry[43].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[43].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[43].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[43].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[43].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[43].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[43].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222665555", (obj.entry[43].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[43].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Helper", (obj.entry[43].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Horace", (obj.entry[43].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[43].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1052", (obj.entry[43].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[43].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[43].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1050 Healthcare Drive", (obj.entry[43].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("male", (obj.entry[43].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[44].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[44].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("56", (obj.entry[44].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[44].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[44].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[44].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[44].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[44].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[44].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222888888", (obj.entry[44].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[44].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Nightingale", (obj.entry[44].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Nancy", (obj.entry[44].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[44].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1014", (obj.entry[44].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[44].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[44].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1014 Healthcare Drive", (obj.entry[44].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("female", (obj.entry[44].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[45].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[45].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("57", (obj.entry[45].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[45].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[45].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[45].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[45].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[45].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[45].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222999999", (obj.entry[45].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[45].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Barton", (obj.entry[45].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Clarence", (obj.entry[45].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[45].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1015", (obj.entry[45].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[45].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[45].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1015 Healthcare Drive", (obj.entry[45].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("male", (obj.entry[45].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[46].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[46].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("58", (obj.entry[46].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[46].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[46].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[46].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[46].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[46].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[46].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222666666", (obj.entry[46].resource!! as Practitioner).identifier[0].value))
    }
}
