package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle52DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 423 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[19].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577409", (obj.entry[19].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[19].resource!! as Patient).active != null) (obj.entry[19].resource!! as Patient).active else false, "Field: (obj.entry[19].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[19].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Rodriguez", (obj.entry[19].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Christopher", (obj.entry[19].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[19].resource!! as Patient).gender))
        assertEquals("1943-09-07", (obj.entry[19].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[19].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/9", obj.entry[20].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[20].resource!! as Patient).resourceType))
        assertTrue(stringMatch("91", (obj.entry[20].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[20].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[20].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[20].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[20].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[20].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[20].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577410", (obj.entry[20].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[20].resource!! as Patient).active != null) (obj.entry[20].resource!! as Patient).active else false, "Field: (obj.entry[20].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[20].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Spencer", (obj.entry[20].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Dan", (obj.entry[20].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[20].resource!! as Patient).gender))
        assertEquals("1933-11-08", (obj.entry[20].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[20].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/9", obj.entry[21].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[21].resource!! as Patient).resourceType))
        assertTrue(stringMatch("92", (obj.entry[21].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[21].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[21].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[21].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[21].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[21].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[21].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577411", (obj.entry[21].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[21].resource!! as Patient).active != null) (obj.entry[21].resource!! as Patient).active else false, "Field: (obj.entry[21].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[21].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Cooper", (obj.entry[21].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Ron", (obj.entry[21].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[21].resource!! as Patient).gender))
        assertEquals("1942-06-22", (obj.entry[21].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[21].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/9", obj.entry[22].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[22].resource!! as Patient).resourceType))
        assertTrue(stringMatch("93", (obj.entry[22].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[22].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[22].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[22].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[22].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[22].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[22].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577412", (obj.entry[22].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[22].resource!! as Patient).active != null) (obj.entry[22].resource!! as Patient).active else false, "Field: (obj.entry[22].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[22].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Martin", (obj.entry[22].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Karen", (obj.entry[22].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[22].resource!! as Patient).gender))
        assertEquals("1950-01-24", (obj.entry[22].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[22].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/9", obj.entry[23].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[23].resource!! as Patient).resourceType))
        assertTrue(stringMatch("94", (obj.entry[23].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[23].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[23].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[23].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[23].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[23].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[23].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577413", (obj.entry[23].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[23].resource!! as Patient).active != null) (obj.entry[23].resource!! as Patient).active else false, "Field: (obj.entry[23].resource!! as Patient).active")
    }
}
