package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle16DataTest : DataTests() {
    @Test
    fun `practitioner-examples-general 380 Test`() {
        val json = File("./src/test/resources/model/sample_data/practitioner-examples-general.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[54].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[54].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("66", (obj.entry[54].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[54].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[54].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[54].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[54].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[54].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[54].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("333555555", (obj.entry[54].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[54].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Chow", (obj.entry[54].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Connie", (obj.entry[54].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[54].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1018", (obj.entry[54].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[54].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[54].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1018 Healthcare Drive", (obj.entry[54].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("female", (obj.entry[54].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[55].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[55].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("67", (obj.entry[55].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[55].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[55].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[55].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[55].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[55].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[55].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("000111111", (obj.entry[55].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[55].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Helper", (obj.entry[55].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Helen", (obj.entry[55].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[55].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1019", (obj.entry[55].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[55].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[55].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1019 Healthcare Drive", (obj.entry[55].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("female", (obj.entry[55].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[56].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[56].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("68", (obj.entry[56].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[56].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[56].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[56].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[56].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[56].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[56].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222776666", (obj.entry[56].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[56].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Player", (obj.entry[56].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Pamela", (obj.entry[56].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[56].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1059", (obj.entry[56].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[56].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[56].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1057 Healthcare Drive", (obj.entry[56].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("female", (obj.entry[56].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[57].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[57].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("69", (obj.entry[57].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[57].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[57].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[57].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[57].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[57].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[57].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222778888", (obj.entry[57].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[57].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Stretcher", (obj.entry[57].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Seth", (obj.entry[57].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[57].resource!! as Practitioner).telecom[0].system))
    }
}
