package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle38DataTest : DataTests() {
    @Test
    fun `questionnaire-profile-example-ussg-fht 407 Test`() {
        val json = File("./src/test/resources/model/sample_data/questionnaire-profile-example-ussg-fht.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("Other/Unknown/Refuse To Answe", (obj.entry[5].resource!! as ValueSet).compose!!.include[0].concept[17].display))
        assertTrue(stringMatch("PUT", obj.entry[5].request!!.method))
        assertTrue(stringMatch("http://hl7.org/fhir/us/sdc/Va", obj.entry[5].request!!.url))
        assertTrue(stringMatch("http://hl7.org/fhir/us/sdc/Va", obj.entry[6].fullUrl))
        assertTrue(stringMatch("ValueSet", (obj.entry[6].resource!! as ValueSet).resourceType))
        assertTrue(stringMatch("LL628-9", (obj.entry[6].resource!! as ValueSet).id))
        assertTrue(stringMatch("http://hl7.org/fhir/us/sdc/St", (obj.entry[6].resource!! as ValueSet).meta!!.profile[0]))
        assertTrue(stringMatch("generated", (obj.entry[6].resource!! as ValueSet).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[6].resource!! as ValueSet).text!!.div))
        assertTrue(stringMatch("http://details.loinc.org/Answ", (obj.entry[6].resource!! as ValueSet).url))
        assertTrue(stringMatch("USSG-FHT ethnicity", (obj.entry[6].resource!! as ValueSet).name))
        assertTrue(stringMatch("active", (obj.entry[6].resource!! as ValueSet).status))
        assertTrue(stringMatch("Regenstrief Institute, Inc an", (obj.entry[6].resource!! as ValueSet).publisher))
        assertTrue(stringMatch("Family history tool ethnicity", (obj.entry[6].resource!! as ValueSet).description))
        assertEquals(true, if ((obj.entry[6].resource!! as ValueSet).immutable != null) (obj.entry[6].resource!! as ValueSet).immutable else false, "Field: (obj.entry[6].resource!! as ValueSet).immutable")
        assertTrue(stringMatch("Refer to https://loinc.org/te", (obj.entry[6].resource!! as ValueSet).copyright))
        assertEquals(false, if ((obj.entry[6].resource!! as ValueSet).extensible != null) (obj.entry[6].resource!! as ValueSet).extensible else false, "Field: (obj.entry[6].resource!! as ValueSet).extensible")
        assertTrue(stringMatch("http://loinc.org", (obj.entry[6].resource!! as ValueSet).compose!!.include[0].system))
        assertTrue(stringMatch("LA6214-6", (obj.entry[6].resource!! as ValueSet).compose!!.include[0].concept[0].code))
        assertTrue(stringMatch("Hispanic or Latino", (obj.entry[6].resource!! as ValueSet).compose!!.include[0].concept[0].display))
        assertTrue(stringMatch("LA10599-1", (obj.entry[6].resource!! as ValueSet).compose!!.include[0].concept[1].code))
        assertTrue(stringMatch("-- Central American", (obj.entry[6].resource!! as ValueSet).compose!!.include[0].concept[1].display))
        assertTrue(stringMatch("LA10600-7", (obj.entry[6].resource!! as ValueSet).compose!!.include[0].concept[2].code))
        assertTrue(stringMatch("-- Cuban", (obj.entry[6].resource!! as ValueSet).compose!!.include[0].concept[2].display))
        assertTrue(stringMatch("LA10601-5", (obj.entry[6].resource!! as ValueSet).compose!!.include[0].concept[3].code))
        assertTrue(stringMatch("-- Dominican(Republic)", (obj.entry[6].resource!! as ValueSet).compose!!.include[0].concept[3].display))
        assertTrue(stringMatch("LA10602-3", (obj.entry[6].resource!! as ValueSet).compose!!.include[0].concept[4].code))
        assertTrue(stringMatch("-- Mexican", (obj.entry[6].resource!! as ValueSet).compose!!.include[0].concept[4].display))
        assertTrue(stringMatch("LA10605-6", (obj.entry[6].resource!! as ValueSet).compose!!.include[0].concept[5].code))
        assertTrue(stringMatch("-- Puerto Rican", (obj.entry[6].resource!! as ValueSet).compose!!.include[0].concept[5].display))
        assertTrue(stringMatch("LA10606-4", (obj.entry[6].resource!! as ValueSet).compose!!.include[0].concept[6].code))
        assertTrue(stringMatch("-- South American", (obj.entry[6].resource!! as ValueSet).compose!!.include[0].concept[6].display))
        assertTrue(stringMatch("LA10604-9", (obj.entry[6].resource!! as ValueSet).compose!!.include[0].concept[7].code))
        assertTrue(stringMatch("-- Other Latin American", (obj.entry[6].resource!! as ValueSet).compose!!.include[0].concept[7].display))
        assertTrue(stringMatch("LA10603-1", (obj.entry[6].resource!! as ValueSet).compose!!.include[0].concept[8].code))
        assertTrue(stringMatch("-- Other Hispanic/Latino/Span", (obj.entry[6].resource!! as ValueSet).compose!!.include[0].concept[8].display))
        assertTrue(stringMatch("LA10597-5", (obj.entry[6].resource!! as ValueSet).compose!!.include[0].concept[9].code))
        assertTrue(stringMatch("Non-Hispanic or Latino", (obj.entry[6].resource!! as ValueSet).compose!!.include[0].concept[9].display))
        assertTrue(stringMatch("LA10598-3", (obj.entry[6].resource!! as ValueSet).compose!!.include[0].concept[10].code))
        assertTrue(stringMatch("Ashkenazi Jewish", (obj.entry[6].resource!! as ValueSet).compose!!.include[0].concept[10].display))
        assertTrue(stringMatch("LA10607-2", (obj.entry[6].resource!! as ValueSet).compose!!.include[0].concept[11].code))
        assertTrue(stringMatch("Unknown/No answer", (obj.entry[6].resource!! as ValueSet).compose!!.include[0].concept[11].display))
        assertTrue(stringMatch("PUT", obj.entry[6].request!!.method))
        assertTrue(stringMatch("http://hl7.org/fhir/us/sdc/Va", obj.entry[6].request!!.url))
        assertTrue(stringMatch("http://hl7.org/fhir/us/sdc/Va", obj.entry[7].fullUrl))
        assertTrue(stringMatch("ValueSet", (obj.entry[7].resource!! as ValueSet).resourceType))
        assertTrue(stringMatch("LL626-3", (obj.entry[7].resource!! as ValueSet).id))
        assertTrue(stringMatch("http://hl7.org/fhir/us/sdc/St", (obj.entry[7].resource!! as ValueSet).meta!!.profile[0]))
        assertTrue(stringMatch("generated", (obj.entry[7].resource!! as ValueSet).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[7].resource!! as ValueSet).text!!.div))
        assertTrue(stringMatch("http://details.loinc.org/Answ", (obj.entry[7].resource!! as ValueSet).url))
        assertTrue(stringMatch("USSG-FHT diseases", (obj.entry[7].resource!! as ValueSet).name))
        assertTrue(stringMatch("active", (obj.entry[7].resource!! as ValueSet).status))
        assertTrue(stringMatch("Regenstrief Institute, Inc an", (obj.entry[7].resource!! as ValueSet).publisher))
        assertTrue(stringMatch("Family history tool diseases", (obj.entry[7].resource!! as ValueSet).description))
        assertEquals(true, if ((obj.entry[7].resource!! as ValueSet).immutable != null) (obj.entry[7].resource!! as ValueSet).immutable else false, "Field: (obj.entry[7].resource!! as ValueSet).immutable")
        assertTrue(stringMatch("Refer to https://loinc.org/te", (obj.entry[7].resource!! as ValueSet).copyright))
        assertEquals(false, if ((obj.entry[7].resource!! as ValueSet).extensible != null) (obj.entry[7].resource!! as ValueSet).extensible else false, "Field: (obj.entry[7].resource!! as ValueSet).extensible")
        assertTrue(stringMatch("http://loinc.org", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].system))
        assertTrue(stringMatch("LA10533-0", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[0].code))
        assertTrue(stringMatch("Blood Clots", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[0].display))
        assertTrue(stringMatch("LA10572-8", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[1].code))
        assertTrue(stringMatch("-- Blood Clot in Leg", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[1].display))
        assertTrue(stringMatch("LA10573-6", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[2].code))
        assertTrue(stringMatch("-- Blood Clot in Lungs", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[2].display))
        assertTrue(stringMatch("LA10524-9", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[3].code))
        assertTrue(stringMatch("Cancer", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[3].display))
        assertTrue(stringMatch("LA10549-6", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[4].code))
        assertTrue(stringMatch("-- Bone", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[4].display))
        assertTrue(stringMatch("LA10536-3", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[5].code))
        assertTrue(stringMatch("-- Breast Cancer", (obj.entry[7].resource!! as ValueSet).compose!!.include[0].concept[5].display))
    }
}
