package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle92DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 463 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("577576", (obj.entry[186].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[186].resource!! as Patient).active != null) (obj.entry[186].resource!! as Patient).active else false, "Field: (obj.entry[186].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[186].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("King", (obj.entry[186].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Paula", (obj.entry[186].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[186].resource!! as Patient).gender))
        assertEquals("1988-02-23", (obj.entry[186].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[186].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[187].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[187].resource!! as Patient).resourceType))
        assertTrue(stringMatch("258", (obj.entry[187].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[187].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[187].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[187].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[187].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[187].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[187].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577577", (obj.entry[187].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[187].resource!! as Patient).active != null) (obj.entry[187].resource!! as Patient).active else false, "Field: (obj.entry[187].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[187].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Phillips", (obj.entry[187].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Katherine", (obj.entry[187].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[187].resource!! as Patient).gender))
        assertEquals("1976-04-27", (obj.entry[187].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[187].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[188].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[188].resource!! as Patient).resourceType))
        assertTrue(stringMatch("259", (obj.entry[188].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[188].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[188].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[188].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[188].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[188].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[188].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577578", (obj.entry[188].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[188].resource!! as Patient).active != null) (obj.entry[188].resource!! as Patient).active else false, "Field: (obj.entry[188].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[188].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Boyd", (obj.entry[188].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Erika", (obj.entry[188].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[188].resource!! as Patient).gender))
        assertEquals("1986-07-03", (obj.entry[188].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[188].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[189].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[189].resource!! as Patient).resourceType))
        assertTrue(stringMatch("260", (obj.entry[189].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[189].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[189].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[189].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[189].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[189].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[189].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577579", (obj.entry[189].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[189].resource!! as Patient).active != null) (obj.entry[189].resource!! as Patient).active else false, "Field: (obj.entry[189].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[189].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Carpenter", (obj.entry[189].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Jamie", (obj.entry[189].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[189].resource!! as Patient).gender))
        assertEquals("1972-03-23", (obj.entry[189].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[189].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[190].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[190].resource!! as Patient).resourceType))
        assertTrue(stringMatch("261", (obj.entry[190].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[190].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[190].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[190].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[190].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[190].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[190].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577580", (obj.entry[190].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[190].resource!! as Patient).active != null) (obj.entry[190].resource!! as Patient).active else false, "Field: (obj.entry[190].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[190].resource!! as Patient).name[0].use))
    }
}
