package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle99DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 470 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("Tiffany", (obj.entry[215].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[215].resource!! as Patient).gender))
        assertEquals("1956-10-28", (obj.entry[215].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[215].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[216].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[216].resource!! as Patient).resourceType))
        assertTrue(stringMatch("287", (obj.entry[216].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[216].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[216].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[216].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[216].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[216].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[216].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577606", (obj.entry[216].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[216].resource!! as Patient).active != null) (obj.entry[216].resource!! as Patient).active else false, "Field: (obj.entry[216].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[216].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Hart", (obj.entry[216].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Bessie", (obj.entry[216].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[216].resource!! as Patient).gender))
        assertEquals("1985-12-25", (obj.entry[216].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[216].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[217].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[217].resource!! as Patient).resourceType))
        assertTrue(stringMatch("288", (obj.entry[217].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[217].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[217].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[217].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[217].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[217].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[217].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577607", (obj.entry[217].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[217].resource!! as Patient).active != null) (obj.entry[217].resource!! as Patient).active else false, "Field: (obj.entry[217].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[217].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Curry", (obj.entry[217].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Francis", (obj.entry[217].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[217].resource!! as Patient).gender))
        assertEquals("1975-01-28", (obj.entry[217].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[217].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[218].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[218].resource!! as Patient).resourceType))
        assertTrue(stringMatch("289", (obj.entry[218].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[218].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[218].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[218].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[218].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[218].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[218].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577608", (obj.entry[218].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[218].resource!! as Patient).active != null) (obj.entry[218].resource!! as Patient).active else false, "Field: (obj.entry[218].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[218].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Hawkins", (obj.entry[218].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Kent", (obj.entry[218].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[218].resource!! as Patient).gender))
        assertEquals("1979-04-03", (obj.entry[218].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[218].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[219].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[219].resource!! as Patient).resourceType))
        assertTrue(stringMatch("290", (obj.entry[219].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[219].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[219].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[219].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[219].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[219].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[219].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577609", (obj.entry[219].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[219].resource!! as Patient).active != null) (obj.entry[219].resource!! as Patient).active else false, "Field: (obj.entry[219].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[219].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Lyons", (obj.entry[219].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Christian", (obj.entry[219].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[219].resource!! as Patient).gender))
        assertEquals("1975-12-01", (obj.entry[219].resource!! as Patient).birthDate.toString())
    }
}
