package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle64DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 435 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertEquals(true, if ((obj.entry[69].resource!! as Patient).active != null) (obj.entry[69].resource!! as Patient).active else false, "Field: (obj.entry[69].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[69].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Hughes", (obj.entry[69].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Mae", (obj.entry[69].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[69].resource!! as Patient).gender))
        assertEquals("1958-05-14", (obj.entry[69].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[69].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[70].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[70].resource!! as Patient).resourceType))
        assertTrue(stringMatch("141", (obj.entry[70].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[70].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[70].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[70].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[70].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[70].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[70].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577460", (obj.entry[70].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[70].resource!! as Patient).active != null) (obj.entry[70].resource!! as Patient).active else false, "Field: (obj.entry[70].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[70].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Rice", (obj.entry[70].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Loretta", (obj.entry[70].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[70].resource!! as Patient).gender))
        assertEquals("1952-08-19", (obj.entry[70].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[70].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[71].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[71].resource!! as Patient).resourceType))
        assertTrue(stringMatch("142", (obj.entry[71].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[71].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[71].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[71].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[71].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[71].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[71].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577461", (obj.entry[71].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[71].resource!! as Patient).active != null) (obj.entry[71].resource!! as Patient).active else false, "Field: (obj.entry[71].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[71].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Reese", (obj.entry[71].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Naomi", (obj.entry[71].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[71].resource!! as Patient).gender))
        assertEquals("1996-03-31", (obj.entry[71].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[71].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[72].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[72].resource!! as Patient).resourceType))
        assertTrue(stringMatch("143", (obj.entry[72].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[72].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[72].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[72].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[72].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[72].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[72].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577462", (obj.entry[72].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[72].resource!! as Patient).active != null) (obj.entry[72].resource!! as Patient).active else false, "Field: (obj.entry[72].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[72].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Cox", (obj.entry[72].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Jesse", (obj.entry[72].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[72].resource!! as Patient).gender))
        assertEquals("1993-12-02", (obj.entry[72].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[72].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[73].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[73].resource!! as Patient).resourceType))
        assertTrue(stringMatch("144", (obj.entry[73].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[73].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[73].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[73].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[73].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[73].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[73].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577463", (obj.entry[73].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[73].resource!! as Patient).active != null) (obj.entry[73].resource!! as Patient).active else false, "Field: (obj.entry[73].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[73].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Mccoy", (obj.entry[73].resource!! as Patient).name[0].family))
    }
}
