package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle5DataTest : DataTests() {
    @Test
    fun `practitioner-examples-general 369 Test`() {
        val json = File("./src/test/resources/model/sample_data/practitioner-examples-general.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("1009 Healthcare Drive", (obj.entry[12].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("female", (obj.entry[12].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[13].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[13].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("25", (obj.entry[13].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[13].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[13].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[13].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[13].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[13].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[13].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222223333", (obj.entry[13].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[13].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Reaction", (obj.entry[13].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Ramsey", (obj.entry[13].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[13].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1025", (obj.entry[13].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[13].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[13].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1024 Healthcare Drive", (obj.entry[13].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("male", (obj.entry[13].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[14].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[14].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("26", (obj.entry[14].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[14].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[14].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[14].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[14].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[14].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[14].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222666666", (obj.entry[14].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[14].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Sleeper", (obj.entry[14].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Sally", (obj.entry[14].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[14].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1012", (obj.entry[14].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[14].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[14].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1012 Healthcare Drive", (obj.entry[14].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("female", (obj.entry[14].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[15].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[15].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("27", (obj.entry[15].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[15].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[15].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[15].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[15].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[15].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[15].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222334444", (obj.entry[15].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[15].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Pump", (obj.entry[15].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Patrick", (obj.entry[15].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[15].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1027", (obj.entry[15].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[15].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[15].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1025 Healthcare Drive", (obj.entry[15].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("male", (obj.entry[15].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[16].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[16].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("28", (obj.entry[16].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[16].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[16].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[16].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[16].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[16].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[16].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222335555", (obj.entry[16].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[16].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Valve", (obj.entry[16].resource!! as Practitioner).name[0].family))
    }
}
