package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle9DataTest : DataTests() {
    @Test
    fun `practitioner-examples-general 373 Test`() {
        val json = File("./src/test/resources/model/sample_data/practitioner-examples-general.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("home", (obj.entry[27].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1037 Healthcare Drive", (obj.entry[27].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("male", (obj.entry[27].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[28].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[28].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("40", (obj.entry[28].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[28].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[28].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[28].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[28].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[28].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[28].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222449999", (obj.entry[28].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[28].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Cranium", (obj.entry[28].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Carol", (obj.entry[28].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[28].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1040", (obj.entry[28].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[28].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[28].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1038 Healthcare Drive", (obj.entry[28].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("female", (obj.entry[28].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[29].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[29].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("41", (obj.entry[29].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[29].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[29].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[29].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[29].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[29].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[29].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222552222", (obj.entry[29].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[29].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Fem", (obj.entry[29].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Flora", (obj.entry[29].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[29].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1041", (obj.entry[29].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[29].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[29].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1039 Healthcare Drive", (obj.entry[29].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("female", (obj.entry[29].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[30].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[30].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("42", (obj.entry[30].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[30].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[30].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[30].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[30].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[30].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[30].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222553333", (obj.entry[30].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[30].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Tumor", (obj.entry[30].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Trudy", (obj.entry[30].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[30].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-2003", (obj.entry[30].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[30].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[30].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1040 Healthcare Drive", (obj.entry[30].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("female", (obj.entry[30].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[31].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[31].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("43", (obj.entry[31].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[31].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[31].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[31].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[31].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[31].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[31].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222554444", (obj.entry[31].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[31].resource!! as Practitioner).name[0].use))
    }
}
