package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle82DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 453 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("Lawrence", (obj.entry[144].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[144].resource!! as Patient).gender))
        assertEquals("1942-10-18", (obj.entry[144].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[144].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[145].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[145].resource!! as Patient).resourceType))
        assertTrue(stringMatch("216", (obj.entry[145].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[145].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[145].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[145].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[145].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[145].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[145].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577535", (obj.entry[145].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[145].resource!! as Patient).active != null) (obj.entry[145].resource!! as Patient).active else false, "Field: (obj.entry[145].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[145].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Mcdaniel", (obj.entry[145].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Pedro", (obj.entry[145].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[145].resource!! as Patient).gender))
        assertEquals("1939-06-28", (obj.entry[145].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[145].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[146].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[146].resource!! as Patient).resourceType))
        assertTrue(stringMatch("217", (obj.entry[146].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[146].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[146].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[146].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[146].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[146].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[146].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577536", (obj.entry[146].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[146].resource!! as Patient).active != null) (obj.entry[146].resource!! as Patient).active else false, "Field: (obj.entry[146].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[146].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Barnes", (obj.entry[146].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Mario", (obj.entry[146].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[146].resource!! as Patient).gender))
        assertEquals("1952-09-08", (obj.entry[146].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[146].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[147].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[147].resource!! as Patient).resourceType))
        assertTrue(stringMatch("218", (obj.entry[147].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[147].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[147].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[147].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[147].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[147].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[147].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577537", (obj.entry[147].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[147].resource!! as Patient).active != null) (obj.entry[147].resource!! as Patient).active else false, "Field: (obj.entry[147].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[147].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Carter", (obj.entry[147].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Karen", (obj.entry[147].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[147].resource!! as Patient).gender))
        assertEquals("1953-06-03", (obj.entry[147].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[147].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[148].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[148].resource!! as Patient).resourceType))
        assertTrue(stringMatch("219", (obj.entry[148].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[148].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[148].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[148].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[148].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[148].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[148].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577538", (obj.entry[148].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[148].resource!! as Patient).active != null) (obj.entry[148].resource!! as Patient).active else false, "Field: (obj.entry[148].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[148].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Moore", (obj.entry[148].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Robin", (obj.entry[148].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[148].resource!! as Patient).gender))
        assertEquals("1954-01-20", (obj.entry[148].resource!! as Patient).birthDate.toString())
    }
}
