package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle58DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 429 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("577434", (obj.entry[44].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[44].resource!! as Patient).active != null) (obj.entry[44].resource!! as Patient).active else false, "Field: (obj.entry[44].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[44].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Fleming", (obj.entry[44].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Christopher", (obj.entry[44].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[44].resource!! as Patient).gender))
        assertEquals("1939-03-08", (obj.entry[44].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[44].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[45].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[45].resource!! as Patient).resourceType))
        assertTrue(stringMatch("116", (obj.entry[45].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[45].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[45].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[45].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[45].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[45].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[45].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577435", (obj.entry[45].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[45].resource!! as Patient).active != null) (obj.entry[45].resource!! as Patient).active else false, "Field: (obj.entry[45].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[45].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Marshall", (obj.entry[45].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Howard", (obj.entry[45].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[45].resource!! as Patient).gender))
        assertEquals("1960-06-08", (obj.entry[45].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[45].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[46].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[46].resource!! as Patient).resourceType))
        assertTrue(stringMatch("117", (obj.entry[46].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[46].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[46].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[46].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[46].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[46].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[46].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577436", (obj.entry[46].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[46].resource!! as Patient).active != null) (obj.entry[46].resource!! as Patient).active else false, "Field: (obj.entry[46].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[46].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Larson", (obj.entry[46].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Erika", (obj.entry[46].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[46].resource!! as Patient).gender))
        assertEquals("1935-06-05", (obj.entry[46].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[46].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[47].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[47].resource!! as Patient).resourceType))
        assertTrue(stringMatch("118", (obj.entry[47].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[47].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[47].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[47].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[47].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[47].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[47].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577437", (obj.entry[47].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[47].resource!! as Patient).active != null) (obj.entry[47].resource!! as Patient).active else false, "Field: (obj.entry[47].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[47].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Day", (obj.entry[47].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Carol", (obj.entry[47].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[47].resource!! as Patient).gender))
        assertEquals("1963-06-08", (obj.entry[47].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[47].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[48].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[48].resource!! as Patient).resourceType))
        assertTrue(stringMatch("119", (obj.entry[48].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[48].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[48].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[48].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[48].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[48].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[48].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577438", (obj.entry[48].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[48].resource!! as Patient).active != null) (obj.entry[48].resource!! as Patient).active else false, "Field: (obj.entry[48].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[48].resource!! as Patient).name[0].use))
    }
}
