package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle50DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 421 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("82", (obj.entry[11].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[11].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[11].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[11].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[11].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[11].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[11].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577401", (obj.entry[11].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[11].resource!! as Patient).active != null) (obj.entry[11].resource!! as Patient).active else false, "Field: (obj.entry[11].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[11].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Rivera", (obj.entry[11].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Christine", (obj.entry[11].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[11].resource!! as Patient).gender))
        assertEquals("1950-01-13", (obj.entry[11].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[11].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/8", obj.entry[12].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[12].resource!! as Patient).resourceType))
        assertTrue(stringMatch("83", (obj.entry[12].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[12].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[12].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[12].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[12].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[12].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[12].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577402", (obj.entry[12].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[12].resource!! as Patient).active != null) (obj.entry[12].resource!! as Patient).active else false, "Field: (obj.entry[12].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[12].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Ryan", (obj.entry[12].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Olga", (obj.entry[12].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[12].resource!! as Patient).gender))
        assertEquals("1945-04-06", (obj.entry[12].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[12].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/8", obj.entry[13].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[13].resource!! as Patient).resourceType))
        assertTrue(stringMatch("84", (obj.entry[13].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[13].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[13].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[13].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[13].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[13].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[13].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577403", (obj.entry[13].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[13].resource!! as Patient).active != null) (obj.entry[13].resource!! as Patient).active else false, "Field: (obj.entry[13].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[13].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Price", (obj.entry[13].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Melanie", (obj.entry[13].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[13].resource!! as Patient).gender))
        assertEquals("1969-04-06", (obj.entry[13].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[13].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/8", obj.entry[14].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[14].resource!! as Patient).resourceType))
        assertTrue(stringMatch("85", (obj.entry[14].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[14].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[14].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[14].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[14].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[14].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[14].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577404", (obj.entry[14].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[14].resource!! as Patient).active != null) (obj.entry[14].resource!! as Patient).active else false, "Field: (obj.entry[14].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[14].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Collier", (obj.entry[14].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Shelly", (obj.entry[14].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[14].resource!! as Patient).gender))
        assertEquals("1953-09-14", (obj.entry[14].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[14].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/8", obj.entry[15].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[15].resource!! as Patient).resourceType))
        assertTrue(stringMatch("86", (obj.entry[15].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[15].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[15].resource!! as Patient).text!!.status))
    }
}
