package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle10DataTest : DataTests() {
    @Test
    fun `practitioner-examples-general 374 Test`() {
        val json = File("./src/test/resources/model/sample_data/practitioner-examples-general.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("Vision", (obj.entry[31].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Victor", (obj.entry[31].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[31].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1043", (obj.entry[31].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[31].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[31].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1041 Healthcare Drive", (obj.entry[31].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("male", (obj.entry[31].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[32].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[32].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("44", (obj.entry[32].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[32].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[32].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[32].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[32].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[32].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[32].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222555545", (obj.entry[32].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[32].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Carpenter", (obj.entry[32].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Calvin", (obj.entry[32].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[32].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1044", (obj.entry[32].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[32].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[32].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1042 Healthcare Drive", (obj.entry[32].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("male", (obj.entry[32].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[33].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[33].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("45", (obj.entry[33].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[33].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[33].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[33].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[33].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[33].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[33].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222556666", (obj.entry[33].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[33].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Rhino", (obj.entry[33].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Rick", (obj.entry[33].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[33].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1045", (obj.entry[33].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[33].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[33].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1043 Healthcare Drive", (obj.entry[33].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("male", (obj.entry[33].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[34].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[34].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("46", (obj.entry[34].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[34].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[34].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[34].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[34].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[34].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[34].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222444444", (obj.entry[34].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[34].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Slide", (obj.entry[34].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Stan", (obj.entry[34].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[34].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1010", (obj.entry[34].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[34].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[34].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1010 Healthcare Drive", (obj.entry[34].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("male", (obj.entry[34].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[35].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[35].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("47", (obj.entry[35].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[35].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[35].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[35].resource!! as Practitioner).text!!.div))
    }
}
