package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle202DataTest : DataTests() {
    @Test
    fun `patient-examples-general 576 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-general.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[9].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[9].resource!! as Patient).resourceType))
        assertTrue(stringMatch("10", (obj.entry[9].resource!! as Patient).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[9].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[9].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[9].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[9].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[9].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[9].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("444888888", (obj.entry[9].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[9].resource!! as Patient).active != null) (obj.entry[9].resource!! as Patient).active else false, "Field: (obj.entry[9].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[9].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Betterhalf", (obj.entry[9].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Boris", (obj.entry[9].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[9].resource!! as Patient).telecom[0].system))
        assertTrue(stringMatch("555-555-2008", (obj.entry[9].resource!! as Patient).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[9].resource!! as Patient).telecom[0].use))
        assertTrue(stringMatch("male", (obj.entry[9].resource!! as Patient).gender))
        assertTrue(stringMatch("home", (obj.entry[9].resource!! as Patient).address[0].use))
        assertTrue(stringMatch("2222 Home Street", (obj.entry[9].resource!! as Patient).address[0].line[0]))
        assertTrue(stringMatch("Organization/hl7", (obj.entry[9].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[10].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[10].resource!! as Patient).resourceType))
        assertTrue(stringMatch("11", (obj.entry[10].resource!! as Patient).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[10].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[10].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[10].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[10].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[10].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[10].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("444999999", (obj.entry[10].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[10].resource!! as Patient).active != null) (obj.entry[10].resource!! as Patient).active else false, "Field: (obj.entry[10].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[10].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Relative", (obj.entry[10].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Ralph", (obj.entry[10].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[10].resource!! as Patient).telecom[0].system))
        assertTrue(stringMatch("555-555-2009", (obj.entry[10].resource!! as Patient).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[10].resource!! as Patient).telecom[0].use))
        assertTrue(stringMatch("male", (obj.entry[10].resource!! as Patient).gender))
        assertTrue(stringMatch("home", (obj.entry[10].resource!! as Patient).address[0].use))
        assertTrue(stringMatch("4444 Home Street", (obj.entry[10].resource!! as Patient).address[0].line[0]))
        assertTrue(stringMatch("Organization/hl7", (obj.entry[10].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[11].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[11].resource!! as Patient).resourceType))
        assertTrue(stringMatch("12", (obj.entry[11].resource!! as Patient).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[11].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[11].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[11].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[11].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[11].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[11].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("555222222", (obj.entry[11].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[11].resource!! as Patient).active != null) (obj.entry[11].resource!! as Patient).active else false, "Field: (obj.entry[11].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[11].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Contact", (obj.entry[11].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Carrie", (obj.entry[11].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[11].resource!! as Patient).telecom[0].system))
        assertTrue(stringMatch("555-555-2010", (obj.entry[11].resource!! as Patient).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[11].resource!! as Patient).telecom[0].use))
        assertTrue(stringMatch("female", (obj.entry[11].resource!! as Patient).gender))
        assertTrue(stringMatch("home", (obj.entry[11].resource!! as Patient).address[0].use))
        assertTrue(stringMatch("5555 Home Street", (obj.entry[11].resource!! as Patient).address[0].line[0]))
        assertTrue(stringMatch("Organization/hl7", (obj.entry[11].resource!! as Patient).managingOrganization!!.reference))
    }
}
