package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle46DataTest : DataTests() {
    @Test
    fun `endpoint-examples-general-template 416 Test`() {
        val json = File("./src/test/resources/model/sample_data/endpoint-examples-general-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("http://hl7.org/fhir/Endpoint/", obj.entry[7].fullUrl))
        assertTrue(stringMatch("Endpoint", (obj.entry[7].resource!! as Endpoint).resourceType))
        assertTrue(stringMatch("78", (obj.entry[7].resource!! as Endpoint).id))
        assertTrue(stringMatch("generated", (obj.entry[7].resource!! as Endpoint).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[7].resource!! as Endpoint).text!!.div))
        assertTrue(stringMatch("active", (obj.entry[7].resource!! as Endpoint).status))
        assertTrue(stringMatch("http://hl7.org/fhir/endpoint-", (obj.entry[7].resource!! as Endpoint).connectionType.system))
        assertTrue(stringMatch("ihe-xds", (obj.entry[7].resource!! as Endpoint).connectionType.code))
        assertTrue(stringMatch("xds event summaries", (obj.entry[7].resource!! as Endpoint).name))
        assertTrue(stringMatch("Epic demo organization", (obj.entry[7].resource!! as Endpoint).managingOrganization!!.display))
        assertTrue(stringMatch("CDA-EventSummary", (obj.entry[7].resource!! as Endpoint).payloadType[0].coding[0].code))
        assertTrue(stringMatch("XDA/XDS", (obj.entry[7].resource!! as Endpoint).payloadMimeType[0]))
        assertTrue(stringMatch("https://open.epic.com/Interfa", (obj.entry[7].resource!! as Endpoint).address))
        assertTrue(stringMatch("http://hl7.org/fhir/Endpoint/", obj.entry[8].fullUrl))
        assertTrue(stringMatch("Endpoint", (obj.entry[8].resource!! as Endpoint).resourceType))
        assertTrue(stringMatch("79", (obj.entry[8].resource!! as Endpoint).id))
        assertTrue(stringMatch("generated", (obj.entry[8].resource!! as Endpoint).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[8].resource!! as Endpoint).text!!.div))
        assertTrue(stringMatch("active", (obj.entry[8].resource!! as Endpoint).status))
        assertTrue(stringMatch("http://hl7.org/fhir/endpoint-", (obj.entry[8].resource!! as Endpoint).connectionType.system))
        assertTrue(stringMatch("dicom-wado-rs", (obj.entry[8].resource!! as Endpoint).connectionType.code))
        assertTrue(stringMatch("Enterprise Image Archive", (obj.entry[8].resource!! as Endpoint).name))
        assertTrue(stringMatch("Multi-site Co.", (obj.entry[8].resource!! as Endpoint).managingOrganization!!.display))
        assertTrue(stringMatch("varies (application/dicom, ap", (obj.entry[8].resource!! as Endpoint).payloadType[0].coding[0].code))
        assertTrue(stringMatch("DICOM WADO-RS", (obj.entry[8].resource!! as Endpoint).payloadMimeType[0]))
        assertTrue(stringMatch("https://pacs.hospital.org/dic", (obj.entry[8].resource!! as Endpoint).address))
        assertTrue(stringMatch("http://hl7.org/fhir/Endpoint/", obj.entry[9].fullUrl))
        assertTrue(stringMatch("Endpoint", (obj.entry[9].resource!! as Endpoint).resourceType))
        assertTrue(stringMatch("80", (obj.entry[9].resource!! as Endpoint).id))
        assertTrue(stringMatch("generated", (obj.entry[9].resource!! as Endpoint).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[9].resource!! as Endpoint).text!!.div))
        assertTrue(stringMatch("active", (obj.entry[9].resource!! as Endpoint).status))
        assertTrue(stringMatch("http://hl7.org/fhir/endpoint-", (obj.entry[9].resource!! as Endpoint).connectionType.system))
        assertTrue(stringMatch("dicom-qido-rs", (obj.entry[9].resource!! as Endpoint).connectionType.code))
        assertTrue(stringMatch("Enterprise Image Archive", (obj.entry[9].resource!! as Endpoint).name))
        assertTrue(stringMatch("Multi-site Co.", (obj.entry[9].resource!! as Endpoint).managingOrganization!!.display))
        assertTrue(stringMatch("varies (application/dicom, ap", (obj.entry[9].resource!! as Endpoint).payloadType[0].coding[0].code))
        assertTrue(stringMatch("DICOM QIDO-RS", (obj.entry[9].resource!! as Endpoint).payloadMimeType[0]))
        assertTrue(stringMatch("https://pacs.hospital.org/dic", (obj.entry[9].resource!! as Endpoint).address))
        assertTrue(stringMatch("http://hl7.org/fhir/Endpoint/", obj.entry[10].fullUrl))
        assertTrue(stringMatch("Endpoint", (obj.entry[10].resource!! as Endpoint).resourceType))
        assertTrue(stringMatch("81", (obj.entry[10].resource!! as Endpoint).id))
        assertTrue(stringMatch("generated", (obj.entry[10].resource!! as Endpoint).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[10].resource!! as Endpoint).text!!.div))
        assertTrue(stringMatch("active", (obj.entry[10].resource!! as Endpoint).status))
        assertTrue(stringMatch("http://hl7.org/fhir/endpoint-", (obj.entry[10].resource!! as Endpoint).connectionType.system))
        assertTrue(stringMatch("dicom-stow-rs", (obj.entry[10].resource!! as Endpoint).connectionType.code))
        assertTrue(stringMatch("Enterprise Image Archive", (obj.entry[10].resource!! as Endpoint).name))
        assertTrue(stringMatch("Multi-site Co.", (obj.entry[10].resource!! as Endpoint).managingOrganization!!.display))
        assertTrue(stringMatch("varies (application/dicom, ap", (obj.entry[10].resource!! as Endpoint).payloadType[0].coding[0].code))
        assertTrue(stringMatch("DICOM STOW-RS", (obj.entry[10].resource!! as Endpoint).payloadMimeType[0]))
        assertTrue(stringMatch("https://pacs.hospital.org/dic", (obj.entry[10].resource!! as Endpoint).address))
        assertTrue(stringMatch("http://hl7.org/fhir/Endpoint/", obj.entry[11].fullUrl))
        assertTrue(stringMatch("Endpoint", (obj.entry[11].resource!! as Endpoint).resourceType))
        assertTrue(stringMatch("82", (obj.entry[11].resource!! as Endpoint).id))
        assertTrue(stringMatch("generated", (obj.entry[11].resource!! as Endpoint).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[11].resource!! as Endpoint).text!!.div))
        assertTrue(stringMatch("active", (obj.entry[11].resource!! as Endpoint).status))
        assertTrue(stringMatch("http://hl7.org/fhir/endpoint-", (obj.entry[11].resource!! as Endpoint).connectionType.system))
        assertTrue(stringMatch("dicom-stow-rs", (obj.entry[11].resource!! as Endpoint).connectionType.code))
        assertTrue(stringMatch("Enterprise Image Archive", (obj.entry[11].resource!! as Endpoint).name))
        assertTrue(stringMatch("Multi-site Co.", (obj.entry[11].resource!! as Endpoint).managingOrganization!!.display))
        assertTrue(stringMatch("varies (application/dicom, ap", (obj.entry[11].resource!! as Endpoint).payloadType[0].coding[0].code))
        assertTrue(stringMatch("DICOM STOW-RS", (obj.entry[11].resource!! as Endpoint).payloadMimeType[0]))
        assertTrue(stringMatch("https://pacs.hospital.org/dic", (obj.entry[11].resource!! as Endpoint).address))
        assertTrue(stringMatch("http://hl7.org/fhir/Endpoint/", obj.entry[12].fullUrl))
        assertTrue(stringMatch("Endpoint", (obj.entry[12].resource!! as Endpoint).resourceType))
        assertTrue(stringMatch("83", (obj.entry[12].resource!! as Endpoint).id))
        assertTrue(stringMatch("generated", (obj.entry[12].resource!! as Endpoint).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[12].resource!! as Endpoint).text!!.div))
        assertTrue(stringMatch("active", (obj.entry[12].resource!! as Endpoint).status))
    }
}
