package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle48DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 419 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("Derrick", (obj.entry[2].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[2].resource!! as Patient).gender))
        assertEquals("1938-09-19", (obj.entry[2].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[2].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/7", obj.entry[3].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[3].resource!! as Patient).resourceType))
        assertTrue(stringMatch("74", (obj.entry[3].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[3].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[3].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[3].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[3].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[3].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[3].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577393", (obj.entry[3].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[3].resource!! as Patient).active != null) (obj.entry[3].resource!! as Patient).active else false, "Field: (obj.entry[3].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[3].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Knight", (obj.entry[3].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Emily", (obj.entry[3].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[3].resource!! as Patient).gender))
        assertEquals("1938-09-19", (obj.entry[3].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[3].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/7", obj.entry[4].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[4].resource!! as Patient).resourceType))
        assertTrue(stringMatch("75", (obj.entry[4].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[4].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[4].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[4].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[4].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[4].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[4].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577394", (obj.entry[4].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[4].resource!! as Patient).active != null) (obj.entry[4].resource!! as Patient).active else false, "Field: (obj.entry[4].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[4].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Ward", (obj.entry[4].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Leah", (obj.entry[4].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[4].resource!! as Patient).gender))
        assertEquals("1975-07-18", (obj.entry[4].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[4].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/7", obj.entry[5].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[5].resource!! as Patient).resourceType))
        assertTrue(stringMatch("76", (obj.entry[5].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[5].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[5].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[5].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[5].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[5].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[5].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577395", (obj.entry[5].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[5].resource!! as Patient).active != null) (obj.entry[5].resource!! as Patient).active else false, "Field: (obj.entry[5].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[5].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Mckinney", (obj.entry[5].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Ross", (obj.entry[5].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[5].resource!! as Patient).gender))
        assertEquals("1975-01-28", (obj.entry[5].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[5].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/7", obj.entry[6].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[6].resource!! as Patient).resourceType))
        assertTrue(stringMatch("77", (obj.entry[6].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[6].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[6].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[6].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[6].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[6].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[6].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577396", (obj.entry[6].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[6].resource!! as Patient).active != null) (obj.entry[6].resource!! as Patient).active else false, "Field: (obj.entry[6].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[6].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Meyer", (obj.entry[6].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Lucille", (obj.entry[6].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[6].resource!! as Patient).gender))
        assertEquals("1991-12-25", (obj.entry[6].resource!! as Patient).birthDate.toString())
    }
}
