package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle197DataTest : DataTests() {
    @Test
    fun `diagnosticreport-examples-general 570 Test`() {
        val json = File("./src/test/resources/model/sample_data/diagnosticreport-examples-general.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("LVX", ((obj.entry[14].resource!! as DiagnosticReport).contained[13] as Observation).code.coding[0].code))
        assertTrue(stringMatch("LEVOFLOXACIN", ((obj.entry[14].resource!! as DiagnosticReport).contained[13] as Observation).code.coding[0].display))
        assertTrue(stringMatch("Patient/5", ((obj.entry[14].resource!! as DiagnosticReport).contained[13] as Observation).subject!!.reference))
        assertTrue(stringMatch("Organization/1832473e-2fe0-45", ((obj.entry[14].resource!! as DiagnosticReport).contained[13] as Observation).performer[0].reference))
        assertTrue(stringMatch("Acme Laboratory, Inc", ((obj.entry[14].resource!! as DiagnosticReport).contained[13] as Observation).performer[0].display))
        assertTrue(stringMatch("%.2f".format(0.25f), "%.2f".format(((obj.entry[14].resource!! as DiagnosticReport).contained[13] as Observation).valueQuantity!!.value)))
        assertTrue(stringMatch("<=", ((obj.entry[14].resource!! as DiagnosticReport).contained[13] as Observation).valueQuantity!!.comparator))
        assertTrue(stringMatch("U", ((obj.entry[14].resource!! as DiagnosticReport).contained[13] as Observation).valueQuantity!!.unit))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0078", ((obj.entry[14].resource!! as DiagnosticReport).contained[13] as Observation).interpretation!!.coding[0].system))
        assertTrue(stringMatch("S", ((obj.entry[14].resource!! as DiagnosticReport).contained[13] as Observation).interpretation!!.coding[0].code))
        assertTrue(stringMatch("Observation", ((obj.entry[14].resource!! as DiagnosticReport).contained[14] as Observation).resourceType))
        assertTrue(stringMatch("o15", ((obj.entry[14].resource!! as DiagnosticReport).contained[14] as Observation).id))
        assertTrue(stringMatch("final", ((obj.entry[14].resource!! as DiagnosticReport).contained[14] as Observation).status))
        assertTrue(stringMatch("http://example.org/local", ((obj.entry[14].resource!! as DiagnosticReport).contained[14] as Observation).code.coding[0].system))
        assertTrue(stringMatch("NIT", ((obj.entry[14].resource!! as DiagnosticReport).contained[14] as Observation).code.coding[0].code))
        assertTrue(stringMatch("NITROFURANTOIN", ((obj.entry[14].resource!! as DiagnosticReport).contained[14] as Observation).code.coding[0].display))
        assertTrue(stringMatch("Patient/5", ((obj.entry[14].resource!! as DiagnosticReport).contained[14] as Observation).subject!!.reference))
        assertTrue(stringMatch("Organization/1832473e-2fe0-45", ((obj.entry[14].resource!! as DiagnosticReport).contained[14] as Observation).performer[0].reference))
        assertTrue(stringMatch("Acme Laboratory, Inc", ((obj.entry[14].resource!! as DiagnosticReport).contained[14] as Observation).performer[0].display))
        assertTrue(stringMatch("%.2f".format(32f), "%.2f".format(((obj.entry[14].resource!! as DiagnosticReport).contained[14] as Observation).valueQuantity!!.value)))
        assertTrue(stringMatch("U", ((obj.entry[14].resource!! as DiagnosticReport).contained[14] as Observation).valueQuantity!!.unit))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0078", ((obj.entry[14].resource!! as DiagnosticReport).contained[14] as Observation).interpretation!!.coding[0].system))
        assertTrue(stringMatch("S", ((obj.entry[14].resource!! as DiagnosticReport).contained[14] as Observation).interpretation!!.coding[0].code))
        assertTrue(stringMatch("Observation", ((obj.entry[14].resource!! as DiagnosticReport).contained[15] as Observation).resourceType))
        assertTrue(stringMatch("o16", ((obj.entry[14].resource!! as DiagnosticReport).contained[15] as Observation).id))
        assertTrue(stringMatch("final", ((obj.entry[14].resource!! as DiagnosticReport).contained[15] as Observation).status))
        assertTrue(stringMatch("http://example.org/local", ((obj.entry[14].resource!! as DiagnosticReport).contained[15] as Observation).code.coding[0].system))
        assertTrue(stringMatch("PTZ", ((obj.entry[14].resource!! as DiagnosticReport).contained[15] as Observation).code.coding[0].code))
        assertTrue(stringMatch("PIPERACILLIN/TAZOBAC", ((obj.entry[14].resource!! as DiagnosticReport).contained[15] as Observation).code.coding[0].display))
        assertTrue(stringMatch("Patient/5", ((obj.entry[14].resource!! as DiagnosticReport).contained[15] as Observation).subject!!.reference))
        assertTrue(stringMatch("Organization/1832473e-2fe0-45", ((obj.entry[14].resource!! as DiagnosticReport).contained[15] as Observation).performer[0].reference))
        assertTrue(stringMatch("Acme Laboratory, Inc", ((obj.entry[14].resource!! as DiagnosticReport).contained[15] as Observation).performer[0].display))
        assertTrue(stringMatch("%.2f".format(4f), "%.2f".format(((obj.entry[14].resource!! as DiagnosticReport).contained[15] as Observation).valueQuantity!!.value)))
        assertTrue(stringMatch("<=", ((obj.entry[14].resource!! as DiagnosticReport).contained[15] as Observation).valueQuantity!!.comparator))
        assertTrue(stringMatch("U", ((obj.entry[14].resource!! as DiagnosticReport).contained[15] as Observation).valueQuantity!!.unit))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0078", ((obj.entry[14].resource!! as DiagnosticReport).contained[15] as Observation).interpretation!!.coding[0].system))
        assertTrue(stringMatch("S", ((obj.entry[14].resource!! as DiagnosticReport).contained[15] as Observation).interpretation!!.coding[0].code))
        assertTrue(stringMatch("Observation", ((obj.entry[14].resource!! as DiagnosticReport).contained[16] as Observation).resourceType))
        assertTrue(stringMatch("o17", ((obj.entry[14].resource!! as DiagnosticReport).contained[16] as Observation).id))
        assertTrue(stringMatch("final", ((obj.entry[14].resource!! as DiagnosticReport).contained[16] as Observation).status))
        assertTrue(stringMatch("http://example.org/local", ((obj.entry[14].resource!! as DiagnosticReport).contained[16] as Observation).code.coding[0].system))
        assertTrue(stringMatch("TRSUV", ((obj.entry[14].resource!! as DiagnosticReport).contained[16] as Observation).code.coding[0].code))
        assertTrue(stringMatch("TRIMETH/SULFA", ((obj.entry[14].resource!! as DiagnosticReport).contained[16] as Observation).code.coding[0].display))
        assertTrue(stringMatch("Patient/5", ((obj.entry[14].resource!! as DiagnosticReport).contained[16] as Observation).subject!!.reference))
        assertTrue(stringMatch("Organization/1832473e-2fe0-45", ((obj.entry[14].resource!! as DiagnosticReport).contained[16] as Observation).performer[0].reference))
        assertTrue(stringMatch("Acme Laboratory, Inc", ((obj.entry[14].resource!! as DiagnosticReport).contained[16] as Observation).performer[0].display))
        assertTrue(stringMatch("%.2f".format(20f), "%.2f".format(((obj.entry[14].resource!! as DiagnosticReport).contained[16] as Observation).valueQuantity!!.value)))
        assertTrue(stringMatch("<=", ((obj.entry[14].resource!! as DiagnosticReport).contained[16] as Observation).valueQuantity!!.comparator))
        assertTrue(stringMatch("U", ((obj.entry[14].resource!! as DiagnosticReport).contained[16] as Observation).valueQuantity!!.unit))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0078", ((obj.entry[14].resource!! as DiagnosticReport).contained[16] as Observation).interpretation!!.coding[0].system))
        assertTrue(stringMatch("S", ((obj.entry[14].resource!! as DiagnosticReport).contained[16] as Observation).interpretation!!.coding[0].code))
        assertTrue(stringMatch("Observation", ((obj.entry[14].resource!! as DiagnosticReport).contained[17] as Observation).resourceType))
        assertTrue(stringMatch("o18", ((obj.entry[14].resource!! as DiagnosticReport).contained[17] as Observation).id))
        assertTrue(stringMatch("final", ((obj.entry[14].resource!! as DiagnosticReport).contained[17] as Observation).status))
        assertTrue(stringMatch("http://example.org/local", ((obj.entry[14].resource!! as DiagnosticReport).contained[17] as Observation).code.coding[0].system))
        assertTrue(stringMatch("TOB", ((obj.entry[14].resource!! as DiagnosticReport).contained[17] as Observation).code.coding[0].code))
        assertTrue(stringMatch("TOBRAMYCIN", ((obj.entry[14].resource!! as DiagnosticReport).contained[17] as Observation).code.coding[0].display))
        assertTrue(stringMatch("Patient/5", ((obj.entry[14].resource!! as DiagnosticReport).contained[17] as Observation).subject!!.reference))
        assertTrue(stringMatch("Organization/1832473e-2fe0-45", ((obj.entry[14].resource!! as DiagnosticReport).contained[17] as Observation).performer[0].reference))
        assertTrue(stringMatch("Acme Laboratory, Inc", ((obj.entry[14].resource!! as DiagnosticReport).contained[17] as Observation).performer[0].display))
        assertTrue(stringMatch("%.2f".format(1f), "%.2f".format(((obj.entry[14].resource!! as DiagnosticReport).contained[17] as Observation).valueQuantity!!.value)))
        assertTrue(stringMatch("<=", ((obj.entry[14].resource!! as DiagnosticReport).contained[17] as Observation).valueQuantity!!.comparator))
        assertTrue(stringMatch("U", ((obj.entry[14].resource!! as DiagnosticReport).contained[17] as Observation).valueQuantity!!.unit))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0078", ((obj.entry[14].resource!! as DiagnosticReport).contained[17] as Observation).interpretation!!.coding[0].system))
        assertTrue(stringMatch("S", ((obj.entry[14].resource!! as DiagnosticReport).contained[17] as Observation).interpretation!!.coding[0].code))
        assertTrue(stringMatch("http://acme.com/lab/reports", (obj.entry[14].resource!! as DiagnosticReport).identifier[0].system))
        assertTrue(stringMatch("5234342", (obj.entry[14].resource!! as DiagnosticReport).identifier[0].value))
        assertTrue(stringMatch("final", (obj.entry[14].resource!! as DiagnosticReport).status))
        assertTrue(stringMatch("http://loinc.org", (obj.entry[14].resource!! as DiagnosticReport).code.coding[0].system))
        assertTrue(stringMatch("18769-0", (obj.entry[14].resource!! as DiagnosticReport).code.coding[0].code))
        assertTrue(stringMatch("Microbial susceptibility test", (obj.entry[14].resource!! as DiagnosticReport).code.coding[0].display))
    }
}
