package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle11DataTest : DataTests() {
    @Test
    fun `practitioner-examples-general 375 Test`() {
        val json = File("./src/test/resources/model/sample_data/practitioner-examples-general.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[35].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[35].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[35].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222557777", (obj.entry[35].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[35].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Kidder", (obj.entry[35].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Karen", (obj.entry[35].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[35].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1046", (obj.entry[35].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[35].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[35].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1044 Healthcare Drive", (obj.entry[35].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("female", (obj.entry[35].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[36].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[36].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("48", (obj.entry[36].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[36].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[36].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[36].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[36].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[36].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[36].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222558888", (obj.entry[36].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[36].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Hollywood", (obj.entry[36].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Heddie", (obj.entry[36].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[36].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1047", (obj.entry[36].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[36].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[36].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1045 Healthcare Drive", (obj.entry[36].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("female", (obj.entry[36].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[37].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[37].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("49", (obj.entry[37].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[37].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[37].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[37].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[37].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[37].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[37].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222559999", (obj.entry[37].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[37].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Shrink", (obj.entry[37].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Serena", (obj.entry[37].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[37].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1048", (obj.entry[37].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[37].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[37].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1046 Healthcare Drive", (obj.entry[37].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("female", (obj.entry[37].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[38].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[38].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("50", (obj.entry[38].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[38].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[38].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[38].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[38].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[38].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[38].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222662222", (obj.entry[38].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[38].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Puffer", (obj.entry[38].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Penny", (obj.entry[38].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[38].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1049", (obj.entry[38].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[38].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[38].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1047 Healthcare Drive", (obj.entry[38].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("female", (obj.entry[38].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[39].fullUrl))
    }
}
