package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle94DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 465 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertEquals("2004-11-02", (obj.entry[194].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[194].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[195].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[195].resource!! as Patient).resourceType))
        assertTrue(stringMatch("266", (obj.entry[195].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[195].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[195].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[195].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[195].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[195].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[195].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577585", (obj.entry[195].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[195].resource!! as Patient).active != null) (obj.entry[195].resource!! as Patient).active else false, "Field: (obj.entry[195].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[195].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Pittman", (obj.entry[195].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Jimmie", (obj.entry[195].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[195].resource!! as Patient).gender))
        assertEquals("1985-08-03", (obj.entry[195].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[195].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[196].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[196].resource!! as Patient).resourceType))
        assertTrue(stringMatch("267", (obj.entry[196].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[196].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[196].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[196].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[196].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[196].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[196].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577586", (obj.entry[196].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[196].resource!! as Patient).active != null) (obj.entry[196].resource!! as Patient).active else false, "Field: (obj.entry[196].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[196].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Holland", (obj.entry[196].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Beverly", (obj.entry[196].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[196].resource!! as Patient).gender))
        assertEquals("1978-02-03", (obj.entry[196].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[196].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[197].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[197].resource!! as Patient).resourceType))
        assertTrue(stringMatch("268", (obj.entry[197].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[197].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[197].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[197].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[197].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[197].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[197].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577587", (obj.entry[197].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[197].resource!! as Patient).active != null) (obj.entry[197].resource!! as Patient).active else false, "Field: (obj.entry[197].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[197].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Stone", (obj.entry[197].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Lillie", (obj.entry[197].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[197].resource!! as Patient).gender))
        assertEquals("1972-04-24", (obj.entry[197].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[197].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[198].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[198].resource!! as Patient).resourceType))
        assertTrue(stringMatch("269", (obj.entry[198].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[198].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[198].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[198].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[198].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[198].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[198].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577588", (obj.entry[198].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[198].resource!! as Patient).active != null) (obj.entry[198].resource!! as Patient).active else false, "Field: (obj.entry[198].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[198].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Hopkins", (obj.entry[198].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Clayton", (obj.entry[198].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[198].resource!! as Patient).gender))
        assertEquals("1982-09-01", (obj.entry[198].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[198].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[199].fullUrl))
    }
}
