package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle77DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 448 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertEquals("1942-02-14", (obj.entry[123].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[123].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[124].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[124].resource!! as Patient).resourceType))
        assertTrue(stringMatch("195", (obj.entry[124].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[124].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[124].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[124].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[124].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[124].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[124].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577514", (obj.entry[124].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[124].resource!! as Patient).active != null) (obj.entry[124].resource!! as Patient).active else false, "Field: (obj.entry[124].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[124].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Watts", (obj.entry[124].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Diane", (obj.entry[124].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[124].resource!! as Patient).gender))
        assertEquals("1938-05-08", (obj.entry[124].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[124].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[125].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[125].resource!! as Patient).resourceType))
        assertTrue(stringMatch("196", (obj.entry[125].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[125].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[125].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[125].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[125].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[125].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[125].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577515", (obj.entry[125].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[125].resource!! as Patient).active != null) (obj.entry[125].resource!! as Patient).active else false, "Field: (obj.entry[125].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[125].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Hansen", (obj.entry[125].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Marcus", (obj.entry[125].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[125].resource!! as Patient).gender))
        assertEquals("1946-06-08", (obj.entry[125].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[125].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[126].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[126].resource!! as Patient).resourceType))
        assertTrue(stringMatch("197", (obj.entry[126].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[126].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[126].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[126].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[126].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[126].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[126].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577516", (obj.entry[126].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[126].resource!! as Patient).active != null) (obj.entry[126].resource!! as Patient).active else false, "Field: (obj.entry[126].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[126].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Moran", (obj.entry[126].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Ramona", (obj.entry[126].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[126].resource!! as Patient).gender))
        assertEquals("1942-06-12", (obj.entry[126].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[126].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[127].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[127].resource!! as Patient).resourceType))
        assertTrue(stringMatch("198", (obj.entry[127].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[127].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[127].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[127].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[127].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[127].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[127].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577517", (obj.entry[127].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[127].resource!! as Patient).active != null) (obj.entry[127].resource!! as Patient).active else false, "Field: (obj.entry[127].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[127].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Williams", (obj.entry[127].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Charlotte", (obj.entry[127].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[127].resource!! as Patient).gender))
        assertEquals("1943-04-16", (obj.entry[127].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[127].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[128].fullUrl))
    }
}
