package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle195DataTest : DataTests() {
    @Test
    fun `diagnosticreport-examples-general 568 Test`() {
        val json = File("./src/test/resources/model/sample_data/diagnosticreport-examples-general.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("o4", ((obj.entry[14].resource!! as DiagnosticReport).contained[3] as Observation).id))
        assertTrue(stringMatch("final", ((obj.entry[14].resource!! as DiagnosticReport).contained[3] as Observation).status))
        assertTrue(stringMatch("http://example.org/local", ((obj.entry[14].resource!! as DiagnosticReport).contained[3] as Observation).code.coding[0].system))
        assertTrue(stringMatch("AM", ((obj.entry[14].resource!! as DiagnosticReport).contained[3] as Observation).code.coding[0].code))
        assertTrue(stringMatch("AMPICILLIN", ((obj.entry[14].resource!! as DiagnosticReport).contained[3] as Observation).code.coding[0].display))
        assertTrue(stringMatch("Patient/5", ((obj.entry[14].resource!! as DiagnosticReport).contained[3] as Observation).subject!!.reference))
        assertTrue(stringMatch("Organization/1832473e-2fe0-45", ((obj.entry[14].resource!! as DiagnosticReport).contained[3] as Observation).performer[0].reference))
        assertTrue(stringMatch("Acme Laboratory, Inc", ((obj.entry[14].resource!! as DiagnosticReport).contained[3] as Observation).performer[0].display))
        assertTrue(stringMatch("%.2f".format(16f), "%.2f".format(((obj.entry[14].resource!! as DiagnosticReport).contained[3] as Observation).valueQuantity!!.value)))
        assertTrue(stringMatch("U", ((obj.entry[14].resource!! as DiagnosticReport).contained[3] as Observation).valueQuantity!!.unit))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0078", ((obj.entry[14].resource!! as DiagnosticReport).contained[3] as Observation).interpretation!!.coding[0].system))
        assertTrue(stringMatch("R", ((obj.entry[14].resource!! as DiagnosticReport).contained[3] as Observation).interpretation!!.coding[0].code))
        assertTrue(stringMatch("Observation", ((obj.entry[14].resource!! as DiagnosticReport).contained[4] as Observation).resourceType))
        assertTrue(stringMatch("o5", ((obj.entry[14].resource!! as DiagnosticReport).contained[4] as Observation).id))
        assertTrue(stringMatch("final", ((obj.entry[14].resource!! as DiagnosticReport).contained[4] as Observation).status))
        assertTrue(stringMatch("http://example.org/local", ((obj.entry[14].resource!! as DiagnosticReport).contained[4] as Observation).code.coding[0].system))
        assertTrue(stringMatch("ATM", ((obj.entry[14].resource!! as DiagnosticReport).contained[4] as Observation).code.coding[0].code))
        assertTrue(stringMatch("AZTREONAM", ((obj.entry[14].resource!! as DiagnosticReport).contained[4] as Observation).code.coding[0].display))
        assertTrue(stringMatch("Patient/5", ((obj.entry[14].resource!! as DiagnosticReport).contained[4] as Observation).subject!!.reference))
        assertTrue(stringMatch("Organization/1832473e-2fe0-45", ((obj.entry[14].resource!! as DiagnosticReport).contained[4] as Observation).performer[0].reference))
        assertTrue(stringMatch("Acme Laboratory, Inc", ((obj.entry[14].resource!! as DiagnosticReport).contained[4] as Observation).performer[0].display))
        assertTrue(stringMatch("%.2f".format(1f), "%.2f".format(((obj.entry[14].resource!! as DiagnosticReport).contained[4] as Observation).valueQuantity!!.value)))
        assertTrue(stringMatch("<=", ((obj.entry[14].resource!! as DiagnosticReport).contained[4] as Observation).valueQuantity!!.comparator))
        assertTrue(stringMatch("U", ((obj.entry[14].resource!! as DiagnosticReport).contained[4] as Observation).valueQuantity!!.unit))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0078", ((obj.entry[14].resource!! as DiagnosticReport).contained[4] as Observation).interpretation!!.coding[0].system))
        assertTrue(stringMatch("S", ((obj.entry[14].resource!! as DiagnosticReport).contained[4] as Observation).interpretation!!.coding[0].code))
        assertTrue(stringMatch("Observation", ((obj.entry[14].resource!! as DiagnosticReport).contained[5] as Observation).resourceType))
        assertTrue(stringMatch("o6", ((obj.entry[14].resource!! as DiagnosticReport).contained[5] as Observation).id))
        assertTrue(stringMatch("final", ((obj.entry[14].resource!! as DiagnosticReport).contained[5] as Observation).status))
        assertTrue(stringMatch("http://example.org/local", ((obj.entry[14].resource!! as DiagnosticReport).contained[5] as Observation).code.coding[0].system))
        assertTrue(stringMatch("CFZ", ((obj.entry[14].resource!! as DiagnosticReport).contained[5] as Observation).code.coding[0].code))
        assertTrue(stringMatch("CEFAZOLIN", ((obj.entry[14].resource!! as DiagnosticReport).contained[5] as Observation).code.coding[0].display))
        assertTrue(stringMatch("Patient/5", ((obj.entry[14].resource!! as DiagnosticReport).contained[5] as Observation).subject!!.reference))
        assertTrue(stringMatch("Organization/1832473e-2fe0-45", ((obj.entry[14].resource!! as DiagnosticReport).contained[5] as Observation).performer[0].reference))
        assertTrue(stringMatch("Acme Laboratory, Inc", ((obj.entry[14].resource!! as DiagnosticReport).contained[5] as Observation).performer[0].display))
        assertTrue(stringMatch("%.2f".format(4f), "%.2f".format(((obj.entry[14].resource!! as DiagnosticReport).contained[5] as Observation).valueQuantity!!.value)))
        assertTrue(stringMatch("<=", ((obj.entry[14].resource!! as DiagnosticReport).contained[5] as Observation).valueQuantity!!.comparator))
        assertTrue(stringMatch("U", ((obj.entry[14].resource!! as DiagnosticReport).contained[5] as Observation).valueQuantity!!.unit))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0078", ((obj.entry[14].resource!! as DiagnosticReport).contained[5] as Observation).interpretation!!.coding[0].system))
        assertTrue(stringMatch("S", ((obj.entry[14].resource!! as DiagnosticReport).contained[5] as Observation).interpretation!!.coding[0].code))
        assertTrue(stringMatch("Observation", ((obj.entry[14].resource!! as DiagnosticReport).contained[6] as Observation).resourceType))
        assertTrue(stringMatch("o7", ((obj.entry[14].resource!! as DiagnosticReport).contained[6] as Observation).id))
        assertTrue(stringMatch("final", ((obj.entry[14].resource!! as DiagnosticReport).contained[6] as Observation).status))
        assertTrue(stringMatch("http://example.org/local", ((obj.entry[14].resource!! as DiagnosticReport).contained[6] as Observation).code.coding[0].system))
        assertTrue(stringMatch("FEP", ((obj.entry[14].resource!! as DiagnosticReport).contained[6] as Observation).code.coding[0].code))
        assertTrue(stringMatch("CEFEPIME", ((obj.entry[14].resource!! as DiagnosticReport).contained[6] as Observation).code.coding[0].display))
        assertTrue(stringMatch("Patient/5", ((obj.entry[14].resource!! as DiagnosticReport).contained[6] as Observation).subject!!.reference))
        assertTrue(stringMatch("Organization/1832473e-2fe0-45", ((obj.entry[14].resource!! as DiagnosticReport).contained[6] as Observation).performer[0].reference))
        assertTrue(stringMatch("Acme Laboratory, Inc", ((obj.entry[14].resource!! as DiagnosticReport).contained[6] as Observation).performer[0].display))
        assertTrue(stringMatch("%.2f".format(1f), "%.2f".format(((obj.entry[14].resource!! as DiagnosticReport).contained[6] as Observation).valueQuantity!!.value)))
        assertTrue(stringMatch("<=", ((obj.entry[14].resource!! as DiagnosticReport).contained[6] as Observation).valueQuantity!!.comparator))
        assertTrue(stringMatch("U", ((obj.entry[14].resource!! as DiagnosticReport).contained[6] as Observation).valueQuantity!!.unit))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0078", ((obj.entry[14].resource!! as DiagnosticReport).contained[6] as Observation).interpretation!!.coding[0].system))
        assertTrue(stringMatch("S", ((obj.entry[14].resource!! as DiagnosticReport).contained[6] as Observation).interpretation!!.coding[0].code))
        assertTrue(stringMatch("Observation", ((obj.entry[14].resource!! as DiagnosticReport).contained[7] as Observation).resourceType))
        assertTrue(stringMatch("o8", ((obj.entry[14].resource!! as DiagnosticReport).contained[7] as Observation).id))
        assertTrue(stringMatch("final", ((obj.entry[14].resource!! as DiagnosticReport).contained[7] as Observation).status))
        assertTrue(stringMatch("http://example.org/local", ((obj.entry[14].resource!! as DiagnosticReport).contained[7] as Observation).code.coding[0].system))
        assertTrue(stringMatch("CTN", ((obj.entry[14].resource!! as DiagnosticReport).contained[7] as Observation).code.coding[0].code))
        assertTrue(stringMatch("CEFOTETAN", ((obj.entry[14].resource!! as DiagnosticReport).contained[7] as Observation).code.coding[0].display))
        assertTrue(stringMatch("Patient/5", ((obj.entry[14].resource!! as DiagnosticReport).contained[7] as Observation).subject!!.reference))
        assertTrue(stringMatch("Organization/1832473e-2fe0-45", ((obj.entry[14].resource!! as DiagnosticReport).contained[7] as Observation).performer[0].reference))
        assertTrue(stringMatch("Acme Laboratory, Inc", ((obj.entry[14].resource!! as DiagnosticReport).contained[7] as Observation).performer[0].display))
        assertTrue(stringMatch("%.2f".format(4f), "%.2f".format(((obj.entry[14].resource!! as DiagnosticReport).contained[7] as Observation).valueQuantity!!.value)))
        assertTrue(stringMatch("<=", ((obj.entry[14].resource!! as DiagnosticReport).contained[7] as Observation).valueQuantity!!.comparator))
        assertTrue(stringMatch("U", ((obj.entry[14].resource!! as DiagnosticReport).contained[7] as Observation).valueQuantity!!.unit))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0078", ((obj.entry[14].resource!! as DiagnosticReport).contained[7] as Observation).interpretation!!.coding[0].system))
        assertTrue(stringMatch("S", ((obj.entry[14].resource!! as DiagnosticReport).contained[7] as Observation).interpretation!!.coding[0].code))
        assertTrue(stringMatch("Observation", ((obj.entry[14].resource!! as DiagnosticReport).contained[8] as Observation).resourceType))
        assertTrue(stringMatch("o9", ((obj.entry[14].resource!! as DiagnosticReport).contained[8] as Observation).id))
        assertTrue(stringMatch("final", ((obj.entry[14].resource!! as DiagnosticReport).contained[8] as Observation).status))
    }
}
