package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle95DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 466 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("Patient", (obj.entry[199].resource!! as Patient).resourceType))
        assertTrue(stringMatch("270", (obj.entry[199].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[199].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[199].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[199].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[199].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[199].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[199].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577589", (obj.entry[199].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[199].resource!! as Patient).active != null) (obj.entry[199].resource!! as Patient).active else false, "Field: (obj.entry[199].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[199].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Stevens", (obj.entry[199].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Patrick", (obj.entry[199].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[199].resource!! as Patient).gender))
        assertEquals("1992-12-14", (obj.entry[199].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[199].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[200].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[200].resource!! as Patient).resourceType))
        assertTrue(stringMatch("271", (obj.entry[200].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[200].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[200].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[200].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[200].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[200].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[200].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577590", (obj.entry[200].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[200].resource!! as Patient).active != null) (obj.entry[200].resource!! as Patient).active else false, "Field: (obj.entry[200].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[200].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Singleton", (obj.entry[200].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Audrey", (obj.entry[200].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[200].resource!! as Patient).gender))
        assertEquals("1989-09-12", (obj.entry[200].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[200].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[201].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[201].resource!! as Patient).resourceType))
        assertTrue(stringMatch("272", (obj.entry[201].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[201].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[201].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[201].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[201].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[201].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[201].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577591", (obj.entry[201].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[201].resource!! as Patient).active != null) (obj.entry[201].resource!! as Patient).active else false, "Field: (obj.entry[201].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[201].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Wilson", (obj.entry[201].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Barry", (obj.entry[201].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[201].resource!! as Patient).gender))
        assertEquals("1989-09-12", (obj.entry[201].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[201].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[202].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[202].resource!! as Patient).resourceType))
        assertTrue(stringMatch("273", (obj.entry[202].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[202].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[202].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[202].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[202].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[202].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[202].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577592", (obj.entry[202].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[202].resource!! as Patient).active != null) (obj.entry[202].resource!! as Patient).active else false, "Field: (obj.entry[202].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[202].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Hernandez", (obj.entry[202].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Renee", (obj.entry[202].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[202].resource!! as Patient).gender))
        assertEquals("1943-09-03", (obj.entry[202].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[202].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[203].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[203].resource!! as Patient).resourceType))
        assertTrue(stringMatch("274", (obj.entry[203].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[203].resource!! as Patient).meta!!.lastUpdated.toString())
    }
}
