package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle6DataTest : DataTests() {
    @Test
    fun `practitioner-examples-general 370 Test`() {
        val json = File("./src/test/resources/model/sample_data/practitioner-examples-general.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("Vera", (obj.entry[16].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[16].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1028", (obj.entry[16].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[16].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[16].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1026 Healthcare Drive", (obj.entry[16].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("female", (obj.entry[16].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[17].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[17].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("29", (obj.entry[17].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[17].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[17].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[17].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[17].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[17].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[17].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222336666", (obj.entry[17].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[17].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Scratch", (obj.entry[17].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Sophie", (obj.entry[17].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[17].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1029", (obj.entry[17].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[17].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[17].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1027 Healthcare Drive", (obj.entry[17].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("female", (obj.entry[17].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[18].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[18].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("30", (obj.entry[18].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[18].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[18].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[18].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[18].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[18].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[18].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222337777", (obj.entry[18].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[18].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Emergency", (obj.entry[18].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Eric", (obj.entry[18].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[18].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1030", (obj.entry[18].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[18].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[18].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1028 Healthcare Drive", (obj.entry[18].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("male", (obj.entry[18].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[19].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[19].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("31", (obj.entry[19].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[19].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[19].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[19].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[19].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[19].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[19].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222338888", (obj.entry[19].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[19].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Hormone", (obj.entry[19].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Horace", (obj.entry[19].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[19].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1031", (obj.entry[19].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[19].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[19].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1029 Healthcare Drive", (obj.entry[19].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("male", (obj.entry[19].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[20].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[20].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("32", (obj.entry[20].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[20].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[20].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[20].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[20].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
    }
}
