package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle15DataTest : DataTests() {
    @Test
    fun `practitioner-examples-general 379 Test`() {
        val json = File("./src/test/resources/model/sample_data/practitioner-examples-general.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[50].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[50].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[50].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[50].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("333222222", (obj.entry[50].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[50].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Script", (obj.entry[50].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Susan", (obj.entry[50].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[50].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1016", (obj.entry[50].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[50].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[50].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1016 Healthcare Drive", (obj.entry[50].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("female", (obj.entry[50].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[51].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[51].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("63", (obj.entry[51].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[51].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[51].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[51].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[51].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[51].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[51].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222772222", (obj.entry[51].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[51].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Bunion", (obj.entry[51].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Paul", (obj.entry[51].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[51].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1057", (obj.entry[51].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[51].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[51].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1055 Healthcare Drive", (obj.entry[51].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("male", (obj.entry[51].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[52].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[52].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("64", (obj.entry[52].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[52].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[52].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[52].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[52].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[52].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[52].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222773333", (obj.entry[52].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[52].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Listener", (obj.entry[52].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Larry", (obj.entry[52].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[52].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1058", (obj.entry[52].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[52].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[52].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1056 Healthcare Drive", (obj.entry[52].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("male", (obj.entry[52].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[53].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[53].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("65", (obj.entry[53].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[53].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[53].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[53].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[53].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[53].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[53].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("333444444", (obj.entry[53].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[53].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Beaker", (obj.entry[53].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Bill", (obj.entry[53].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[53].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1017", (obj.entry[53].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[53].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[53].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1017 Healthcare Drive", (obj.entry[53].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("male", (obj.entry[53].resource!! as Practitioner).gender))
    }
}
