package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle30DataTest : DataTests() {
    @Test
    fun `document-example-dischargesummary 397 Test`() {
        val json = File("./src/test/resources/model/sample_data/document-example-dischargesummary.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("Discharged to care of GP", (obj.entry[3].resource!! as Encounter).hospitalization!!.dischargeDisposition!!.text))
        assertTrue(stringMatch("urn:uuid:541a72a8-df75-4484-a", obj.entry[4].fullUrl))
        assertTrue(stringMatch("Observation", (obj.entry[4].resource!! as Observation).resourceType))
        assertEquals("2013-05-05T16:13:03Z", (obj.entry[4].resource!! as Observation).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("additional", (obj.entry[4].resource!! as Observation).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[4].resource!! as Observation).text!!.div))
        assertTrue(stringMatch("final", (obj.entry[4].resource!! as Observation).status))
        assertTrue(stringMatch("http://loinc.org", (obj.entry[4].resource!! as Observation).code.coding[0].system))
        assertTrue(stringMatch("46241-6", (obj.entry[4].resource!! as Observation).code.coding[0].code))
        assertTrue(stringMatch("Reason for admission", (obj.entry[4].resource!! as Observation).code.text))
        assertTrue(stringMatch("http://fhir.healthintersectio", (obj.entry[4].resource!! as Observation).subject!!.reference))
        assertTrue(stringMatch("Eve Everywoman", (obj.entry[4].resource!! as Observation).subject!!.display))
        assertTrue(stringMatch("http://fhir.healthintersectio", (obj.entry[4].resource!! as Observation).context!!.reference))
        assertTrue(stringMatch("Acute Asthmatic attack. Was w", (obj.entry[4].resource!! as Observation).valueString))
        assertTrue(stringMatch("urn:uuid:124a6916-5d84-4b8c-b", obj.entry[5].fullUrl))
        assertTrue(stringMatch("MedicationRequest", (obj.entry[5].resource!! as MedicationRequest).resourceType))
        assertEquals("2013-05-05T16:13:03Z", (obj.entry[5].resource!! as MedicationRequest).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[5].resource!! as MedicationRequest).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[5].resource!! as MedicationRequest).text!!.div))
        assertTrue(stringMatch("order", (obj.entry[5].resource!! as MedicationRequest).intent))
        assertTrue(stringMatch("http://snomed.info/sct", (obj.entry[5].resource!! as MedicationRequest).medicationCodeableConcept.coding[0].system))
        assertTrue(stringMatch("66493003", (obj.entry[5].resource!! as MedicationRequest).medicationCodeableConcept.coding[0].code))
        assertTrue(stringMatch("Theophylline 200mg", (obj.entry[5].resource!! as MedicationRequest).medicationCodeableConcept.text))
        assertTrue(stringMatch("http://fhir.healthintersectio", (obj.entry[5].resource!! as MedicationRequest).subject.reference))
        assertTrue(stringMatch("Peter Patient", (obj.entry[5].resource!! as MedicationRequest).subject.display))
        assertTrue(stringMatch("Practitioner/example", (obj.entry[5].resource!! as MedicationRequest).requester!!.agent.reference))
        assertTrue(stringMatch("Peter Practitioner", (obj.entry[5].resource!! as MedicationRequest).requester!!.agent.display))
        assertTrue(stringMatch("Organization/f002", (obj.entry[5].resource!! as MedicationRequest).requester!!.onBehalfOf!!.reference))
        assertTrue(stringMatch("Management of Asthma", (obj.entry[5].resource!! as MedicationRequest).reasonCode[0].text))
        assertTrue(stringMatch("Take with Food", (obj.entry[5].resource!! as MedicationRequest).dosageInstruction[0].additionalInstruction[0].text))
        assertEquals(2, (obj.entry[5].resource!! as MedicationRequest).dosageInstruction[0].timing!!.repeat!!.frequency)
        assertTrue(stringMatch("%.2f".format(1f), "%.2f".format((obj.entry[5].resource!! as MedicationRequest).dosageInstruction[0].timing!!.repeat!!.period)))
        assertTrue(stringMatch("d", (obj.entry[5].resource!! as MedicationRequest).dosageInstruction[0].timing!!.repeat!!.periodUnit))
        assertTrue(stringMatch("http://snomed.info/sct", (obj.entry[5].resource!! as MedicationRequest).dosageInstruction[0].route!!.coding[0].system))
        assertTrue(stringMatch("394899003", (obj.entry[5].resource!! as MedicationRequest).dosageInstruction[0].route!!.coding[0].code))
        assertTrue(stringMatch("oral administration of treatm", (obj.entry[5].resource!! as MedicationRequest).dosageInstruction[0].route!!.coding[0].display))
        assertTrue(stringMatch("%.2f".format(1f), "%.2f".format((obj.entry[5].resource!! as MedicationRequest).dosageInstruction[0].doseQuantity!!.value)))
        assertTrue(stringMatch("tablet", (obj.entry[5].resource!! as MedicationRequest).dosageInstruction[0].doseQuantity!!.unit))
        assertTrue(stringMatch("http://unitsofmeasure.org", (obj.entry[5].resource!! as MedicationRequest).dosageInstruction[0].doseQuantity!!.system))
        assertTrue(stringMatch("tbl", (obj.entry[5].resource!! as MedicationRequest).dosageInstruction[0].doseQuantity!!.code))
        assertTrue(stringMatch("urn:uuid:673f8db5-0ffd-4395-9", obj.entry[6].fullUrl))
        assertTrue(stringMatch("MedicationStatement", (obj.entry[6].resource!! as MedicationStatement).resourceType))
        assertTrue(stringMatch("generated", (obj.entry[6].resource!! as MedicationStatement).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[6].resource!! as MedicationStatement).text!!.div))
        assertTrue(stringMatch("completed", (obj.entry[6].resource!! as MedicationStatement).status))
        assertTrue(stringMatch("Ventolin Inhaler", (obj.entry[6].resource!! as MedicationStatement).medicationCodeableConcept.text))
        assertEquals("2013-05-05T16:13:03Z", (obj.entry[6].resource!! as MedicationStatement).dateAsserted.toString())
        assertTrue(stringMatch("http://fhir.healthintersectio", (obj.entry[6].resource!! as MedicationStatement).subject.reference))
        assertTrue(stringMatch("Peter Patient", (obj.entry[6].resource!! as MedicationStatement).subject.display))
        assertTrue(stringMatch("n", (obj.entry[6].resource!! as MedicationStatement).taken))
        assertTrue(stringMatch("Management of Asthma", (obj.entry[6].resource!! as MedicationStatement).reasonNotTaken[0].text))
        assertTrue(stringMatch("urn:uuid:47600e0f-b6b5-4308-8", obj.entry[7].fullUrl))
        assertTrue(stringMatch("AllergyIntolerance", (obj.entry[7].resource!! as AllergyIntolerance).resourceType))
        assertEquals("2013-05-05T16:13:03Z", (obj.entry[7].resource!! as AllergyIntolerance).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[7].resource!! as AllergyIntolerance).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[7].resource!! as AllergyIntolerance).text!!.div))
        assertTrue(stringMatch("active", (obj.entry[7].resource!! as AllergyIntolerance).clinicalStatus))
        assertTrue(stringMatch("confirmed", (obj.entry[7].resource!! as AllergyIntolerance).verificationStatus))
        assertTrue(stringMatch("allergy", (obj.entry[7].resource!! as AllergyIntolerance).type))
        assertTrue(stringMatch("high", (obj.entry[7].resource!! as AllergyIntolerance).criticality))
        assertTrue(stringMatch("Doxycycline", (obj.entry[7].resource!! as AllergyIntolerance).code!!.text))
        assertTrue(stringMatch("http://fhir.healthintersectio", (obj.entry[7].resource!! as AllergyIntolerance).patient.reference))
        assertTrue(stringMatch("Eve Everywoman", (obj.entry[7].resource!! as AllergyIntolerance).patient.display))
        assertEquals("2012-09-17", (obj.entry[7].resource!! as AllergyIntolerance).assertedDate.toString())
        assertTrue(stringMatch("http://example.org/system", (obj.entry[7].resource!! as AllergyIntolerance).reaction[0].manifestation[0].coding[0].system))
        assertTrue(stringMatch("xxx", (obj.entry[7].resource!! as AllergyIntolerance).reaction[0].manifestation[0].coding[0].code))
        assertTrue(stringMatch("Hives", (obj.entry[7].resource!! as AllergyIntolerance).reaction[0].manifestation[0].coding[0].display))
        assertTrue(stringMatch("Hives", (obj.entry[7].resource!! as AllergyIntolerance).reaction[0].manifestation[0].text))
        assertTrue(stringMatch("urn:iso-astm:E1762-95:2013", obj.signature!!.type[0].system))
        assertTrue(stringMatch("1.2.840.10065.1.12.1.1", obj.signature!!.type[0].code))
        assertTrue(stringMatch("Author's Signature", obj.signature!!.type[0].display))
    }
}
