package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle91DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 462 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[182].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[182].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[182].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577572", (obj.entry[182].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[182].resource!! as Patient).active != null) (obj.entry[182].resource!! as Patient).active else false, "Field: (obj.entry[182].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[182].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Mendoza", (obj.entry[182].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Clifford", (obj.entry[182].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[182].resource!! as Patient).gender))
        assertEquals("1945-03-25", (obj.entry[182].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[182].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[183].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[183].resource!! as Patient).resourceType))
        assertTrue(stringMatch("254", (obj.entry[183].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[183].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[183].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[183].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[183].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[183].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[183].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577573", (obj.entry[183].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[183].resource!! as Patient).active != null) (obj.entry[183].resource!! as Patient).active else false, "Field: (obj.entry[183].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[183].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Craig", (obj.entry[183].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Judith", (obj.entry[183].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[183].resource!! as Patient).gender))
        assertEquals("1978-06-12", (obj.entry[183].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[183].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[184].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[184].resource!! as Patient).resourceType))
        assertTrue(stringMatch("255", (obj.entry[184].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[184].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[184].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[184].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[184].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[184].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[184].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577574", (obj.entry[184].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[184].resource!! as Patient).active != null) (obj.entry[184].resource!! as Patient).active else false, "Field: (obj.entry[184].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[184].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Fleming", (obj.entry[184].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Vivian", (obj.entry[184].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[184].resource!! as Patient).gender))
        assertEquals("1994-10-29", (obj.entry[184].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[184].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[185].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[185].resource!! as Patient).resourceType))
        assertTrue(stringMatch("256", (obj.entry[185].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[185].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[185].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[185].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[185].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[185].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[185].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577575", (obj.entry[185].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[185].resource!! as Patient).active != null) (obj.entry[185].resource!! as Patient).active else false, "Field: (obj.entry[185].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[185].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Smith", (obj.entry[185].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Peggy", (obj.entry[185].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[185].resource!! as Patient).gender))
        assertEquals("1976-12-15", (obj.entry[185].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[185].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[186].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[186].resource!! as Patient).resourceType))
        assertTrue(stringMatch("257", (obj.entry[186].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[186].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[186].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[186].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[186].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[186].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[186].resource!! as Patient).identifier[0].system))
    }
}
