package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle201DataTest : DataTests() {
    @Test
    fun `patient-examples-general 575 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-general.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("phone", (obj.entry[5].resource!! as Patient).telecom[0].system))
        assertTrue(stringMatch("555-555-5001", (obj.entry[5].resource!! as Patient).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[5].resource!! as Patient).telecom[0].use))
        assertTrue(stringMatch("male", (obj.entry[5].resource!! as Patient).gender))
        assertTrue(stringMatch("home", (obj.entry[5].resource!! as Patient).address[0].use))
        assertTrue(stringMatch("6666 Home Street", (obj.entry[5].resource!! as Patient).address[0].line[0]))
        assertTrue(stringMatch("Organization/hl7", (obj.entry[5].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/7", obj.entry[6].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[6].resource!! as Patient).resourceType))
        assertTrue(stringMatch("7", (obj.entry[6].resource!! as Patient).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[6].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[6].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[6].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[6].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[6].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[6].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("444112345", (obj.entry[6].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[6].resource!! as Patient).active != null) (obj.entry[6].resource!! as Patient).active else false, "Field: (obj.entry[6].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[6].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Nuclear", (obj.entry[6].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Nelda", (obj.entry[6].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[6].resource!! as Patient).telecom[0].system))
        assertTrue(stringMatch("555-555-5001", (obj.entry[6].resource!! as Patient).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[6].resource!! as Patient).telecom[0].use))
        assertTrue(stringMatch("female", (obj.entry[6].resource!! as Patient).gender))
        assertTrue(stringMatch("home", (obj.entry[6].resource!! as Patient).address[0].use))
        assertTrue(stringMatch("6666 Home Street", (obj.entry[6].resource!! as Patient).address[0].line[0]))
        assertTrue(stringMatch("Organization/hl7", (obj.entry[6].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/8", obj.entry[7].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[7].resource!! as Patient).resourceType))
        assertTrue(stringMatch("8", (obj.entry[7].resource!! as Patient).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[7].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[7].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[7].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[7].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[7].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[7].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("444666666", (obj.entry[7].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[7].resource!! as Patient).active != null) (obj.entry[7].resource!! as Patient).active else false, "Field: (obj.entry[7].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[7].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Mum", (obj.entry[7].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Martha", (obj.entry[7].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[7].resource!! as Patient).telecom[0].system))
        assertTrue(stringMatch("555-555-2006", (obj.entry[7].resource!! as Patient).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[7].resource!! as Patient).telecom[0].use))
        assertTrue(stringMatch("female", (obj.entry[7].resource!! as Patient).gender))
        assertTrue(stringMatch("home", (obj.entry[7].resource!! as Patient).address[0].use))
        assertTrue(stringMatch("4444 Home Street", (obj.entry[7].resource!! as Patient).address[0].line[0]))
        assertTrue(stringMatch("Organization/hl7", (obj.entry[7].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/9", obj.entry[8].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[8].resource!! as Patient).resourceType))
        assertTrue(stringMatch("9", (obj.entry[8].resource!! as Patient).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[8].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[8].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[8].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[8].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[8].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[8].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("444777777", (obj.entry[8].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[8].resource!! as Patient).active != null) (obj.entry[8].resource!! as Patient).active else false, "Field: (obj.entry[8].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[8].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Sons", (obj.entry[8].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Stuart", (obj.entry[8].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[8].resource!! as Patient).telecom[0].system))
        assertTrue(stringMatch("555-555-2007", (obj.entry[8].resource!! as Patient).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[8].resource!! as Patient).telecom[0].use))
        assertTrue(stringMatch("other", (obj.entry[8].resource!! as Patient).gender))
        assertEquals("2002-08-24", (obj.entry[8].resource!! as Patient).deceasedDateTime.toString())
        assertTrue(stringMatch("home", (obj.entry[8].resource!! as Patient).address[0].use))
        assertTrue(stringMatch("4444 Home Street", (obj.entry[8].resource!! as Patient).address[0].line[0]))
        assertTrue(stringMatch("Organization/hl7", (obj.entry[8].resource!! as Patient).managingOrganization!!.reference))
    }
}
