package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle89DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 460 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[174].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[174].resource!! as Patient).resourceType))
        assertTrue(stringMatch("245", (obj.entry[174].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[174].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[174].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[174].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[174].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[174].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[174].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577564", (obj.entry[174].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[174].resource!! as Patient).active != null) (obj.entry[174].resource!! as Patient).active else false, "Field: (obj.entry[174].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[174].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Maldonado", (obj.entry[174].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Gail", (obj.entry[174].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[174].resource!! as Patient).gender))
        assertEquals("1975-12-15", (obj.entry[174].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[174].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[175].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[175].resource!! as Patient).resourceType))
        assertTrue(stringMatch("246", (obj.entry[175].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[175].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[175].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[175].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[175].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[175].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[175].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577565", (obj.entry[175].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[175].resource!! as Patient).active != null) (obj.entry[175].resource!! as Patient).active else false, "Field: (obj.entry[175].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[175].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Hammond", (obj.entry[175].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Amber", (obj.entry[175].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[175].resource!! as Patient).gender))
        assertEquals("1999-11-02", (obj.entry[175].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[175].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[176].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[176].resource!! as Patient).resourceType))
        assertTrue(stringMatch("247", (obj.entry[176].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[176].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[176].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[176].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[176].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[176].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[176].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577566", (obj.entry[176].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[176].resource!! as Patient).active != null) (obj.entry[176].resource!! as Patient).active else false, "Field: (obj.entry[176].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[176].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Copeland", (obj.entry[176].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Neil", (obj.entry[176].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[176].resource!! as Patient).gender))
        assertEquals("1953-03-17", (obj.entry[176].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[176].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[177].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[177].resource!! as Patient).resourceType))
        assertTrue(stringMatch("248", (obj.entry[177].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[177].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[177].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[177].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[177].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[177].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[177].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577567", (obj.entry[177].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[177].resource!! as Patient).active != null) (obj.entry[177].resource!! as Patient).active else false, "Field: (obj.entry[177].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[177].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Mills", (obj.entry[177].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Lloyd", (obj.entry[177].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[177].resource!! as Patient).gender))
        assertEquals("1958-07-10", (obj.entry[177].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[177].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[178].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[178].resource!! as Patient).resourceType))
        assertTrue(stringMatch("249", (obj.entry[178].resource!! as Patient).id))
    }
}
