package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle41DataTest : DataTests() {
    @Test
    fun `questionnaire-profile-example-ussg-fht 410 Test`() {
        val json = File("./src/test/resources/model/sample_data/questionnaire-profile-example-ussg-fht.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("Infancy", (obj.entry[8].resource!! as ValueSet).compose!!.include[0].concept[2].display))
        assertTrue(stringMatch("LA10395-4", (obj.entry[8].resource!! as ValueSet).compose!!.include[0].concept[3].code))
        assertTrue(stringMatch("Childhood", (obj.entry[8].resource!! as ValueSet).compose!!.include[0].concept[3].display))
        assertTrue(stringMatch("LA10404-4", (obj.entry[8].resource!! as ValueSet).compose!!.include[0].concept[4].code))
        assertTrue(stringMatch("Adolescence", (obj.entry[8].resource!! as ValueSet).compose!!.include[0].concept[4].display))
        assertTrue(stringMatch("LA10396-2", (obj.entry[8].resource!! as ValueSet).compose!!.include[0].concept[5].code))
        assertTrue(stringMatch("20-29", (obj.entry[8].resource!! as ValueSet).compose!!.include[0].concept[5].display))
        assertTrue(stringMatch("LA10397-0", (obj.entry[8].resource!! as ValueSet).compose!!.include[0].concept[6].code))
        assertTrue(stringMatch("30-39", (obj.entry[8].resource!! as ValueSet).compose!!.include[0].concept[6].display))
        assertTrue(stringMatch("LA10398-8", (obj.entry[8].resource!! as ValueSet).compose!!.include[0].concept[7].code))
        assertTrue(stringMatch("40-49", (obj.entry[8].resource!! as ValueSet).compose!!.include[0].concept[7].display))
        assertTrue(stringMatch("LA10399-6", (obj.entry[8].resource!! as ValueSet).compose!!.include[0].concept[8].code))
        assertTrue(stringMatch("50-59", (obj.entry[8].resource!! as ValueSet).compose!!.include[0].concept[8].display))
        assertTrue(stringMatch("LA10400-2", (obj.entry[8].resource!! as ValueSet).compose!!.include[0].concept[9].code))
        assertTrue(stringMatch("OVER 60", (obj.entry[8].resource!! as ValueSet).compose!!.include[0].concept[9].display))
        assertTrue(stringMatch("LA4489-6", (obj.entry[8].resource!! as ValueSet).compose!!.include[0].concept[10].code))
        assertTrue(stringMatch("Unknown", (obj.entry[8].resource!! as ValueSet).compose!!.include[0].concept[10].display))
        assertTrue(stringMatch("PUT", obj.entry[8].request!!.method))
        assertTrue(stringMatch("http://hl7.org/fhir/us/sdc/Va", obj.entry[8].request!!.url))
        assertTrue(stringMatch("http://hl7.org/fhir/us/sdc/Va", obj.entry[9].fullUrl))
        assertTrue(stringMatch("ValueSet", (obj.entry[9].resource!! as ValueSet).resourceType))
        assertTrue(stringMatch("LL621-4", (obj.entry[9].resource!! as ValueSet).id))
        assertTrue(stringMatch("http://hl7.org/fhir/us/sdc/St", (obj.entry[9].resource!! as ValueSet).meta!!.profile[0]))
        assertTrue(stringMatch("generated", (obj.entry[9].resource!! as ValueSet).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[9].resource!! as ValueSet).text!!.div))
        assertTrue(stringMatch("http://details.loinc.org/Answ", (obj.entry[9].resource!! as ValueSet).url))
        assertTrue(stringMatch("USSG-FHT relationship", (obj.entry[9].resource!! as ValueSet).name))
        assertTrue(stringMatch("active", (obj.entry[9].resource!! as ValueSet).status))
        assertTrue(stringMatch("Regenstrief Institute, Inc an", (obj.entry[9].resource!! as ValueSet).publisher))
        assertTrue(stringMatch("Family history tool relations", (obj.entry[9].resource!! as ValueSet).description))
        assertEquals(true, if ((obj.entry[9].resource!! as ValueSet).immutable != null) (obj.entry[9].resource!! as ValueSet).immutable else false, "Field: (obj.entry[9].resource!! as ValueSet).immutable")
        assertTrue(stringMatch("Refer to https://loinc.org/te", (obj.entry[9].resource!! as ValueSet).copyright))
        assertEquals(false, if ((obj.entry[9].resource!! as ValueSet).extensible != null) (obj.entry[9].resource!! as ValueSet).extensible else false, "Field: (obj.entry[9].resource!! as ValueSet).extensible")
        assertTrue(stringMatch("http://loinc.org", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].system))
        assertTrue(stringMatch("LA10405-1", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[0].code))
        assertTrue(stringMatch("Daughter", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[0].display))
        assertTrue(stringMatch("LA10406-9", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[1].code))
        assertTrue(stringMatch("Granddaughter", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[1].display))
        assertTrue(stringMatch("LA10407-7", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[2].code))
        assertTrue(stringMatch("Grandson", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[2].display))
        assertTrue(stringMatch("LA10408-5", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[3].code))
        assertTrue(stringMatch("Half-brother", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[3].display))
        assertTrue(stringMatch("LA10409-3", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[4].code))
        assertTrue(stringMatch("Half-sister", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[4].display))
        assertTrue(stringMatch("LA10410-1", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[5].code))
        assertTrue(stringMatch("Maternal Aunt", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[5].display))
        assertTrue(stringMatch("LA10411-9", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[6].code))
        assertTrue(stringMatch("Maternal Cousin", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[6].display))
        assertTrue(stringMatch("LA10412-7", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[7].code))
        assertTrue(stringMatch("Maternal Grandfather", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[7].display))
        assertTrue(stringMatch("LA10413-5", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[8].code))
        assertTrue(stringMatch("Maternal Grandmother", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[8].display))
        assertTrue(stringMatch("LA10414-3", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[9].code))
        assertTrue(stringMatch("Maternal Uncle", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[9].display))
        assertTrue(stringMatch("LA10415-0", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[10].code))
        assertTrue(stringMatch("Brother", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[10].display))
        assertTrue(stringMatch("LA10416-8", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[11].code))
        assertTrue(stringMatch("Father", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[11].display))
        assertTrue(stringMatch("LA10417-6", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[12].code))
        assertTrue(stringMatch("Mother", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[12].display))
        assertTrue(stringMatch("LA10418-4", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[13].code))
        assertTrue(stringMatch("Sister", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[13].display))
        assertTrue(stringMatch("LA10419-2", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[14].code))
        assertTrue(stringMatch("Nephew", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[14].display))
        assertTrue(stringMatch("LA10420-0", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[15].code))
        assertTrue(stringMatch("Niece", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[15].display))
        assertTrue(stringMatch("LA10421-8", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[16].code))
        assertTrue(stringMatch("Paternal Aunt", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[16].display))
        assertTrue(stringMatch("LA10422-6", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[17].code))
        assertTrue(stringMatch("Paternal Cousin", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[17].display))
        assertTrue(stringMatch("LA10423-4", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[18].code))
    }
}
