package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle72DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 443 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[103].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[103].resource!! as Patient).resourceType))
        assertTrue(stringMatch("174", (obj.entry[103].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[103].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[103].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[103].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[103].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[103].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[103].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577493", (obj.entry[103].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[103].resource!! as Patient).active != null) (obj.entry[103].resource!! as Patient).active else false, "Field: (obj.entry[103].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[103].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Graham", (obj.entry[103].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Maurice", (obj.entry[103].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[103].resource!! as Patient).gender))
        assertEquals("1955-02-12", (obj.entry[103].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[103].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[104].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[104].resource!! as Patient).resourceType))
        assertTrue(stringMatch("175", (obj.entry[104].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[104].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[104].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[104].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[104].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[104].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[104].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577494", (obj.entry[104].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[104].resource!! as Patient).active != null) (obj.entry[104].resource!! as Patient).active else false, "Field: (obj.entry[104].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[104].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Curtis", (obj.entry[104].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Ivan", (obj.entry[104].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[104].resource!! as Patient).gender))
        assertEquals("1982-04-08", (obj.entry[104].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[104].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[105].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[105].resource!! as Patient).resourceType))
        assertTrue(stringMatch("176", (obj.entry[105].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[105].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[105].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[105].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[105].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[105].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[105].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577495", (obj.entry[105].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[105].resource!! as Patient).active != null) (obj.entry[105].resource!! as Patient).active else false, "Field: (obj.entry[105].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[105].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Hines", (obj.entry[105].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Brett", (obj.entry[105].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[105].resource!! as Patient).gender))
        assertEquals("1973-06-01", (obj.entry[105].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[105].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[106].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[106].resource!! as Patient).resourceType))
        assertTrue(stringMatch("177", (obj.entry[106].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[106].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[106].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[106].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[106].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[106].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[106].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577496", (obj.entry[106].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[106].resource!! as Patient).active != null) (obj.entry[106].resource!! as Patient).active else false, "Field: (obj.entry[106].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[106].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Robbins", (obj.entry[106].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Jerome", (obj.entry[106].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[106].resource!! as Patient).gender))
        assertEquals("1971-04-15", (obj.entry[106].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[106].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[107].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[107].resource!! as Patient).resourceType))
        assertTrue(stringMatch("178", (obj.entry[107].resource!! as Patient).id))
    }
}
