package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle14DataTest : DataTests() {
    @Test
    fun `practitioner-examples-general 378 Test`() {
        val json = File("./src/test/resources/model/sample_data/practitioner-examples-general.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("official", (obj.entry[46].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Bender", (obj.entry[46].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Bob", (obj.entry[46].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[46].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1053", (obj.entry[46].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[46].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[46].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1051 Healthcare Drive", (obj.entry[46].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("male", (obj.entry[46].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[47].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[47].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("59", (obj.entry[47].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[47].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[47].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[47].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[47].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[47].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[47].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222667777", (obj.entry[47].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[47].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Chopper", (obj.entry[47].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Charlie", (obj.entry[47].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[47].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1054", (obj.entry[47].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[47].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[47].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1052 Healthcare Drive", (obj.entry[47].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("male", (obj.entry[47].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[48].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[48].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("60", (obj.entry[48].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[48].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[48].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[48].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[48].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[48].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[48].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222668888", (obj.entry[48].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[48].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Brace", (obj.entry[48].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Ben", (obj.entry[48].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[48].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1055", (obj.entry[48].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[48].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[48].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1053 Healthcare Drive", (obj.entry[48].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("male", (obj.entry[48].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[49].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[49].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("61", (obj.entry[49].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[49].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[49].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[49].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[49].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[49].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[49].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222669999", (obj.entry[49].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[49].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Specs", (obj.entry[49].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Sylvia", (obj.entry[49].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[49].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1056", (obj.entry[49].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[49].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[49].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1054 Healthcare Drive", (obj.entry[49].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("female", (obj.entry[49].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[50].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[50].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("62", (obj.entry[50].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[50].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[50].resource!! as Practitioner).text!!.status))
    }
}
