package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle84DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 455 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("224", (obj.entry[153].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[153].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[153].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[153].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[153].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[153].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[153].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577543", (obj.entry[153].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[153].resource!! as Patient).active != null) (obj.entry[153].resource!! as Patient).active else false, "Field: (obj.entry[153].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[153].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Mack", (obj.entry[153].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Jonathan", (obj.entry[153].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[153].resource!! as Patient).gender))
        assertEquals("1959-04-19", (obj.entry[153].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[153].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[154].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[154].resource!! as Patient).resourceType))
        assertTrue(stringMatch("225", (obj.entry[154].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[154].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[154].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[154].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[154].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[154].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[154].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577544", (obj.entry[154].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[154].resource!! as Patient).active != null) (obj.entry[154].resource!! as Patient).active else false, "Field: (obj.entry[154].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[154].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Campbell", (obj.entry[154].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Jared", (obj.entry[154].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[154].resource!! as Patient).gender))
        assertEquals("1975-11-16", (obj.entry[154].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[154].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[155].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[155].resource!! as Patient).resourceType))
        assertTrue(stringMatch("226", (obj.entry[155].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[155].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[155].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[155].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[155].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[155].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[155].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577545", (obj.entry[155].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[155].resource!! as Patient).active != null) (obj.entry[155].resource!! as Patient).active else false, "Field: (obj.entry[155].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[155].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Blake", (obj.entry[155].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Jason", (obj.entry[155].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[155].resource!! as Patient).gender))
        assertEquals("1952-02-13", (obj.entry[155].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[155].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[156].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[156].resource!! as Patient).resourceType))
        assertTrue(stringMatch("227", (obj.entry[156].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[156].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[156].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[156].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[156].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[156].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[156].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577546", (obj.entry[156].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[156].resource!! as Patient).active != null) (obj.entry[156].resource!! as Patient).active else false, "Field: (obj.entry[156].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[156].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Malone", (obj.entry[156].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Tyler", (obj.entry[156].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[156].resource!! as Patient).gender))
        assertEquals("1948-09-14", (obj.entry[156].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[156].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[157].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[157].resource!! as Patient).resourceType))
        assertTrue(stringMatch("228", (obj.entry[157].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[157].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[157].resource!! as Patient).text!!.status))
    }
}
