package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle81DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 452 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertEquals(true, if ((obj.entry[140].resource!! as Patient).active != null) (obj.entry[140].resource!! as Patient).active else false, "Field: (obj.entry[140].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[140].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Carpenter", (obj.entry[140].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Charlotte", (obj.entry[140].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[140].resource!! as Patient).gender))
        assertEquals("1989-12-02", (obj.entry[140].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[140].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[141].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[141].resource!! as Patient).resourceType))
        assertTrue(stringMatch("212", (obj.entry[141].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[141].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[141].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[141].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[141].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[141].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[141].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577531", (obj.entry[141].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[141].resource!! as Patient).active != null) (obj.entry[141].resource!! as Patient).active else false, "Field: (obj.entry[141].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[141].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Vaughn", (obj.entry[141].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Holly", (obj.entry[141].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[141].resource!! as Patient).gender))
        assertEquals("1957-03-06", (obj.entry[141].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[141].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[142].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[142].resource!! as Patient).resourceType))
        assertTrue(stringMatch("213", (obj.entry[142].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[142].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[142].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[142].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[142].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[142].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[142].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577532", (obj.entry[142].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[142].resource!! as Patient).active != null) (obj.entry[142].resource!! as Patient).active else false, "Field: (obj.entry[142].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[142].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Lane", (obj.entry[142].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Stacey", (obj.entry[142].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[142].resource!! as Patient).gender))
        assertEquals("1935-12-11", (obj.entry[142].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[142].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[143].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[143].resource!! as Patient).resourceType))
        assertTrue(stringMatch("214", (obj.entry[143].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[143].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[143].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[143].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[143].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[143].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[143].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577533", (obj.entry[143].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[143].resource!! as Patient).active != null) (obj.entry[143].resource!! as Patient).active else false, "Field: (obj.entry[143].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[143].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Porter", (obj.entry[143].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Lynn", (obj.entry[143].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[143].resource!! as Patient).gender))
        assertEquals("2009-02-11", (obj.entry[143].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[143].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[144].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[144].resource!! as Patient).resourceType))
        assertTrue(stringMatch("215", (obj.entry[144].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[144].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[144].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[144].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[144].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[144].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[144].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577534", (obj.entry[144].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[144].resource!! as Patient).active != null) (obj.entry[144].resource!! as Patient).active else false, "Field: (obj.entry[144].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[144].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Fernandez", (obj.entry[144].resource!! as Patient).name[0].family))
    }
}
