package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle7DataTest : DataTests() {
    @Test
    fun `practitioner-examples-general 371 Test`() {
        val json = File("./src/test/resources/model/sample_data/practitioner-examples-general.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("SS", (obj.entry[20].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[20].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222339999", (obj.entry[20].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[20].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Family", (obj.entry[20].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Fay", (obj.entry[20].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[20].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1032", (obj.entry[20].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[20].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[20].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1030 Healthcare Drive", (obj.entry[20].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("female", (obj.entry[20].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[21].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[21].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("33", (obj.entry[21].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[21].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[21].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[21].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[21].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[21].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[21].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222442222", (obj.entry[21].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[21].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Tum", (obj.entry[21].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Tony", (obj.entry[21].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[21].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1033", (obj.entry[21].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[21].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[21].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1031 Healthcare Drive", (obj.entry[21].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("male", (obj.entry[21].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[22].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[22].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("34", (obj.entry[22].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[22].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[22].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[22].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[22].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[22].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[22].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222443333", (obj.entry[22].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[22].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Sage", (obj.entry[22].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Stanley", (obj.entry[22].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[22].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1034", (obj.entry[22].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[22].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[22].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1032 Healthcare Drive", (obj.entry[22].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("male", (obj.entry[22].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[23].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[23].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("35", (obj.entry[23].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[23].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[23].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[23].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[23].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[23].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[23].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222443344", (obj.entry[23].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[23].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Bleeder", (obj.entry[23].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Boris", (obj.entry[23].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[23].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1035", (obj.entry[23].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[23].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[23].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1033 Healthcare Drive", (obj.entry[23].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("male", (obj.entry[23].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[24].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[24].resource!! as Practitioner).resourceType))
    }
}
