package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle106DataTest : DataTests() {
    @Test
    fun `diagnosticreport-examples-general 479 Test`() {
        val json = File("./src/test/resources/model/sample_data/diagnosticreport-examples-general.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("mmol/L", ((obj.entry[0].resource!! as DiagnosticReport).contained[17] as Observation).valueQuantity!!.unit))
        assertTrue(stringMatch("%.2f".format(2.25f), "%.2f".format(((obj.entry[0].resource!! as DiagnosticReport).contained[17] as Observation).referenceRange[0].low!!.value)))
        assertTrue(stringMatch("mmol/L", ((obj.entry[0].resource!! as DiagnosticReport).contained[17] as Observation).referenceRange[0].low!!.unit))
        assertTrue(stringMatch("%.2f".format(2.65f), "%.2f".format(((obj.entry[0].resource!! as DiagnosticReport).contained[17] as Observation).referenceRange[0].high!!.value)))
        assertTrue(stringMatch("mmol/L", ((obj.entry[0].resource!! as DiagnosticReport).contained[17] as Observation).referenceRange[0].high!!.unit))
        assertTrue(stringMatch("Observation", ((obj.entry[0].resource!! as DiagnosticReport).contained[18] as Observation).resourceType))
        assertTrue(stringMatch("o19", ((obj.entry[0].resource!! as DiagnosticReport).contained[18] as Observation).id))
        assertTrue(stringMatch("final", ((obj.entry[0].resource!! as DiagnosticReport).contained[18] as Observation).status))
        assertTrue(stringMatch("http://loinc.org", ((obj.entry[0].resource!! as DiagnosticReport).contained[18] as Observation).code.coding[0].system))
        assertTrue(stringMatch("14879-1", ((obj.entry[0].resource!! as DiagnosticReport).contained[18] as Observation).code.coding[0].code))
        assertTrue(stringMatch("Phosphate [Moles/volume] in S", ((obj.entry[0].resource!! as DiagnosticReport).contained[18] as Observation).code.coding[0].display))
        assertTrue(stringMatch("http://snomed.info/sct", ((obj.entry[0].resource!! as DiagnosticReport).contained[18] as Observation).code.coding[1].system))
        assertTrue(stringMatch("104866001", ((obj.entry[0].resource!! as DiagnosticReport).contained[18] as Observation).code.coding[1].code))
        assertTrue(stringMatch("Patient/1", ((obj.entry[0].resource!! as DiagnosticReport).contained[18] as Observation).subject!!.reference))
        assertTrue(stringMatch("Organization/1832473e-2fe0-45", ((obj.entry[0].resource!! as DiagnosticReport).contained[18] as Observation).performer[0].reference))
        assertTrue(stringMatch("Acme Laboratory, Inc", ((obj.entry[0].resource!! as DiagnosticReport).contained[18] as Observation).performer[0].display))
        assertTrue(stringMatch("%.2f".format(1.5f), "%.2f".format(((obj.entry[0].resource!! as DiagnosticReport).contained[18] as Observation).valueQuantity!!.value)))
        assertTrue(stringMatch("mmol/L", ((obj.entry[0].resource!! as DiagnosticReport).contained[18] as Observation).valueQuantity!!.unit))
        assertTrue(stringMatch("%.2f".format(0.8f), "%.2f".format(((obj.entry[0].resource!! as DiagnosticReport).contained[18] as Observation).referenceRange[0].low!!.value)))
        assertTrue(stringMatch("mmol/L", ((obj.entry[0].resource!! as DiagnosticReport).contained[18] as Observation).referenceRange[0].low!!.unit))
        assertTrue(stringMatch("%.2f".format(1.5f), "%.2f".format(((obj.entry[0].resource!! as DiagnosticReport).contained[18] as Observation).referenceRange[0].high!!.value)))
        assertTrue(stringMatch("mmol/L", ((obj.entry[0].resource!! as DiagnosticReport).contained[18] as Observation).referenceRange[0].high!!.unit))
        assertTrue(stringMatch("Observation", ((obj.entry[0].resource!! as DiagnosticReport).contained[19] as Observation).resourceType))
        assertTrue(stringMatch("o20", ((obj.entry[0].resource!! as DiagnosticReport).contained[19] as Observation).id))
        assertTrue(stringMatch("final", ((obj.entry[0].resource!! as DiagnosticReport).contained[19] as Observation).status))
        assertTrue(stringMatch("http://loinc.org", ((obj.entry[0].resource!! as DiagnosticReport).contained[19] as Observation).code.coding[0].system))
        assertTrue(stringMatch("2885-2", ((obj.entry[0].resource!! as DiagnosticReport).contained[19] as Observation).code.coding[0].code))
        assertTrue(stringMatch("Protein [Mass/volume] in Seru", ((obj.entry[0].resource!! as DiagnosticReport).contained[19] as Observation).code.coding[0].display))
        assertTrue(stringMatch("http://snomed.info/sct", ((obj.entry[0].resource!! as DiagnosticReport).contained[19] as Observation).code.coding[1].system))
        assertTrue(stringMatch("74040009", ((obj.entry[0].resource!! as DiagnosticReport).contained[19] as Observation).code.coding[1].code))
        assertTrue(stringMatch("Patient/1", ((obj.entry[0].resource!! as DiagnosticReport).contained[19] as Observation).subject!!.reference))
        assertTrue(stringMatch("Organization/1832473e-2fe0-45", ((obj.entry[0].resource!! as DiagnosticReport).contained[19] as Observation).performer[0].reference))
        assertTrue(stringMatch("Acme Laboratory, Inc", ((obj.entry[0].resource!! as DiagnosticReport).contained[19] as Observation).performer[0].display))
        assertTrue(stringMatch("%.2f".format(67f), "%.2f".format(((obj.entry[0].resource!! as DiagnosticReport).contained[19] as Observation).valueQuantity!!.value)))
        assertTrue(stringMatch("g/L", ((obj.entry[0].resource!! as DiagnosticReport).contained[19] as Observation).valueQuantity!!.unit))
        assertTrue(stringMatch("%.2f".format(60f), "%.2f".format(((obj.entry[0].resource!! as DiagnosticReport).contained[19] as Observation).referenceRange[0].low!!.value)))
        assertTrue(stringMatch("g/L", ((obj.entry[0].resource!! as DiagnosticReport).contained[19] as Observation).referenceRange[0].low!!.unit))
        assertTrue(stringMatch("%.2f".format(82f), "%.2f".format(((obj.entry[0].resource!! as DiagnosticReport).contained[19] as Observation).referenceRange[0].high!!.value)))
        assertTrue(stringMatch("g/L", ((obj.entry[0].resource!! as DiagnosticReport).contained[19] as Observation).referenceRange[0].high!!.unit))
        assertTrue(stringMatch("Observation", ((obj.entry[0].resource!! as DiagnosticReport).contained[20] as Observation).resourceType))
        assertTrue(stringMatch("o21", ((obj.entry[0].resource!! as DiagnosticReport).contained[20] as Observation).id))
        assertTrue(stringMatch("final", ((obj.entry[0].resource!! as DiagnosticReport).contained[20] as Observation).status))
        assertTrue(stringMatch("http://loinc.org", ((obj.entry[0].resource!! as DiagnosticReport).contained[20] as Observation).code.coding[0].system))
        assertTrue(stringMatch("1751-7", ((obj.entry[0].resource!! as DiagnosticReport).contained[20] as Observation).code.coding[0].code))
        assertTrue(stringMatch("Albumin [Mass/volume] in Seru", ((obj.entry[0].resource!! as DiagnosticReport).contained[20] as Observation).code.coding[0].display))
        assertTrue(stringMatch("http://snomed.info/sct", ((obj.entry[0].resource!! as DiagnosticReport).contained[20] as Observation).code.coding[1].system))
        assertTrue(stringMatch("104485008", ((obj.entry[0].resource!! as DiagnosticReport).contained[20] as Observation).code.coding[1].code))
        assertTrue(stringMatch("Patient/1", ((obj.entry[0].resource!! as DiagnosticReport).contained[20] as Observation).subject!!.reference))
        assertTrue(stringMatch("Organization/1832473e-2fe0-45", ((obj.entry[0].resource!! as DiagnosticReport).contained[20] as Observation).performer[0].reference))
        assertTrue(stringMatch("Acme Laboratory, Inc", ((obj.entry[0].resource!! as DiagnosticReport).contained[20] as Observation).performer[0].display))
        assertTrue(stringMatch("%.2f".format(42f), "%.2f".format(((obj.entry[0].resource!! as DiagnosticReport).contained[20] as Observation).valueQuantity!!.value)))
        assertTrue(stringMatch("g/L", ((obj.entry[0].resource!! as DiagnosticReport).contained[20] as Observation).valueQuantity!!.unit))
        assertTrue(stringMatch("%.2f".format(35f), "%.2f".format(((obj.entry[0].resource!! as DiagnosticReport).contained[20] as Observation).referenceRange[0].low!!.value)))
        assertTrue(stringMatch("g/L", ((obj.entry[0].resource!! as DiagnosticReport).contained[20] as Observation).referenceRange[0].low!!.unit))
        assertTrue(stringMatch("%.2f".format(50f), "%.2f".format(((obj.entry[0].resource!! as DiagnosticReport).contained[20] as Observation).referenceRange[0].high!!.value)))
        assertTrue(stringMatch("g/L", ((obj.entry[0].resource!! as DiagnosticReport).contained[20] as Observation).referenceRange[0].high!!.unit))
        assertTrue(stringMatch("Observation", ((obj.entry[0].resource!! as DiagnosticReport).contained[21] as Observation).resourceType))
        assertTrue(stringMatch("o22", ((obj.entry[0].resource!! as DiagnosticReport).contained[21] as Observation).id))
        assertTrue(stringMatch("final", ((obj.entry[0].resource!! as DiagnosticReport).contained[21] as Observation).status))
        assertTrue(stringMatch("http://loinc.org", ((obj.entry[0].resource!! as DiagnosticReport).contained[21] as Observation).code.coding[0].system))
        assertTrue(stringMatch("10834-0", ((obj.entry[0].resource!! as DiagnosticReport).contained[21] as Observation).code.coding[0].code))
        assertTrue(stringMatch("Globulin [Mass/volume] in Ser", ((obj.entry[0].resource!! as DiagnosticReport).contained[21] as Observation).code.coding[0].display))
        assertTrue(stringMatch("http://snomed.info/sct", ((obj.entry[0].resource!! as DiagnosticReport).contained[21] as Observation).code.coding[1].system))
        assertTrue(stringMatch("104979009", ((obj.entry[0].resource!! as DiagnosticReport).contained[21] as Observation).code.coding[1].code))
        assertTrue(stringMatch("Patient/1", ((obj.entry[0].resource!! as DiagnosticReport).contained[21] as Observation).subject!!.reference))
        assertTrue(stringMatch("Organization/1832473e-2fe0-45", ((obj.entry[0].resource!! as DiagnosticReport).contained[21] as Observation).performer[0].reference))
        assertTrue(stringMatch("Acme Laboratory, Inc", ((obj.entry[0].resource!! as DiagnosticReport).contained[21] as Observation).performer[0].display))
        assertTrue(stringMatch("%.2f".format(25f), "%.2f".format(((obj.entry[0].resource!! as DiagnosticReport).contained[21] as Observation).valueQuantity!!.value)))
        assertTrue(stringMatch("g/L", ((obj.entry[0].resource!! as DiagnosticReport).contained[21] as Observation).valueQuantity!!.unit))
        assertTrue(stringMatch("%.2f".format(20f), "%.2f".format(((obj.entry[0].resource!! as DiagnosticReport).contained[21] as Observation).referenceRange[0].low!!.value)))
        assertTrue(stringMatch("g/L", ((obj.entry[0].resource!! as DiagnosticReport).contained[21] as Observation).referenceRange[0].low!!.unit))
    }
}
