package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle55DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 426 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[32].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[32].resource!! as Patient).resourceType))
        assertTrue(stringMatch("103", (obj.entry[32].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[32].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[32].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[32].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[32].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[32].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[32].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577422", (obj.entry[32].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[32].resource!! as Patient).active != null) (obj.entry[32].resource!! as Patient).active else false, "Field: (obj.entry[32].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[32].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Christensen", (obj.entry[32].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Donald", (obj.entry[32].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[32].resource!! as Patient).gender))
        assertEquals("1933-03-02", (obj.entry[32].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[32].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[33].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[33].resource!! as Patient).resourceType))
        assertTrue(stringMatch("104", (obj.entry[33].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[33].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[33].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[33].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[33].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[33].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[33].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577423", (obj.entry[33].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[33].resource!! as Patient).active != null) (obj.entry[33].resource!! as Patient).active else false, "Field: (obj.entry[33].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[33].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Hughes", (obj.entry[33].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Teresa", (obj.entry[33].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[33].resource!! as Patient).gender))
        assertEquals("1988-05-22", (obj.entry[33].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[33].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[34].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[34].resource!! as Patient).resourceType))
        assertTrue(stringMatch("105", (obj.entry[34].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[34].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[34].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[34].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[34].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[34].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[34].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577424", (obj.entry[34].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[34].resource!! as Patient).active != null) (obj.entry[34].resource!! as Patient).active else false, "Field: (obj.entry[34].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[34].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Houston", (obj.entry[34].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Daryl", (obj.entry[34].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[34].resource!! as Patient).gender))
        assertEquals("1937-02-14", (obj.entry[34].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[34].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[35].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[35].resource!! as Patient).resourceType))
        assertTrue(stringMatch("106", (obj.entry[35].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[35].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[35].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[35].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[35].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[35].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[35].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577425", (obj.entry[35].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[35].resource!! as Patient).active != null) (obj.entry[35].resource!! as Patient).active else false, "Field: (obj.entry[35].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[35].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("West", (obj.entry[35].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("James", (obj.entry[35].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[35].resource!! as Patient).gender))
        assertEquals("1946-06-08", (obj.entry[35].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[35].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/1", obj.entry[36].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[36].resource!! as Patient).resourceType))
        assertTrue(stringMatch("107", (obj.entry[36].resource!! as Patient).id))
    }
}
