package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle12DataTest : DataTests() {
    @Test
    fun `practitioner-examples-general 376 Test`() {
        val json = File("./src/test/resources/model/sample_data/practitioner-examples-general.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("Practitioner", (obj.entry[39].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("51", (obj.entry[39].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[39].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[39].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[39].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[39].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[39].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[39].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222555555", (obj.entry[39].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[39].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Curie", (obj.entry[39].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Christine", (obj.entry[39].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[39].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1011", (obj.entry[39].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[39].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[39].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1011 Healthcare Drive", (obj.entry[39].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("female", (obj.entry[39].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[40].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[40].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("52", (obj.entry[40].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[40].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[40].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[40].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[40].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[40].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[40].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222663333", (obj.entry[40].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[40].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Joint", (obj.entry[40].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Jeffrey", (obj.entry[40].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[40].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1050", (obj.entry[40].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[40].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[40].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1048 Healthcare Drive", (obj.entry[40].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("male", (obj.entry[40].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[41].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[41].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("53", (obj.entry[41].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[41].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[41].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[41].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[41].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[41].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[41].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222777777", (obj.entry[41].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[41].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Cutter", (obj.entry[41].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Carl", (obj.entry[41].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[41].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1013", (obj.entry[41].resource!! as Practitioner).telecom[0].value))
        assertTrue(stringMatch("work", (obj.entry[41].resource!! as Practitioner).telecom[0].use))
        assertTrue(stringMatch("home", (obj.entry[41].resource!! as Practitioner).address[0].use))
        assertTrue(stringMatch("1013 Healthcare Drive", (obj.entry[41].resource!! as Practitioner).address[0].line[0]))
        assertTrue(stringMatch("male", (obj.entry[41].resource!! as Practitioner).gender))
        assertTrue(stringMatch("http://hl7.org/fhir/Practitio", obj.entry[42].fullUrl))
        assertTrue(stringMatch("Practitioner", (obj.entry[42].resource!! as Practitioner).resourceType))
        assertTrue(stringMatch("54", (obj.entry[42].resource!! as Practitioner).id))
        assertEquals("2012-05-29T23:45:32Z", (obj.entry[42].resource!! as Practitioner).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[42].resource!! as Practitioner).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[42].resource!! as Practitioner).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[42].resource!! as Practitioner).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[42].resource!! as Practitioner).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("http://hl7.org/fhir/sid/us-ss", (obj.entry[42].resource!! as Practitioner).identifier[0].system))
        assertTrue(stringMatch("222664444", (obj.entry[42].resource!! as Practitioner).identifier[0].value))
        assertTrue(stringMatch("official", (obj.entry[42].resource!! as Practitioner).name[0].use))
        assertTrue(stringMatch("Plumber", (obj.entry[42].resource!! as Practitioner).name[0].family))
        assertTrue(stringMatch("Peter", (obj.entry[42].resource!! as Practitioner).name[0].given[0]))
        assertTrue(stringMatch("phone", (obj.entry[42].resource!! as Practitioner).telecom[0].system))
        assertTrue(stringMatch("555-555-1051", (obj.entry[42].resource!! as Practitioner).telecom[0].value))
    }
}
