package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle42DataTest : DataTests() {
    @Test
    fun `questionnaire-profile-example-ussg-fht 411 Test`() {
        val json = File("./src/test/resources/model/sample_data/questionnaire-profile-example-ussg-fht.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("Paternal Grandfather", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[18].display))
        assertTrue(stringMatch("LA10424-2", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[19].code))
        assertTrue(stringMatch("Paternal Grandmother", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[19].display))
        assertTrue(stringMatch("LA10425-9", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[20].code))
        assertTrue(stringMatch("Paternal Uncle", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[20].display))
        assertTrue(stringMatch("LA10426-7", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[21].code))
        assertTrue(stringMatch("Son", (obj.entry[9].resource!! as ValueSet).compose!!.include[0].concept[21].display))
        assertTrue(stringMatch("PUT", obj.entry[9].request!!.method))
        assertTrue(stringMatch("http://hl7.org/fhir/us/sdc/Va", obj.entry[9].request!!.url))
        assertTrue(stringMatch("http://hl7.org/fhir/us/sdc/Va", obj.entry[10].fullUrl))
        assertTrue(stringMatch("ValueSet", (obj.entry[10].resource!! as ValueSet).resourceType))
        assertTrue(stringMatch("LL624-8", (obj.entry[10].resource!! as ValueSet).id))
        assertTrue(stringMatch("http://hl7.org/fhir/us/sdc/St", (obj.entry[10].resource!! as ValueSet).meta!!.profile[0]))
        assertTrue(stringMatch("generated", (obj.entry[10].resource!! as ValueSet).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[10].resource!! as ValueSet).text!!.div))
        assertTrue(stringMatch("http://details.loinc.org/Answ", (obj.entry[10].resource!! as ValueSet).url))
        assertTrue(stringMatch("USSG-FHT living", (obj.entry[10].resource!! as ValueSet).name))
        assertTrue(stringMatch("active", (obj.entry[10].resource!! as ValueSet).status))
        assertTrue(stringMatch("Regenstrief Institute, Inc an", (obj.entry[10].resource!! as ValueSet).publisher))
        assertTrue(stringMatch("Family history tool living", (obj.entry[10].resource!! as ValueSet).description))
        assertEquals(true, if ((obj.entry[10].resource!! as ValueSet).immutable != null) (obj.entry[10].resource!! as ValueSet).immutable else false, "Field: (obj.entry[10].resource!! as ValueSet).immutable")
        assertTrue(stringMatch("Refer to https://loinc.org/te", (obj.entry[10].resource!! as ValueSet).copyright))
        assertEquals(false, if ((obj.entry[10].resource!! as ValueSet).extensible != null) (obj.entry[10].resource!! as ValueSet).extensible else false, "Field: (obj.entry[10].resource!! as ValueSet).extensible")
        assertTrue(stringMatch("http://loinc.org", (obj.entry[10].resource!! as ValueSet).compose!!.include[0].system))
        assertTrue(stringMatch("LA33-6", (obj.entry[10].resource!! as ValueSet).compose!!.include[0].concept[0].code))
        assertTrue(stringMatch("Yes", (obj.entry[10].resource!! as ValueSet).compose!!.include[0].concept[0].display))
        assertTrue(stringMatch("LA32-8", (obj.entry[10].resource!! as ValueSet).compose!!.include[0].concept[1].code))
        assertTrue(stringMatch("No", (obj.entry[10].resource!! as ValueSet).compose!!.include[0].concept[1].display))
        assertTrue(stringMatch("LA4489-6", (obj.entry[10].resource!! as ValueSet).compose!!.include[0].concept[2].code))
        assertTrue(stringMatch("Unknown", (obj.entry[10].resource!! as ValueSet).compose!!.include[0].concept[2].display))
        assertTrue(stringMatch("PUT", obj.entry[10].request!!.method))
        assertTrue(stringMatch("http://hl7.org/fhir/us/sdc/Va", obj.entry[10].request!!.url))
        assertTrue(stringMatch("http://hl7.org/fhir/us/sdc/Va", obj.entry[11].fullUrl))
        assertTrue(stringMatch("ValueSet", (obj.entry[11].resource!! as ValueSet).resourceType))
        assertTrue(stringMatch("LL627-1", (obj.entry[11].resource!! as ValueSet).id))
        assertTrue(stringMatch("http://hl7.org/fhir/us/sdc/St", (obj.entry[11].resource!! as ValueSet).meta!!.profile[0]))
        assertTrue(stringMatch("generated", (obj.entry[11].resource!! as ValueSet).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[11].resource!! as ValueSet).text!!.div))
        assertTrue(stringMatch("http://details.loinc.org/Answ", (obj.entry[11].resource!! as ValueSet).url))
        assertTrue(stringMatch("USSG-FHT diseases & cause of ", (obj.entry[11].resource!! as ValueSet).name))
        assertTrue(stringMatch("active", (obj.entry[11].resource!! as ValueSet).status))
        assertTrue(stringMatch("Regenstrief Institute, Inc an", (obj.entry[11].resource!! as ValueSet).publisher))
        assertTrue(stringMatch("Family history tool diseases ", (obj.entry[11].resource!! as ValueSet).description))
        assertEquals(true, if ((obj.entry[11].resource!! as ValueSet).immutable != null) (obj.entry[11].resource!! as ValueSet).immutable else false, "Field: (obj.entry[11].resource!! as ValueSet).immutable")
        assertTrue(stringMatch("Refer to https://loinc.org/te", (obj.entry[11].resource!! as ValueSet).copyright))
        assertEquals(false, if ((obj.entry[11].resource!! as ValueSet).extensible != null) (obj.entry[11].resource!! as ValueSet).extensible else false, "Field: (obj.entry[11].resource!! as ValueSet).extensible")
        assertTrue(stringMatch("http://loinc.org", (obj.entry[11].resource!! as ValueSet).compose!!.include[0].system))
        assertTrue(stringMatch("LA10533-0", (obj.entry[11].resource!! as ValueSet).compose!!.include[0].concept[0].code))
        assertTrue(stringMatch("Blood Clots", (obj.entry[11].resource!! as ValueSet).compose!!.include[0].concept[0].display))
        assertTrue(stringMatch("LA10572-8", (obj.entry[11].resource!! as ValueSet).compose!!.include[0].concept[1].code))
        assertTrue(stringMatch("-- Blood Clot in Leg", (obj.entry[11].resource!! as ValueSet).compose!!.include[0].concept[1].display))
        assertTrue(stringMatch("LA10573-6", (obj.entry[11].resource!! as ValueSet).compose!!.include[0].concept[2].code))
        assertTrue(stringMatch("-- Blood Clot in Lungs", (obj.entry[11].resource!! as ValueSet).compose!!.include[0].concept[2].display))
        assertTrue(stringMatch("LA10524-9", (obj.entry[11].resource!! as ValueSet).compose!!.include[0].concept[3].code))
        assertTrue(stringMatch("Cancer", (obj.entry[11].resource!! as ValueSet).compose!!.include[0].concept[3].display))
        assertTrue(stringMatch("LA10549-6", (obj.entry[11].resource!! as ValueSet).compose!!.include[0].concept[4].code))
        assertTrue(stringMatch("-- Bone", (obj.entry[11].resource!! as ValueSet).compose!!.include[0].concept[4].display))
        assertTrue(stringMatch("LA10536-3", (obj.entry[11].resource!! as ValueSet).compose!!.include[0].concept[5].code))
        assertTrue(stringMatch("-- Breast Cancer", (obj.entry[11].resource!! as ValueSet).compose!!.include[0].concept[5].display))
        assertTrue(stringMatch("LA10537-1", (obj.entry[11].resource!! as ValueSet).compose!!.include[0].concept[6].code))
        assertTrue(stringMatch("-- Colon Cancer", (obj.entry[11].resource!! as ValueSet).compose!!.include[0].concept[6].display))
        assertTrue(stringMatch("LA10548-8", (obj.entry[11].resource!! as ValueSet).compose!!.include[0].concept[7].code))
        assertTrue(stringMatch("-- Esophageal Cancer", (obj.entry[11].resource!! as ValueSet).compose!!.include[0].concept[7].display))
        assertTrue(stringMatch("LA10547-0", (obj.entry[11].resource!! as ValueSet).compose!!.include[0].concept[8].code))
        assertTrue(stringMatch("-- Gastric Cancer", (obj.entry[11].resource!! as ValueSet).compose!!.include[0].concept[8].display))
        assertTrue(stringMatch("LA10541-3", (obj.entry[11].resource!! as ValueSet).compose!!.include[0].concept[9].code))
        assertTrue(stringMatch("-- Kidney Cancer", (obj.entry[11].resource!! as ValueSet).compose!!.include[0].concept[9].display))
        assertTrue(stringMatch("LA10545-4", (obj.entry[11].resource!! as ValueSet).compose!!.include[0].concept[10].code))
        assertTrue(stringMatch("-- Leukemia", (obj.entry[11].resource!! as ValueSet).compose!!.include[0].concept[10].display))
        assertTrue(stringMatch("LA10542-1", (obj.entry[11].resource!! as ValueSet).compose!!.include[0].concept[11].code))
        assertTrue(stringMatch("-- Lung Cancer", (obj.entry[11].resource!! as ValueSet).compose!!.include[0].concept[11].display))
    }
}
