package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle80DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 451 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("SS", (obj.entry[136].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[136].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577526", (obj.entry[136].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[136].resource!! as Patient).active != null) (obj.entry[136].resource!! as Patient).active else false, "Field: (obj.entry[136].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[136].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Terry", (obj.entry[136].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Sergio", (obj.entry[136].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[136].resource!! as Patient).gender))
        assertEquals("1933-10-17", (obj.entry[136].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[136].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[137].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[137].resource!! as Patient).resourceType))
        assertTrue(stringMatch("208", (obj.entry[137].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[137].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[137].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[137].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[137].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[137].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[137].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577527", (obj.entry[137].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[137].resource!! as Patient).active != null) (obj.entry[137].resource!! as Patient).active else false, "Field: (obj.entry[137].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[137].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("White", (obj.entry[137].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Raul", (obj.entry[137].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[137].resource!! as Patient).gender))
        assertEquals("1951-06-22", (obj.entry[137].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[137].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[138].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[138].resource!! as Patient).resourceType))
        assertTrue(stringMatch("209", (obj.entry[138].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[138].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[138].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[138].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[138].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[138].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[138].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577528", (obj.entry[138].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[138].resource!! as Patient).active != null) (obj.entry[138].resource!! as Patient).active else false, "Field: (obj.entry[138].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[138].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Richardson", (obj.entry[138].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Jordan", (obj.entry[138].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[138].resource!! as Patient).gender))
        assertEquals("1945-02-08", (obj.entry[138].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[138].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[139].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[139].resource!! as Patient).resourceType))
        assertTrue(stringMatch("210", (obj.entry[139].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[139].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[139].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[139].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[139].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[139].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[139].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577529", (obj.entry[139].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[139].resource!! as Patient).active != null) (obj.entry[139].resource!! as Patient).active else false, "Field: (obj.entry[139].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[139].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Bates", (obj.entry[139].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Joann", (obj.entry[139].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[139].resource!! as Patient).gender))
        assertEquals("1976-11-29", (obj.entry[139].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[139].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[140].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[140].resource!! as Patient).resourceType))
        assertTrue(stringMatch("211", (obj.entry[140].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[140].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[140].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[140].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[140].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[140].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[140].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577530", (obj.entry[140].resource!! as Patient).identifier[0].value))
    }
}
