package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle170DataTest : DataTests() {
    @Test
    fun `diagnosticreport-examples-general 543 Test`() {
        val json = File("./src/test/resources/model/sample_data/diagnosticreport-examples-general.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("o8", ((obj.entry[10].resource!! as DiagnosticReport).contained[7] as Observation).id))
        assertTrue(stringMatch("final", ((obj.entry[10].resource!! as DiagnosticReport).contained[7] as Observation).status))
        assertTrue(stringMatch("http://loinc.org", ((obj.entry[10].resource!! as DiagnosticReport).contained[7] as Observation).code.coding[0].system))
        assertTrue(stringMatch("14682-9", ((obj.entry[10].resource!! as DiagnosticReport).contained[7] as Observation).code.coding[0].code))
        assertTrue(stringMatch("Creatinine [Moles/volume] in ", ((obj.entry[10].resource!! as DiagnosticReport).contained[7] as Observation).code.coding[0].display))
        assertTrue(stringMatch("http://snomed.info/sct", ((obj.entry[10].resource!! as DiagnosticReport).contained[7] as Observation).code.coding[1].system))
        assertTrue(stringMatch("70901006", ((obj.entry[10].resource!! as DiagnosticReport).contained[7] as Observation).code.coding[1].code))
        assertTrue(stringMatch("Patient/1", ((obj.entry[10].resource!! as DiagnosticReport).contained[7] as Observation).subject!!.reference))
        assertTrue(stringMatch("Organization/1832473e-2fe0-45", ((obj.entry[10].resource!! as DiagnosticReport).contained[7] as Observation).performer[0].reference))
        assertTrue(stringMatch("Acme Laboratory, Inc", ((obj.entry[10].resource!! as DiagnosticReport).contained[7] as Observation).performer[0].display))
        assertTrue(stringMatch("%.2f".format(0.08f), "%.2f".format(((obj.entry[10].resource!! as DiagnosticReport).contained[7] as Observation).valueQuantity!!.value)))
        assertTrue(stringMatch("mmol/L", ((obj.entry[10].resource!! as DiagnosticReport).contained[7] as Observation).valueQuantity!!.unit))
        assertTrue(stringMatch("%.2f".format(0.04f), "%.2f".format(((obj.entry[10].resource!! as DiagnosticReport).contained[7] as Observation).referenceRange[0].low!!.value)))
        assertTrue(stringMatch("mmol/L", ((obj.entry[10].resource!! as DiagnosticReport).contained[7] as Observation).referenceRange[0].low!!.unit))
        assertTrue(stringMatch("%.2f".format(0.11f), "%.2f".format(((obj.entry[10].resource!! as DiagnosticReport).contained[7] as Observation).referenceRange[0].high!!.value)))
        assertTrue(stringMatch("mmol/L", ((obj.entry[10].resource!! as DiagnosticReport).contained[7] as Observation).referenceRange[0].high!!.unit))
        assertTrue(stringMatch("Observation", ((obj.entry[10].resource!! as DiagnosticReport).contained[8] as Observation).resourceType))
        assertTrue(stringMatch("o9", ((obj.entry[10].resource!! as DiagnosticReport).contained[8] as Observation).id))
        assertTrue(stringMatch("final", ((obj.entry[10].resource!! as DiagnosticReport).contained[8] as Observation).status))
        assertTrue(stringMatch("http://loinc.org", ((obj.entry[10].resource!! as DiagnosticReport).contained[8] as Observation).code.coding[0].system))
        assertTrue(stringMatch("14933-6", ((obj.entry[10].resource!! as DiagnosticReport).contained[8] as Observation).code.coding[0].code))
        assertTrue(stringMatch("Urate [Moles/volume] in Serum", ((obj.entry[10].resource!! as DiagnosticReport).contained[8] as Observation).code.coding[0].display))
        assertTrue(stringMatch("http://snomed.info/sct", ((obj.entry[10].resource!! as DiagnosticReport).contained[8] as Observation).code.coding[1].system))
        assertTrue(stringMatch("86228006", ((obj.entry[10].resource!! as DiagnosticReport).contained[8] as Observation).code.coding[1].code))
        assertTrue(stringMatch("Patient/1", ((obj.entry[10].resource!! as DiagnosticReport).contained[8] as Observation).subject!!.reference))
        assertTrue(stringMatch("Organization/1832473e-2fe0-45", ((obj.entry[10].resource!! as DiagnosticReport).contained[8] as Observation).performer[0].reference))
        assertTrue(stringMatch("Acme Laboratory, Inc", ((obj.entry[10].resource!! as DiagnosticReport).contained[8] as Observation).performer[0].display))
        assertTrue(stringMatch("%.2f".format(0.40f), "%.2f".format(((obj.entry[10].resource!! as DiagnosticReport).contained[8] as Observation).valueQuantity!!.value)))
        assertTrue(stringMatch("mmol/L", ((obj.entry[10].resource!! as DiagnosticReport).contained[8] as Observation).valueQuantity!!.unit))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0078", ((obj.entry[10].resource!! as DiagnosticReport).contained[8] as Observation).interpretation!!.coding[0].system))
        assertTrue(stringMatch("HH", ((obj.entry[10].resource!! as DiagnosticReport).contained[8] as Observation).interpretation!!.coding[0].code))
        assertTrue(stringMatch("%.2f".format(0.14f), "%.2f".format(((obj.entry[10].resource!! as DiagnosticReport).contained[8] as Observation).referenceRange[0].low!!.value)))
        assertTrue(stringMatch("mmol/L", ((obj.entry[10].resource!! as DiagnosticReport).contained[8] as Observation).referenceRange[0].low!!.unit))
        assertTrue(stringMatch("%.2f".format(0.35f), "%.2f".format(((obj.entry[10].resource!! as DiagnosticReport).contained[8] as Observation).referenceRange[0].high!!.value)))
        assertTrue(stringMatch("mmol/L", ((obj.entry[10].resource!! as DiagnosticReport).contained[8] as Observation).referenceRange[0].high!!.unit))
        assertTrue(stringMatch("Observation", ((obj.entry[10].resource!! as DiagnosticReport).contained[9] as Observation).resourceType))
        assertTrue(stringMatch("o10", ((obj.entry[10].resource!! as DiagnosticReport).contained[9] as Observation).id))
        assertTrue(stringMatch("final", ((obj.entry[10].resource!! as DiagnosticReport).contained[9] as Observation).status))
        assertTrue(stringMatch("http://loinc.org", ((obj.entry[10].resource!! as DiagnosticReport).contained[9] as Observation).code.coding[0].system))
        assertTrue(stringMatch("14631-6", ((obj.entry[10].resource!! as DiagnosticReport).contained[9] as Observation).code.coding[0].code))
        assertTrue(stringMatch("Bilirubin.total [Moles/volume", ((obj.entry[10].resource!! as DiagnosticReport).contained[9] as Observation).code.coding[0].display))
        assertTrue(stringMatch("http://snomed.info/sct", ((obj.entry[10].resource!! as DiagnosticReport).contained[9] as Observation).code.coding[1].system))
        assertTrue(stringMatch("27171005", ((obj.entry[10].resource!! as DiagnosticReport).contained[9] as Observation).code.coding[1].code))
        assertTrue(stringMatch("Patient/1", ((obj.entry[10].resource!! as DiagnosticReport).contained[9] as Observation).subject!!.reference))
        assertTrue(stringMatch("Organization/1832473e-2fe0-45", ((obj.entry[10].resource!! as DiagnosticReport).contained[9] as Observation).performer[0].reference))
        assertTrue(stringMatch("Acme Laboratory, Inc", ((obj.entry[10].resource!! as DiagnosticReport).contained[9] as Observation).performer[0].display))
        assertTrue(stringMatch("%.2f".format(9f), "%.2f".format(((obj.entry[10].resource!! as DiagnosticReport).contained[9] as Observation).valueQuantity!!.value)))
        assertTrue(stringMatch("umol/L", ((obj.entry[10].resource!! as DiagnosticReport).contained[9] as Observation).valueQuantity!!.unit))
        assertTrue(stringMatch("%.2f".format(2f), "%.2f".format(((obj.entry[10].resource!! as DiagnosticReport).contained[9] as Observation).referenceRange[0].low!!.value)))
        assertTrue(stringMatch("umol/L", ((obj.entry[10].resource!! as DiagnosticReport).contained[9] as Observation).referenceRange[0].low!!.unit))
        assertTrue(stringMatch("%.2f".format(20f), "%.2f".format(((obj.entry[10].resource!! as DiagnosticReport).contained[9] as Observation).referenceRange[0].high!!.value)))
        assertTrue(stringMatch("umol/L", ((obj.entry[10].resource!! as DiagnosticReport).contained[9] as Observation).referenceRange[0].high!!.unit))
        assertTrue(stringMatch("Observation", ((obj.entry[10].resource!! as DiagnosticReport).contained[10] as Observation).resourceType))
        assertTrue(stringMatch("o11", ((obj.entry[10].resource!! as DiagnosticReport).contained[10] as Observation).id))
        assertTrue(stringMatch("final", ((obj.entry[10].resource!! as DiagnosticReport).contained[10] as Observation).status))
        assertTrue(stringMatch("http://loinc.org", ((obj.entry[10].resource!! as DiagnosticReport).contained[10] as Observation).code.coding[0].system))
        assertTrue(stringMatch("14629-0", ((obj.entry[10].resource!! as DiagnosticReport).contained[10] as Observation).code.coding[0].code))
        assertTrue(stringMatch("Bilirubin.direct [Moles/volum", ((obj.entry[10].resource!! as DiagnosticReport).contained[10] as Observation).code.coding[0].display))
        assertTrue(stringMatch("http://snomed.info/sct", ((obj.entry[10].resource!! as DiagnosticReport).contained[10] as Observation).code.coding[1].system))
        assertTrue(stringMatch("39748002", ((obj.entry[10].resource!! as DiagnosticReport).contained[10] as Observation).code.coding[1].code))
        assertTrue(stringMatch("Patient/1", ((obj.entry[10].resource!! as DiagnosticReport).contained[10] as Observation).subject!!.reference))
        assertTrue(stringMatch("Organization/1832473e-2fe0-45", ((obj.entry[10].resource!! as DiagnosticReport).contained[10] as Observation).performer[0].reference))
        assertTrue(stringMatch("Acme Laboratory, Inc", ((obj.entry[10].resource!! as DiagnosticReport).contained[10] as Observation).performer[0].display))
        assertTrue(stringMatch("%.2f".format(4f), "%.2f".format(((obj.entry[10].resource!! as DiagnosticReport).contained[10] as Observation).valueQuantity!!.value)))
        assertTrue(stringMatch("umol/L", ((obj.entry[10].resource!! as DiagnosticReport).contained[10] as Observation).valueQuantity!!.unit))
        assertTrue(stringMatch("%.2f".format(0f), "%.2f".format(((obj.entry[10].resource!! as DiagnosticReport).contained[10] as Observation).referenceRange[0].low!!.value)))
        assertTrue(stringMatch("umol/L", ((obj.entry[10].resource!! as DiagnosticReport).contained[10] as Observation).referenceRange[0].low!!.unit))
        assertTrue(stringMatch("%.2f".format(8f), "%.2f".format(((obj.entry[10].resource!! as DiagnosticReport).contained[10] as Observation).referenceRange[0].high!!.value)))
        assertTrue(stringMatch("umol/L", ((obj.entry[10].resource!! as DiagnosticReport).contained[10] as Observation).referenceRange[0].high!!.unit))
        assertTrue(stringMatch("Observation", ((obj.entry[10].resource!! as DiagnosticReport).contained[11] as Observation).resourceType))
        assertTrue(stringMatch("o12", ((obj.entry[10].resource!! as DiagnosticReport).contained[11] as Observation).id))
    }
}
