package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle79DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 450 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("generated", (obj.entry[132].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[132].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[132].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[132].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[132].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577522", (obj.entry[132].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[132].resource!! as Patient).active != null) (obj.entry[132].resource!! as Patient).active else false, "Field: (obj.entry[132].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[132].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Brown", (obj.entry[132].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Gina", (obj.entry[132].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[132].resource!! as Patient).gender))
        assertEquals("1991-12-25", (obj.entry[132].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[132].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[133].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[133].resource!! as Patient).resourceType))
        assertTrue(stringMatch("204", (obj.entry[133].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[133].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[133].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[133].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[133].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[133].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[133].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577523", (obj.entry[133].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[133].resource!! as Patient).active != null) (obj.entry[133].resource!! as Patient).active else false, "Field: (obj.entry[133].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[133].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Fields", (obj.entry[133].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Amanda", (obj.entry[133].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[133].resource!! as Patient).gender))
        assertEquals("1956-06-15", (obj.entry[133].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[133].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[134].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[134].resource!! as Patient).resourceType))
        assertTrue(stringMatch("205", (obj.entry[134].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[134].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[134].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[134].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[134].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[134].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[134].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577524", (obj.entry[134].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[134].resource!! as Patient).active != null) (obj.entry[134].resource!! as Patient).active else false, "Field: (obj.entry[134].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[134].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Greer", (obj.entry[134].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Dianne", (obj.entry[134].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[134].resource!! as Patient).gender))
        assertEquals("1953-07-28", (obj.entry[134].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[134].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[135].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[135].resource!! as Patient).resourceType))
        assertTrue(stringMatch("206", (obj.entry[135].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[135].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[135].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[135].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[135].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[135].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[135].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577525", (obj.entry[135].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[135].resource!! as Patient).active != null) (obj.entry[135].resource!! as Patient).active else false, "Field: (obj.entry[135].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[135].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Jones", (obj.entry[135].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Alan", (obj.entry[135].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[135].resource!! as Patient).gender))
        assertEquals("1965-06-19", (obj.entry[135].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[135].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[136].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[136].resource!! as Patient).resourceType))
        assertTrue(stringMatch("207", (obj.entry[136].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[136].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[136].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[136].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[136].resource!! as Patient).identifier[0].type!!.coding[0].system))
    }
}
