package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle83DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 454 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertTrue(stringMatch("Organization/1", (obj.entry[148].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[149].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[149].resource!! as Patient).resourceType))
        assertTrue(stringMatch("220", (obj.entry[149].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[149].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[149].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[149].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[149].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[149].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[149].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577539", (obj.entry[149].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[149].resource!! as Patient).active != null) (obj.entry[149].resource!! as Patient).active else false, "Field: (obj.entry[149].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[149].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Bass", (obj.entry[149].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Leon", (obj.entry[149].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[149].resource!! as Patient).gender))
        assertEquals("1940-06-07", (obj.entry[149].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[149].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[150].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[150].resource!! as Patient).resourceType))
        assertTrue(stringMatch("221", (obj.entry[150].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[150].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[150].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[150].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[150].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[150].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[150].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577540", (obj.entry[150].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[150].resource!! as Patient).active != null) (obj.entry[150].resource!! as Patient).active else false, "Field: (obj.entry[150].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[150].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Thomas", (obj.entry[150].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Bruce", (obj.entry[150].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[150].resource!! as Patient).gender))
        assertEquals("1959-10-17", (obj.entry[150].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[150].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[151].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[151].resource!! as Patient).resourceType))
        assertTrue(stringMatch("222", (obj.entry[151].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[151].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[151].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[151].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[151].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[151].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[151].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577541", (obj.entry[151].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[151].resource!! as Patient).active != null) (obj.entry[151].resource!! as Patient).active else false, "Field: (obj.entry[151].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[151].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Oliver", (obj.entry[151].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Gina", (obj.entry[151].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[151].resource!! as Patient).gender))
        assertEquals("1950-09-15", (obj.entry[151].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[151].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[152].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[152].resource!! as Patient).resourceType))
        assertTrue(stringMatch("223", (obj.entry[152].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[152].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[152].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[152].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[152].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[152].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[152].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577542", (obj.entry[152].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[152].resource!! as Patient).active != null) (obj.entry[152].resource!! as Patient).active else false, "Field: (obj.entry[152].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[152].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Goodman", (obj.entry[152].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Francis", (obj.entry[152].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[152].resource!! as Patient).gender))
        assertEquals("1939-12-23", (obj.entry[152].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[152].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[153].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[153].resource!! as Patient).resourceType))
    }
}
