package com.juicelabs.fhir.model

import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test

class Bundle90DataTest : DataTests() {
    @Test
    fun `patient-examples-cypress-template 461 Test`() {
        val json = File("./src/test/resources/model/sample_data/patient-examples-cypress-template.json").readTextAndClose()
        val obj = mapper.fromJson(json, Bundle::class.java)
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[178].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[178].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[178].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[178].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[178].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[178].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577568", (obj.entry[178].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[178].resource!! as Patient).active != null) (obj.entry[178].resource!! as Patient).active else false, "Field: (obj.entry[178].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[178].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Henry", (obj.entry[178].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Ricky", (obj.entry[178].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[178].resource!! as Patient).gender))
        assertEquals("1960-06-22", (obj.entry[178].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[178].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[179].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[179].resource!! as Patient).resourceType))
        assertTrue(stringMatch("250", (obj.entry[179].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[179].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[179].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[179].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[179].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[179].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[179].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577569", (obj.entry[179].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[179].resource!! as Patient).active != null) (obj.entry[179].resource!! as Patient).active else false, "Field: (obj.entry[179].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[179].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Byrd", (obj.entry[179].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Mitchell", (obj.entry[179].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("male", (obj.entry[179].resource!! as Patient).gender))
        assertEquals("1995-08-07", (obj.entry[179].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[179].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[180].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[180].resource!! as Patient).resourceType))
        assertTrue(stringMatch("251", (obj.entry[180].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[180].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[180].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[180].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[180].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[180].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[180].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577570", (obj.entry[180].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[180].resource!! as Patient).active != null) (obj.entry[180].resource!! as Patient).active else false, "Field: (obj.entry[180].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[180].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Gilbert", (obj.entry[180].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Danielle", (obj.entry[180].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[180].resource!! as Patient).gender))
        assertEquals("1945-10-08", (obj.entry[180].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[180].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[181].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[181].resource!! as Patient).resourceType))
        assertTrue(stringMatch("252", (obj.entry[181].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[181].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[181].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[181].resource!! as Patient).text!!.div))
        assertTrue(stringMatch("http://hl7.org/fhir/v2/0203", (obj.entry[181].resource!! as Patient).identifier[0].type!!.coding[0].system))
        assertTrue(stringMatch("SS", (obj.entry[181].resource!! as Patient).identifier[0].type!!.coding[0].code))
        assertTrue(stringMatch("https://github.com/projectcyp", (obj.entry[181].resource!! as Patient).identifier[0].system))
        assertTrue(stringMatch("577571", (obj.entry[181].resource!! as Patient).identifier[0].value))
        assertEquals(true, if ((obj.entry[181].resource!! as Patient).active != null) (obj.entry[181].resource!! as Patient).active else false, "Field: (obj.entry[181].resource!! as Patient).active")
        assertTrue(stringMatch("official", (obj.entry[181].resource!! as Patient).name[0].use))
        assertTrue(stringMatch("Stevens", (obj.entry[181].resource!! as Patient).name[0].family))
        assertTrue(stringMatch("Terri", (obj.entry[181].resource!! as Patient).name[0].given[0]))
        assertTrue(stringMatch("female", (obj.entry[181].resource!! as Patient).gender))
        assertEquals("2000-11-02", (obj.entry[181].resource!! as Patient).birthDate.toString())
        assertTrue(stringMatch("Organization/1", (obj.entry[181].resource!! as Patient).managingOrganization!!.reference))
        assertTrue(stringMatch("http://hl7.org/fhir/Patient/2", obj.entry[182].fullUrl))
        assertTrue(stringMatch("Patient", (obj.entry[182].resource!! as Patient).resourceType))
        assertTrue(stringMatch("253", (obj.entry[182].resource!! as Patient).id))
        assertEquals("2012-06-03T23:45:32Z", (obj.entry[182].resource!! as Patient).meta!!.lastUpdated.toString())
        assertTrue(stringMatch("generated", (obj.entry[182].resource!! as Patient).text!!.status))
        assertTrue(stringMatch("<div xmlns=\"http://www.w3.org", (obj.entry[182].resource!! as Patient).text!!.div))
    }
}
